int main()
{
__asm__ __volatile__(
"	pushl	%ebp\n"
"	movl	%esp, %ebp\n"
"	pushl	%edi\n"
"	pushl	%esi\n"
"	pushl	%ebx\n"
"	subl	$76, %esp\n"
"	xorl	%ebx, %ebx\n"
"	movl	%ebx, _dx+460\n"
"	xorl	%ecx, %ecx\n"
"	movl	%ecx, _dx+440\n"
"	movl	$-1, %edx\n"
"	movl	%edx, _dx+476\n"
"	movl	$1, %edi\n"
"	movl	%edi, _dx+404\n"
"	xorl	%esi, %esi\n"
"	movl	%esi, _dy+404\n"
"	xorl	%ebx, %ebx\n"
"	movl	%ebx, _dy+476\n"
"	movl	$-1, %ecx\n"
"	movl	%ecx, _dy+460\n"
"	movl	$1, %edx\n"
"	movl	%edx, _dy+440\n"
"	xorl	%eax, %eax\n"
"	movl	%eax, _ym+4\n"
"	xorl	%eax, %eax\n"
"	movl	%eax, _xm+4\n"
"	movl	$48, -24(%ebp)\n"
"L34:\n"
"	movl	-24(%ebp), %esi\n"
"	movl	$1, %eax\n"
"	movl	%eax, _isdig.3(,%esi,4)\n"
"	incl	%esi\n"
"	movl	%esi, -24(%ebp)\n"
"	cmpl	$57, %esi\n"
"	jle	L34\n"
"	movl	$48, -24(%ebp)\n"
"L39:\n"
"	movl	-24(%ebp), %edi\n"
"	movl	$1, %edx\n"
"	movl	%edx, _isdigm.4(,%edi,4)\n"
"	incl	%edi\n"
"	movl	%edi, -24(%ebp)\n"
"	cmpl	$57, %edi\n"
"	jle	L39\n"
"	movl	$1, %edi\n"
"	movl	%edi, _isdigm.4+180\n"
"	movl	$1048576, %esi\n"
"	movl	%esi, 8(%esp)\n"
"	movl	$_inbuf.0, %esi\n"
"	movl	%esi, 4(%esp)\n"
"	movl	$0, (%esp)\n"
"	call	read\n"
"	movl	$_outbuf.1, -20(%ebp)\n"
"	movsbl	_inbuf.0,%ebx\n"
"	movl	_isdig.3(,%ebx,4), %ecx\n"
"	testl	%ecx, %ecx\n"
"	jne	L169\n"
"L43:\n"
"	incl	%esi\n"
"	movzbl	(%esi), %ecx\n"
"	movsbl	%cl,%ebx\n"
"	movl	_isdig.3(,%ebx,4), %edx\n"
"	testl	%edx, %edx\n"
"	je	L43\n"
"L137:\n"
"	movsbl	%cl,%edx\n"
"	subl	$48, %edx\n"
"	movl	%edx, -32(%ebp)\n"
"	incl	%esi\n"
"	movzbl	(%esi), %ecx\n"
"	movsbl	%cl,%eax\n"
"	movl	_isdig.3(,%eax,4), %edi\n"
"	testl	%edi, %edi\n"
"	je	L139\n"
"	movl	%eax, %edx\n"
"L48:\n"
"	movl	-32(%ebp), %eax\n"
"	leal	(%eax,%eax,4), %ebx\n"
"	leal	-48(%edx,%ebx,2), %ecx\n"
"	movl	%ecx, -32(%ebp)\n"
"	incl	%esi\n"
"	movzbl	(%esi), %ecx\n"
"	movsbl	%cl,%edi\n"
"	movl	%edi, %edx\n"
"	movl	_isdig.3(,%edi,4), %ebx\n"
"	testl	%ebx, %ebx\n"
"	jne	L48\n"
"L139:\n"
"	movl	-32(%ebp), %edx\n"
"	decl	-32(%ebp)\n"
"	testl	%edx, %edx\n"
"	jle	L141\n"
"L131:\n"
"	movsbl	%cl,%edi\n"
"	movl	_isdig.3(,%edi,4), %ebx\n"
"	testl	%ebx, %ebx\n"
"	jne	L143\n"
"	.p2align 4,,15\n"
"L55:\n"
"	incl	%esi\n"
"	movzbl	(%esi), %ecx\n"
"	movsbl	%cl,%ebx\n"
"	movl	_isdig.3(,%ebx,4), %edx\n"
"	testl	%edx, %edx\n"
"	je	L55\n"
"L143:\n"
"	movsbl	%cl,%edx\n"
"	leal	-48(%edx), %ebx\n"
"	incl	%esi\n"
"	movzbl	(%esi), %ecx\n"
"	movsbl	%cl,%eax\n"
"	movl	_isdig.3(,%eax,4), %edi\n"
"	testl	%edi, %edi\n"
"	je	L145\n"
"	movl	%eax, %edx\n"
"	.p2align 4,,15\n"
"L60:\n"
"	leal	(%ebx,%ebx,4), %ecx\n"
"	leal	-48(%edx,%ecx,2), %ebx\n"
"	incl	%esi\n"
"	movzbl	(%esi), %ecx\n"
"	movsbl	%cl,%edi\n"
"	movl	%edi, %edx\n"
"	movl	_isdig.3(,%edi,4), %edi\n"
"	testl	%edi, %edi\n"
"	jne	L60\n"
"L145:\n"
"	movl	%ebx, _n\n"
"	movsbl	%cl,%edx\n"
"	movl	_isdig.3(,%edx,4), %ebx\n"
"	testl	%ebx, %ebx\n"
"	jne	L147\n"
"	.p2align 4,,15\n"
"L64:\n"
"	incl	%esi\n"
"	movzbl	(%esi), %ecx\n"
"	movsbl	%cl,%ebx\n"
"	movl	_isdig.3(,%ebx,4), %edi\n"
"	testl	%edi, %edi\n"
"	je	L64\n"
"L147:\n"
"	movsbl	%cl,%edx\n"
"	leal	-48(%edx), %ebx\n"
"	incl	%esi\n"
"	movzbl	(%esi), %ecx\n"
"	movsbl	%cl,%eax\n"
"	movl	_isdig.3(,%eax,4), %edi\n"
"	testl	%edi, %edi\n"
"	je	L149\n"
"	movl	%eax, %edx\n"
"	.p2align 4,,15\n"
"L69:\n"
"	leal	(%ebx,%ebx,4), %ecx\n"
"	leal	-48(%edx,%ecx,2), %ebx\n"
"	incl	%esi\n"
"	movzbl	(%esi), %ecx\n"
"	movsbl	%cl,%edi\n"
"	movl	%edi, %edx\n"
"	movl	_isdig.3(,%edi,4), %edi\n"
"	testl	%edi, %edi\n"
"	jne	L69\n"
"L149:\n"
"	movl	%ebx, _m\n"
"	movl	$0, -24(%ebp)\n"
"	cmpl	%ebx, -24(%ebp)\n"
"	jge	L151\n"
"	movl	%ebx, %edi\n"
"	.p2align 4,,15\n"
"L106:\n"
"	movsbl	%cl,%edx\n"
"	movl	_isdigm.4(,%edx,4), %ebx\n"
"	testl	%ebx, %ebx\n"
"	jne	L153\n"
"	.p2align 4,,15\n"
"L77:\n"
"	incl	%esi\n"
"	movzbl	(%esi), %ecx\n"
"	movsbl	%cl,%ebx\n"
"	movl	_isdigm.4(,%ebx,4), %edx\n"
"	testl	%edx, %edx\n"
"	je	L77\n"
"L153:\n"
"	cmpb	$45, %cl\n"
"	je	L171\n"
"	movsbl	%cl,%edx\n"
"	leal	-48(%edx), %ebx\n"
"	incl	%esi\n"
"	movzbl	(%esi), %ecx\n"
"	movsbl	%cl,%eax\n"
"	movl	_isdig.3(,%eax,4), %edx\n"
"	testl	%edx, %edx\n"
"	je	L84\n"
"	movl	%eax, %edx\n"
"	.p2align 4,,15\n"
"L89:\n"
"	leal	(%ebx,%ebx,4), %ecx\n"
"	leal	-48(%edx,%ecx,2), %ebx\n"
"	incl	%esi\n"
"	movzbl	(%esi), %ecx\n"
"	movsbl	%cl,%eax\n"
"	movl	%eax, %edx\n"
"	movl	_isdig.3(,%eax,4), %eax\n"
"	testl	%eax, %eax\n"
"	jne	L89\n"
"L84:\n"
"	movl	-24(%ebp), %edx\n"
"	movl	%ebx, _ox(,%edx,4)\n"
"	movsbl	%cl,%edx\n"
"	movl	_isdigm.4(,%edx,4), %ebx\n"
"	testl	%ebx, %ebx\n"
"	jne	L158\n"
"	.p2align 4,,15\n"
"L93:\n"
"	incl	%esi\n"
"	movzbl	(%esi), %ecx\n"
"	movsbl	%cl,%ebx\n"
"	movl	_isdigm.4(,%ebx,4), %edx\n"
"	testl	%edx, %edx\n"
"	je	L93\n"
"L158:\n"
"	cmpb	$45, %cl\n"
"	je	L172\n"
"	movsbl	%cl,%edx\n"
"	leal	-48(%edx), %ebx\n"
"	incl	%esi\n"
"	movzbl	(%esi), %edx\n"
"	movb	%dl, %cl\n"
"	movsbl	%dl,%eax\n"
"	movl	_isdig.3(,%eax,4), %edx\n"
"	testl	%edx, %edx\n"
"	je	L100\n"
"	movl	%eax, %edx\n"
"	.p2align 4,,15\n"
"L105:\n"
"	leal	(%ebx,%ebx,4), %ecx\n"
"	leal	-48(%edx,%ecx,2), %ebx\n"
"	incl	%esi\n"
"	movzbl	(%esi), %edx\n"
"	movb	%dl, %cl\n"
"	movsbl	%dl,%eax\n"
"	movl	%eax, %edx\n"
"	movl	_isdig.3(,%eax,4), %eax\n"
"	testl	%eax, %eax\n"
"	jne	L105\n"
"L100:\n"
"	movl	-24(%ebp), %eax\n"
"	movl	%ebx, _oy(,%eax,4)\n"
"	incl	%eax\n"
"	movl	%eax, -24(%ebp)\n"
"	cmpl	%edi, %eax\n"
"	jl	L106\n"
"L151:\n"
"	movl	_n, %ecx\n"
"	movl	_sol_list(,%ecx,4), %edx\n"
"	movl	_pre_list(,%ecx,4), %ebx\n"
"	movl	%ebx, -36(%ebp)\n"
"	xorl	%ebx, %ebx\n"
"	movl	$1, -28(%ebp)\n"
"	movl	$0, -24(%ebp)\n"
"	movl	(%edx), %edi\n"
"	testl	%edi, %edi\n"
"	je	L163\n"
"	movl	%edx, %edi\n"
"	.p2align 4,,15\n"
"L119:\n"
"	movl	-28(%ebp), %ecx\n"
"	movl	%ecx, -60(%ebp)\n"
"	movl	-24(%ebp), %eax\n"
"	movl	-36(%ebp), %edx\n"
"	movl	(%edx,%eax,4), %eax\n"
"	movl	%eax, -40(%ebp)\n"
"	cmpl	%eax, %ecx\n"
"	jle	L111\n"
"	movl	%eax, -60(%ebp)\n"
"L111:\n"
"	movl	-28(%ebp), %eax\n"
"	cmpl	%eax, -60(%ebp)\n"
"	je	L173\n"
"L112:\n"
"	movl	-60(%ebp), %edx\n"
"	incl	%edx\n"
"	movl	%edx, 4(%esp)\n"
"	movl	(%edi), %ecx\n"
"	addl	%ecx, -60(%ebp)\n"
"	movl	-60(%ebp), %edx\n"
"	movl	%edx, (%esp)\n"
"	call	_check\n"
"	movl	%eax, -28(%ebp)\n"
"	cmpl	_n, %eax\n"
"	je	L174\n"
"L109:\n"
"	incl	-24(%ebp)\n"
"	addl	$4, %edi\n"
"	movl	(%edi), %ecx\n"
"	testl	%ecx, %ecx\n"
"	jne	L119\n"
"L163:\n"
"	movl	-20(%ebp), %eax\n"
"	movb	$70, (%eax)\n"
"	incl	%eax\n"
"	movb	$111, (%eax)\n"
"	incl	%eax\n"
"	movb	$117, (%eax)\n"
"	incl	%eax\n"
"	movb	$110, (%eax)\n"
"	incl	%eax\n"
"	movb	$100, (%eax)\n"
"	incl	%eax\n"
"	movb	$32, (%eax)\n"
"	incl	%eax\n"
"	movl	%eax, -20(%ebp)\n"
"	testl	%ebx, %ebx\n"
"	jne	L120\n"
"	movb	$48, (%eax)\n"
"	incl	%eax\n"
"	movl	%eax, -20(%ebp)\n"
"L121:\n"
"	movl	-20(%ebp), %eax\n"
"	movb	$32, (%eax)\n"
"	incl	%eax\n"
"	movb	$103, (%eax)\n"
"	incl	%eax\n"
"	movb	$111, (%eax)\n"
"	incl	%eax\n"
"	movb	$108, (%eax)\n"
"	incl	%eax\n"
"	movb	$121, (%eax)\n"
"	incl	%eax\n"
"	movb	$103, (%eax)\n"
"	incl	%eax\n"
"	movb	$111, (%eax)\n"
"	incl	%eax\n"
"	movb	$110, (%eax)\n"
"	incl	%eax\n"
"	movb	$40, (%eax)\n"
"	incl	%eax\n"
"	movb	$115, (%eax)\n"
"	incl	%eax\n"
"	movb	$41, (%eax)\n"
"	incl	%eax\n"
"	movb	$46, (%eax)\n"
"	incl	%eax\n"
"	movb	$10, (%eax)\n"
"	incl	%eax\n"
"	movb	$10, (%eax)\n"
"	incl	%eax\n"
"	movl	%eax, -20(%ebp)\n"
"	movl	-32(%ebp), %edx\n"
"	decl	-32(%ebp)\n"
"	testl	%edx, %edx\n"
"	jle	L141\n"
"	movzbl	(%esi), %ecx\n"
"	jmp	L131\n"
"L120:\n"
"	movl	$_tmp.2, %ecx\n"
"	jle	L167\n"
"	movl	$1717986919, %edi\n"
"	.p2align 4,,15\n"
"L126:\n"
"	movl	%ebx, %eax\n"
"	imull	%edi\n"
"	movl	%eax, -48(%ebp)\n"
"	movl	%edx, -44(%ebp)\n"
"	movl	-44(%ebp), %edx\n"
"	sarl	$2, %edx\n"
"	movl	%ebx, %eax\n"
"	sarl	$31, %eax\n"
"	subl	%eax, %edx\n"
"	leal	(%edx,%edx,4), %eax\n"
"	addl	%eax, %eax\n"
"	subl	%eax, %ebx\n"
"	movb	%bl, %al\n"
"	addb	$48, %al\n"
"	movb	%al, (%ecx)\n"
"	incl	%ecx\n"
"	movl	%edx, %ebx\n"
"	testl	%edx, %edx\n"
"	jg	L126\n"
"L167:\n"
"	decl	%ecx\n"
"	cmpl	$_tmp.2-1, %ecx\n"
"	jbe	L121\n"
"L130:\n"
"	movzbl	(%ecx), %ebx\n"
"	movl	-20(%ebp), %edi\n"
"	movb	%bl, (%edi)\n"
"	incl	%edi\n"
"	movl	%edi, -20(%ebp)\n"
"	decl	%ecx\n"
"	cmpl	$_tmp.2-1, %ecx\n"
"	ja	L130\n"
"	jmp	L121\n"
"L174:\n"
"	movl	(%edi), %ecx\n"
"	movzbl	(%ecx), %eax\n"
"	testb	%al, %al\n"
"	je	L165\n"
"	.p2align 4,,15\n"
"L118:\n"
"	incl	%ecx\n"
"	movl	-20(%ebp), %edx\n"
"	movb	%al, (%edx)\n"
"	incl	%edx\n"
"	movl	%edx, -20(%ebp)\n"
"	movzbl	(%ecx), %eax\n"
"	testb	%al, %al\n"
"	jne	L118\n"
"L165:\n"
"	movl	-20(%ebp), %eax\n"
"	movb	$10, (%eax)\n"
"	incl	%eax\n"
"	movl	%eax, -20(%ebp)\n"
"	incl	%ebx\n"
"	jmp	L109\n"
"L173:\n"
"	movl	(%edi), %eax\n"
"	movl	-28(%ebp), %ecx\n"
"	movzbl	(%ecx,%eax), %edx\n"
"	movl	-4(%edi), %eax\n"
"	cmpb	%dl, (%ecx,%eax)\n"
"	jne	L112\n"
"	jmp	L109\n"
"L172:\n"
"	incl	%esi\n"
"	movsbl	(%esi),%ecx\n"
"	leal	-48(%ecx), %ebx\n"
"	incl	%esi\n"
"	movzbl	(%esi), %ecx\n"
"	movsbl	%cl,%eax\n"
"	movl	_isdig.3(,%eax,4), %edx\n"
"	testl	%edx, %edx\n"
"	je	L160\n"
"	movl	%eax, %edx\n"
"	.p2align 4,,15\n"
"L99:\n"
"	leal	(%ebx,%ebx,4), %ecx\n"
"	leal	-48(%edx,%ecx,2), %ebx\n"
"	incl	%esi\n"
"	movzbl	(%esi), %ecx\n"
"	movsbl	%cl,%eax\n"
"	movl	%eax, %edx\n"
"	movl	_isdig.3(,%eax,4), %eax\n"
"	testl	%eax, %eax\n"
"	jne	L99\n"
"L160:\n"
"	negl	%ebx\n"
"	jmp	L100\n"
"L171:\n"
"	incl	%esi\n"
"	movsbl	(%esi),%ecx\n"
"	leal	-48(%ecx), %ebx\n"
"	incl	%esi\n"
"	movzbl	(%esi), %ecx\n"
"	movsbl	%cl,%eax\n"
"	movl	_isdig.3(,%eax,4), %edx\n"
"	testl	%edx, %edx\n"
"	je	L155\n"
"	movl	%eax, %edx\n"
"	.p2align 4,,15\n"
"L83:\n"
"	leal	(%ebx,%ebx,4), %ecx\n"
"	leal	-48(%edx,%ecx,2), %ebx\n"
"	incl	%esi\n"
"	movzbl	(%esi), %ecx\n"
"	movsbl	%cl,%eax\n"
"	movl	%eax, %edx\n"
"	movl	_isdig.3(,%eax,4), %eax\n"
"	testl	%eax, %eax\n"
"	jne	L83\n"
"L155:\n"
"	negl	%ebx\n"
"	jmp	L84\n"
"L169:\n"
"	movzbl	_inbuf.0, %ecx\n"
"	jmp	L137\n"
"L141:\n"
"	subl	$_outbuf.1, -20(%ebp)\n"
"	movl	-20(%ebp), %ecx\n"
"	movl	%ecx, 8(%esp)\n"
"	movl	$_outbuf.1, %esi\n"
"	movl	%esi, 4(%esp)\n"
"	movl	$1, (%esp)\n"
"	call	write\n"
"	movl	$0, (%esp)\n"
"	call	exit\n"
"	.comm	_n, 16	 # 4\n"
"	.comm	_m, 16	 # 4\n"
"	.comm	_ox, 256	 # 256\n"
"	.comm	_oy, 256	 # 256\n"
"	.comm	_dx, 1024	 # 1024\n"
"	.comm	_dy, 1024	 # 1024\n"
"	.comm	_xm, 1024	 # 1024\n"
"	.comm	_ym, 1024	 # 1024\n"
"	.p2align 4,,15\n"
"_check:\n"
"	pushl	%ebp\n"
"	movl	%esp, %ebp\n"
"	pushl	%edi\n"
"	pushl	%esi\n"
"	pushl	%ebx\n"
"	subl	$20, %esp\n"
"	movl	12(%ebp), %ebx\n"
"	movl	_xm(,%ebx,4), %esi\n"
"	movl	_ym(,%ebx,4), %edi\n"
"	movl	_n, %edx\n"
"	movl	%edx, -28(%ebp)\n"
"	cmpl	%edx, %ebx\n"
"	jg	L180\n"
"	movl	_m, %eax\n"
"	movl	%eax, -32(%ebp)\n"
"	.p2align 4,,15\n"
"L28:\n"
"	movl	%esi, _xm(,%ebx,4)\n"
"	movl	%edi, _ym(,%ebx,4)\n"
"	movl	8(%ebp), %ecx\n"
"	movsbl	(%ecx),%eax\n"
"	movl	%ebx, %edx\n"
"	movl	_dx(,%eax,4), %ecx\n"
"	imull	%ecx, %edx\n"
"	leal	(%edx,%esi), %ecx\n"
"	movl	%ecx, -16(%ebp)\n"
"	movl	%ebx, %edx\n"
"	movl	_dy(,%eax,4), %ecx\n"
"	imull	%ecx, %edx\n"
"	leal	(%edx,%edi), %eax\n"
"	cmpl	-16(%ebp), %esi\n"
"	je	L188\n"
"	xorl	%ecx, %ecx\n"
"	cmpl	-32(%ebp), %ecx\n"
"	jge	L4\n"
"	leal	-1(%ebx), %edx\n"
"	movl	%edx, -24(%ebp)\n"
"	.p2align 4,,15\n"
"L27:\n"
"	cmpl	%edi, _oy(,%ecx,4)\n"
"	je	L189\n"
"L20:\n"
"	incl	%ecx\n"
"	cmpl	-32(%ebp), %ecx\n"
"	jl	L27\n"
"L4:\n"
"	incl	%ebx\n"
"	incl	8(%ebp)\n"
"	movl	-16(%ebp), %esi\n"
"	movl	%eax, %edi\n"
"	cmpl	-28(%ebp), %ebx\n"
"	jle	L28\n"
"L180:\n"
"	movl	-28(%ebp), %eax\n"
"L1:\n"
"	addl	$20, %esp\n"
"	popl	%ebx\n"
"	popl	%esi\n"
"	popl	%edi\n"
"	popl	%ebp\n"
"	ret\n"
"	.p2align 4,,7\n"
"L189:\n"
"	movl	_ox(,%ecx,4), %edx\n"
"	cmpl	%edx, %esi\n"
"	jg	L25\n"
"	cmpl	-16(%ebp), %edx\n"
"	jle	L24\n"
"L25:\n"
"	cmpl	%edx, -16(%ebp)\n"
"	jg	L20\n"
"	cmpl	%esi, %edx\n"
"	jg	L20\n"
"L24:\n"
"	movl	-24(%ebp), %eax\n"
"	jmp	L1\n"
"L188:\n"
"	xorl	%ecx, %ecx\n"
"	cmpl	-32(%ebp), %ecx\n"
"	jge	L4\n"
"	leal	-1(%ebx), %edx\n"
"	movl	%edx, -20(%ebp)\n"
"	.p2align 4,,15\n"
"L16:\n"
"	cmpl	%esi, _ox(,%ecx,4)\n"
"	je	L190\n"
"L9:\n"
"	incl	%ecx\n"
"	cmpl	-32(%ebp), %ecx\n"
"	jl	L16\n"
"	jmp	L4\n"
"	.p2align 4,,7\n"
"L190:\n"
"	movl	_oy(,%ecx,4), %edx\n"
"	cmpl	%edx, %edi\n"
"	jg	L14\n"
"	cmpl	%eax, %edx\n"
"	jle	L13\n"
"L14:\n"
"	cmpl	%edx, %eax\n"
"	jg	L9\n"
"	cmpl	%edi, %edx\n"
"	jg	L9\n"
"L13:\n"
"	movl	-20(%ebp), %eax\n"
"	jmp	L1\n"

"LC0:\n"
"	.ascii \"enwnwse\\0\"\n"
"LC1:\n"
"	.ascii \"eswswne\\0\"\n"
"LC2:\n"
"	.ascii \"neseswn\\0\"\n"
"LC3:\n"
"	.ascii \"nwswsen\\0\"\n"
"LC4:\n"
"	.ascii \"senenws\\0\"\n"
"LC5:\n"
"	.ascii \"swnwnes\\0\"\n"
"LC6:\n"
"	.ascii \"wnenesw\\0\"\n"
"LC7:\n"
"	.ascii \"wsesenw\\0\"\n"
"	.align 32\n"
"_sol7:\n"
"	.long	LC0\n"
"	.long	LC1\n"
"	.long	LC2\n"
"	.long	LC3\n"
"	.long	LC4\n"
"	.long	LC5\n"
"	.long	LC6\n"
"	.long	LC7\n"
"	.long	0\n"
"	.align 32\n"
"_pre7:\n"
"	.long	0\n"
"	.long	1\n"
"	.long	0\n"
"	.long	1\n"
"	.long	0\n"
"	.long	1\n"
"	.long	0\n"
"	.long	1\n"
"LC8:\n"
"	.ascii \"enwswsen\\0\"\n"
"LC9:\n"
"	.ascii \"eswnwnes\\0\"\n"
"LC10:\n"
"	.ascii \"neswswne\\0\"\n"
"LC11:\n"
"	.ascii \"nwsesenw\\0\"\n"
"LC12:\n"
"	.ascii \"senwnwse\\0\"\n"
"LC13:\n"
"	.ascii \"swnenesw\\0\"\n"
"LC14:\n"
"	.ascii \"wneseswn\\0\"\n"
"LC15:\n"
"	.ascii \"wsenenws\\0\"\n"
"	.align 32\n"
"_sol8:\n"
"	.long	LC8\n"
"	.long	LC9\n"
"	.long	LC10\n"
"	.long	LC11\n"
"	.long	LC12\n"
"	.long	LC13\n"
"	.long	LC14\n"
"	.long	LC15\n"
"	.long	0\n"
"	.align 32\n"
"_pre8:\n"
"	.long	0\n"
"	.long	1\n"
"	.long	0\n"
"	.long	1\n"
"	.long	0\n"
"	.long	1\n"
"	.long	0\n"
"	.long	1\n"
"LC16:\n"
"	.ascii \"enenwswnwswsene\\0\"\n"
"LC17:\n"
"	.ascii \"enenwswswnwnese\\0\"\n"
"LC18:\n"
"	.ascii \"eneswnwnwswnese\\0\"\n"
"LC19:\n"
"	.ascii \"eneswswswswnene\\0\"\n"
"LC20:\n"
"	.ascii \"enwneswnwseswne\\0\"\n"
"LC21:\n"
"	.ascii \"enwseswswsenwne\\0\"\n"
"LC22:\n"
"	.ascii \"enwswnenwsenesw\\0\"\n"
"LC23:\n"
"	.ascii \"enwswseseswnwne\\0\"\n"
"LC24:\n"
"	.ascii \"enwswseswsenenw\\0\"\n"
"LC25:\n"
"	.ascii \"esenwnwnwnwsese\\0\"\n"
"LC26:\n"
"	.ascii \"esenwswswnwsene\\0\"\n"
"LC27:\n"
"	.ascii \"eseswnwnwswsene\\0\"\n"
"LC28:\n"
"	.ascii \"eseswnwswnwnese\\0\"\n"
"LC29:\n"
"	.ascii \"eswnenwnwneswse\\0\"\n"
"LC30:\n"
"	.ascii \"eswnwnenenwswse\\0\"\n"
"LC31:\n"
"	.ascii \"eswnwnenwnesesw\\0\"\n"
"LC32:\n"
"	.ascii \"eswnwseswnesenw\\0\"\n"
"LC33:\n"
"	.ascii \"eswsenwswnenwse\\0\"\n"
"LC34:\n"
"	.ascii \"neneswseswswnen\\0\"\n"
"LC35:\n"
"	.ascii \"neneswswsesenwn\\0\"\n"
"LC36:\n"
"	.ascii \"nenwseseswsenwn\\0\"\n"
"LC37:\n"
"	.ascii \"nenwswswswsenen\\0\"\n"
"LC38:\n"
"	.ascii \"nesenwseswnwsen\\0\"\n"
"LC39:\n"
"	.ascii \"neswnwswswnesen\\0\"\n"
"LC40:\n"
"	.ascii \"neswseneswnenws\\0\"\n"
"LC41:\n"
"	.ascii \"neswswnwnwsesen\\0\"\n"
"LC42:\n"
"	.ascii \"neswswnwswnenes\\0\"\n"
"LC43:\n"
"	.ascii \"nwneseseseswnwn\\0\"\n"
"LC44:\n"
"	.ascii \"nwneswswseswnen\\0\"\n"
"LC45:\n"
"	.ascii \"nwnwseseswswnen\\0\"\n"
"LC46:\n"
"	.ascii \"nwnwseswsesenwn\\0\"\n"
"LC47:\n"
"	.ascii \"nwsenesesenwswn\\0\"\n"
"LC48:\n"
"	.ascii \"nwseseneneswswn\\0\"\n"
"LC49:\n"
"	.ascii \"nwsesenesenwnws\\0\"\n"
"LC50:\n"
"	.ascii \"nwseswnwsenwnes\\0\"\n"
"LC51:\n"
"	.ascii \"nwswneswseneswn\\0\"\n"
"LC52:\n"
"	.ascii \"seneswnenwswnes\\0\"\n"
"LC53:\n"
"	.ascii \"senwnesenwseswn\\0\"\n"
"LC54:\n"
"	.ascii \"senwnwswnwsesen\\0\"\n"
"LC55:\n"
"	.ascii \"senwnwswswnenes\\0\"\n"
"LC56:\n"
"	.ascii \"senwswnwnwsenes\\0\"\n"
"LC57:\n"
"	.ascii \"sesenwnenwnwses\\0\"\n"
"LC58:\n"
"	.ascii \"sesenwnwnenesws\\0\"\n"
"LC59:\n"
"	.ascii \"seswnenenwnesws\\0\"\n"
"LC60:\n"
"	.ascii \"seswnwnwnwneses\\0\"\n"
"LC61:\n"
"	.ascii \"swneneseneswswn\\0\"\n"
"LC62:\n"
"	.ascii \"swnenesesenwnws\\0\"\n"
"LC63:\n"
"	.ascii \"swnenwswneswsen\\0\"\n"
"LC64:\n"
"	.ascii \"swneseneneswnws\\0\"\n"
"LC65:\n"
"	.ascii \"swnwsenwnesenws\\0\"\n"
"LC66:\n"
"	.ascii \"swsenenenenwsws\\0\"\n"
"LC67:\n"
"	.ascii \"swsenwnwnenwses\\0\"\n"
"LC68:\n"
"	.ascii \"swswnenenwnwses\\0\"\n"
"LC69:\n"
"	.ascii \"swswnenwnenesws\\0\"\n"
"LC70:\n"
"	.ascii \"wnenwseneswsenw\\0\"\n"
"LC71:\n"
"	.ascii \"wnesenwneswnwse\\0\"\n"
"LC72:\n"
"	.ascii \"wneseswseswnwne\\0\"\n"
"LC73:\n"
"	.ascii \"wneseswswsenenw\\0\"\n"
"LC74:\n"
"	.ascii \"wneswseseswnenw\\0\"\n"
"LC75:\n"
"	.ascii \"wnwneseneseswnw\\0\"\n"
"LC76:\n"
"	.ascii \"wnwnesesenenwsw\\0\"\n"
"LC77:\n"
"	.ascii \"wnwsenenesenwsw\\0\"\n"
"LC78:\n"
"	.ascii \"wnwsesesesenwnw\\0\"\n"
"LC79:\n"
"	.ascii \"wsenenwnenwswse\\0\"\n"
"LC80:\n"
"	.ascii \"wsenenwnwnesesw\\0\"\n"
"LC81:\n"
"	.ascii \"wseneswsenwswne\\0\"\n"
"LC82:\n"
"	.ascii \"wsenwnenenwsesw\\0\"\n"
"LC83:\n"
"	.ascii \"wseswnesenwnesw\\0\"\n"
"LC84:\n"
"	.ascii \"wswneneneneswsw\\0\"\n"
"LC85:\n"
"	.ascii \"wswneseseneswnw\\0\"\n"
"LC86:\n"
"	.ascii \"wswseneneseswnw\\0\"\n"
"LC87:\n"
"	.ascii \"wswsenesenenwsw\\0\"\n"
"	.align 32\n"
"_sol15:\n"
"	.long	LC16\n"
"	.long	LC17\n"
"	.long	LC18\n"
"	.long	LC19\n"
"	.long	LC20\n"
"	.long	LC21\n"
"	.long	LC22\n"
"	.long	LC23\n"
"	.long	LC24\n"
"	.long	LC25\n"
"	.long	LC26\n"
"	.long	LC27\n"
"	.long	LC28\n"
"	.long	LC29\n"
"	.long	LC30\n"
"	.long	LC31\n"
"	.long	LC32\n"
"	.long	LC33\n"
"	.long	LC34\n"
"	.long	LC35\n"
"	.long	LC36\n"
"	.long	LC37\n"
"	.long	LC38\n"
"	.long	LC39\n"
"	.long	LC40\n"
"	.long	LC41\n"
"	.long	LC42\n"
"	.long	LC43\n"
"	.long	LC44\n"
"	.long	LC45\n"
"	.long	LC46\n"
"	.long	LC47\n"
"	.long	LC48\n"
"	.long	LC49\n"
"	.long	LC50\n"
"	.long	LC51\n"
"	.long	LC52\n"
"	.long	LC53\n"
"	.long	LC54\n"
"	.long	LC55\n"
"	.long	LC56\n"
"	.long	LC57\n"
"	.long	LC58\n"
"	.long	LC59\n"
"	.long	LC60\n"
"	.long	LC61\n"
"	.long	LC62\n"
"	.long	LC63\n"
"	.long	LC64\n"
"	.long	LC65\n"
"	.long	LC66\n"
"	.long	LC67\n"
"	.long	LC68\n"
"	.long	LC69\n"
"	.long	LC70\n"
"	.long	LC71\n"
"	.long	LC72\n"
"	.long	LC73\n"
"	.long	LC74\n"
"	.long	LC75\n"
"	.long	LC76\n"
"	.long	LC77\n"
"	.long	LC78\n"
"	.long	LC79\n"
"	.long	LC80\n"
"	.long	LC81\n"
"	.long	LC82\n"
"	.long	LC83\n"
"	.long	LC84\n"
"	.long	LC85\n"
"	.long	LC86\n"
"	.long	LC87\n"
"	.long	0\n"
"	.align 32\n"
"_pre15:\n"
"	.long	0\n"
"	.long	7\n"
"	.long	3\n"
"	.long	5\n"
"	.long	2\n"
"	.long	3\n"
"	.long	4\n"
"	.long	5\n"
"	.long	8\n"
"	.long	1\n"
"	.long	5\n"
"	.long	3\n"
"	.long	7\n"
"	.long	2\n"
"	.long	4\n"
"	.long	8\n"
"	.long	5\n"
"	.long	3\n"
"	.long	0\n"
"	.long	7\n"
"	.long	3\n"
"	.long	5\n"
"	.long	2\n"
"	.long	3\n"
"	.long	4\n"
"	.long	5\n"
"	.long	8\n"
"	.long	1\n"
"	.long	5\n"
"	.long	3\n"
"	.long	7\n"
"	.long	2\n"
"	.long	4\n"
"	.long	8\n"
"	.long	5\n"
"	.long	3\n"
"	.long	0\n"
"	.long	3\n"
"	.long	5\n"
"	.long	8\n"
"	.long	4\n"
"	.long	2\n"
"	.long	7\n"
"	.long	3\n"
"	.long	5\n"
"	.long	1\n"
"	.long	8\n"
"	.long	5\n"
"	.long	4\n"
"	.long	3\n"
"	.long	2\n"
"	.long	5\n"
"	.long	3\n"
"	.long	7\n"
"	.long	0\n"
"	.long	3\n"
"	.long	5\n"
"	.long	8\n"
"	.long	4\n"
"	.long	2\n"
"	.long	7\n"
"	.long	3\n"
"	.long	5\n"
"	.long	1\n"
"	.long	8\n"
"	.long	5\n"
"	.long	4\n"
"	.long	3\n"
"	.long	2\n"
"	.long	5\n"
"	.long	3\n"
"	.long	7\n"
"LC88:\n"
"	.ascii \"enenwnwnwswsesen\\0\"\n"
"LC89:\n"
"	.ascii \"enenwnwswnwsenes\\0\"\n"
"LC90:\n"
"	.ascii \"enenwswnwnwneses\\0\"\n"
"LC91:\n"
"	.ascii \"enenwswswswsenen\\0\"\n"
"LC92:\n"
"	.ascii \"eneswnwswswnesen\\0\"\n"
"LC93:\n"
"	.ascii \"eneswswnwnwsesen\\0\"\n"
"LC94:\n"
"	.ascii \"eneswswnwswnenes\\0\"\n"
"LC95:\n"
"	.ascii \"enwnenwnwseswsen\\0\"\n"
"LC96:\n"
"	.ascii \"enwneswnwnenwses\\0\"\n"
"LC97:\n"
"	.ascii \"enwneswswseswnen\\0\"\n"
"LC98:\n"
"	.ascii \"enwnwneneswswsen\\0\"\n"
"LC99:\n"
"	.ascii \"enwnwnenwseseswn\\0\"\n"
"LC100:\n"
"	.ascii \"enwnwneswnesenws\\0\"\n"
"LC101:\n"
"	.ascii \"enwswneswseneswn\\0\"\n"
"LC102:\n"
"	.ascii \"esenwnwswnwsesen\\0\"\n"
"LC103:\n"
"	.ascii \"esenwnwswswnenes\\0\"\n"
"LC104:\n"
"	.ascii \"esenwswnwnwsenes\\0\"\n"
"LC105:\n"
"	.ascii \"eseswnwnwnwneses\\0\"\n"
"LC106:\n"
"	.ascii \"eseswnwswswsenen\\0\"\n"
"LC107:\n"
"	.ascii \"eseswswnwswnesen\\0\"\n"
"LC108:\n"
"	.ascii \"eseswswswnwnenes\\0\"\n"
"LC109:\n"
"	.ascii \"eswnwsenwnesenws\\0\"\n"
"LC110:\n"
"	.ascii \"eswsenwnwnenwses\\0\"\n"
"LC111:\n"
"	.ascii \"eswsenwswseswnen\\0\"\n"
"LC112:\n"
"	.ascii \"eswseswswnenwnes\\0\"\n"
"LC113:\n"
"	.ascii \"eswswsenwseneswn\\0\"\n"
"LC114:\n"
"	.ascii \"eswswsesenwnwnes\\0\"\n"
"LC115:\n"
"	.ascii \"eswswseswnenenws\\0\"\n"
"LC116:\n"
"	.ascii \"neneseseswswnwne\\0\"\n"
"LC117:\n"
"	.ascii \"neneseswseswnenw\\0\"\n"
"LC118:\n"
"	.ascii \"neneswsesesenwnw\\0\"\n"
"LC119:\n"
"	.ascii \"neneswswswswnene\\0\"\n"
"LC120:\n"
"	.ascii \"nenwseswswsenwne\\0\"\n"
"LC121:\n"
"	.ascii \"nenwswseseswnwne\\0\"\n"
"LC122:\n"
"	.ascii \"nenwswseswsenenw\\0\"\n"
"LC123:\n"
"	.ascii \"neseneseswnwswne\\0\"\n"
"LC124:\n"
"	.ascii \"nesenwseseneswnw\\0\"\n"
"LC125:\n"
"	.ascii \"nesenwswswnwsene\\0\"\n"
"LC126:\n"
"	.ascii \"nesesenenwswswne\\0\"\n"
"LC127:\n"
"	.ascii \"neseseneswnwnwse\\0\"\n"
"LC128:\n"
"	.ascii \"nesesenwsenwnesw\\0\"\n"
"LC129:\n"
"	.ascii \"neswsenwswnenwse\\0\"\n"
"LC130:\n"
"	.ascii \"nwneseswseswnwne\\0\"\n"
"LC131:\n"
"	.ascii \"nwneseswswsenenw\\0\"\n"
"LC132:\n"
"	.ascii \"nwneswseseswnenw\\0\"\n"
"LC133:\n"
"	.ascii \"nwnwsesesesenwnw\\0\"\n"
"LC134:\n"
"	.ascii \"nwnwseswswswnene\\0\"\n"
"LC135:\n"
"	.ascii \"nwnwswseswsenwne\\0\"\n"
"LC136:\n"
"	.ascii \"nwnwswswsesenenw\\0\"\n"
"LC137:\n"
"	.ascii \"nwseswnesenwnesw\\0\"\n"
"LC138:\n"
"	.ascii \"nwswneseseneswnw\\0\"\n"
"LC139:\n"
"	.ascii \"nwswneswswnwsene\\0\"\n"
"LC140:\n"
"	.ascii \"nwswnwswsenesenw\\0\"\n"
"LC141:\n"
"	.ascii \"nwswswneswnenwse\\0\"\n"
"LC142:\n"
"	.ascii \"nwswswnwnesesenw\\0\"\n"
"LC143:\n"
"	.ascii \"nwswswnwsenenesw\\0\"\n"
"LC144:\n"
"	.ascii \"senenesenwswswne\\0\"\n"
"LC145:\n"
"	.ascii \"seneneseswnwnwse\\0\"\n"
"LC146:\n"
"	.ascii \"seneneswneswsenw\\0\"\n"
"LC147:\n"
"	.ascii \"senesenenwswnwse\\0\"\n"
"LC148:\n"
"	.ascii \"seneswnenesenwsw\\0\"\n"
"LC149:\n"
"	.ascii \"seneswnwnwswnese\\0\"\n"
"LC150:\n"
"	.ascii \"senwneswnwseswne\\0\"\n"
"LC151:\n"
"	.ascii \"sesenenenwnwswse\\0\"\n"
"LC152:\n"
"	.ascii \"sesenenwnenwsesw\\0\"\n"
"LC153:\n"
"	.ascii \"sesenwneneneswsw\\0\"\n"
"LC154:\n"
"	.ascii \"sesenwnwnwnwsese\\0\"\n"
"LC155:\n"
"	.ascii \"seswnenwnwneswse\\0\"\n"
"LC156:\n"
"	.ascii \"seswnwnenenwswse\\0\"\n"
"LC157:\n"
"	.ascii \"seswnwnenwnesesw\\0\"\n"
"LC158:\n"
"	.ascii \"swnenwseneswsenw\\0\"\n"
"LC159:\n"
"	.ascii \"swnwnwsenwseswne\\0\"\n"
"LC160:\n"
"	.ascii \"swnwnwswnesesenw\\0\"\n"
"LC161:\n"
"	.ascii \"swnwnwswsenenesw\\0\"\n"
"LC162:\n"
"	.ascii \"swnwsenenesenwsw\\0\"\n"
"LC163:\n"
"	.ascii \"swnwsenwnwswnese\\0\"\n"
"LC164:\n"
"	.ascii \"swnwswnwnesenesw\\0\"\n"
"LC165:\n"
"	.ascii \"swsenenwnenwswse\\0\"\n"
"LC166:\n"
"	.ascii \"swsenenwnwnesesw\\0\"\n"
"LC167:\n"
"	.ascii \"swsenwnenenwsesw\\0\"\n"
"LC168:\n"
"	.ascii \"swswneneneneswsw\\0\"\n"
"LC169:\n"
"	.ascii \"swswnenwnwnwsese\\0\"\n"
"LC170:\n"
"	.ascii \"swswnwnenwneswse\\0\"\n"
"LC171:\n"
"	.ascii \"swswnwnwnenesesw\\0\"\n"
"LC172:\n"
"	.ascii \"wnenenwneswswsen\\0\"\n"
"LC173:\n"
"	.ascii \"wnenenwnwseseswn\\0\"\n"
"LC174:\n"
"	.ascii \"wnenenwsenwswnes\\0\"\n"
"LC175:\n"
"	.ascii \"wnenwneneswseswn\\0\"\n"
"LC176:\n"
"	.ascii \"wnenwsenenwnesws\\0\"\n"
"LC177:\n"
"	.ascii \"wnenwseseswsenwn\\0\"\n"
"LC178:\n"
"	.ascii \"wnesenwseswnwsen\\0\"\n"
"LC179:\n"
"	.ascii \"wnwneneneseswswn\\0\"\n"
"LC180:\n"
"	.ascii \"wnwneneseneswnws\\0\"\n"
"LC181:\n"
"	.ascii \"wnwnesenenenwsws\\0\"\n"
"LC182:\n"
"	.ascii \"wnwneseseseswnwn\\0\"\n"
"LC183:\n"
"	.ascii \"wnwsenesesenwswn\\0\"\n"
"LC184:\n"
"	.ascii \"wnwseseneneswswn\\0\"\n"
"LC185:\n"
"	.ascii \"wnwsesenesenwnws\\0\"\n"
"LC186:\n"
"	.ascii \"wseneswnenwswnes\\0\"\n"
"LC187:\n"
"	.ascii \"wseseswneswnwsen\\0\"\n"
"LC188:\n"
"	.ascii \"wseseswsenwnwnes\\0\"\n"
"LC189:\n"
"	.ascii \"wseseswswnenenws\\0\"\n"
"LC190:\n"
"	.ascii \"wseswnenenwnesws\\0\"\n"
"LC191:\n"
"	.ascii \"wseswneseswsenwn\\0\"\n"
"LC192:\n"
"	.ascii \"wseswsesenwnenws\\0\"\n"
"LC193:\n"
"	.ascii \"wswneneseneswswn\\0\"\n"
"LC194:\n"
"	.ascii \"wswnenesesenwnws\\0\"\n"
"LC195:\n"
"	.ascii \"wswneseneneswnws\\0\"\n"
"LC196:\n"
"	.ascii \"wswsenenenenwsws\\0\"\n"
"LC197:\n"
"	.ascii \"wswseneseseswnwn\\0\"\n"
"LC198:\n"
"	.ascii \"wswsesenesenwswn\\0\"\n"
"LC199:\n"
"	.ascii \"wswsesesenenwnws\\0\"\n"
"	.align 32\n"
"_sol16:\n"
"	.long	LC88\n"
"	.long	LC89\n"
"	.long	LC90\n"
"	.long	LC91\n"
"	.long	LC92\n"
"	.long	LC93\n"
"	.long	LC94\n"
"	.long	LC95\n"
"	.long	LC96\n"
"	.long	LC97\n"
"	.long	LC98\n"
"	.long	LC99\n"
"	.long	LC100\n"
"	.long	LC101\n"
"	.long	LC102\n"
"	.long	LC103\n"
"	.long	LC104\n"
"	.long	LC105\n"
"	.long	LC106\n"
"	.long	LC107\n"
"	.long	LC108\n"
"	.long	LC109\n"
"	.long	LC110\n"
"	.long	LC111\n"
"	.long	LC112\n"
"	.long	LC113\n"
"	.long	LC114\n"
"	.long	LC115\n"
"	.long	LC116\n"
"	.long	LC117\n"
"	.long	LC118\n"
"	.long	LC119\n"
"	.long	LC120\n"
"	.long	LC121\n"
"	.long	LC122\n"
"	.long	LC123\n"
"	.long	LC124\n"
"	.long	LC125\n"
"	.long	LC126\n"
"	.long	LC127\n"
"	.long	LC128\n"
"	.long	LC129\n"
"	.long	LC130\n"
"	.long	LC131\n"
"	.long	LC132\n"
"	.long	LC133\n"
"	.long	LC134\n"
"	.long	LC135\n"
"	.long	LC136\n"
"	.long	LC137\n"
"	.long	LC138\n"
"	.long	LC139\n"
"	.long	LC140\n"
"	.long	LC141\n"
"	.long	LC142\n"
"	.long	LC143\n"
"	.long	LC144\n"
"	.long	LC145\n"
"	.long	LC146\n"
"	.long	LC147\n"
"	.long	LC148\n"
"	.long	LC149\n"
"	.long	LC150\n"
"	.long	LC151\n"
"	.long	LC152\n"
"	.long	LC153\n"
"	.long	LC154\n"
"	.long	LC155\n"
"	.long	LC156\n"
"	.long	LC157\n"
"	.long	LC158\n"
"	.long	LC159\n"
"	.long	LC160\n"
"	.long	LC161\n"
"	.long	LC162\n"
"	.long	LC163\n"
"	.long	LC164\n"
"	.long	LC165\n"
"	.long	LC166\n"
"	.long	LC167\n"
"	.long	LC168\n"
"	.long	LC169\n"
"	.long	LC170\n"
"	.long	LC171\n"
"	.long	LC172\n"
"	.long	LC173\n"
"	.long	LC174\n"
"	.long	LC175\n"
"	.long	LC176\n"
"	.long	LC177\n"
"	.long	LC178\n"
"	.long	LC179\n"
"	.long	LC180\n"
"	.long	LC181\n"
"	.long	LC182\n"
"	.long	LC183\n"
"	.long	LC184\n"
"	.long	LC185\n"
"	.long	LC186\n"
"	.long	LC187\n"
"	.long	LC188\n"
"	.long	LC189\n"
"	.long	LC190\n"
"	.long	LC191\n"
"	.long	LC192\n"
"	.long	LC193\n"
"	.long	LC194\n"
"	.long	LC195\n"
"	.long	LC196\n"
"	.long	LC197\n"
"	.long	LC198\n"
"	.long	LC199\n"
"	.long	0\n"
"	.align 32\n"
"_pre16:\n"
"	.long	0\n"
"	.long	7\n"
"	.long	5\n"
"	.long	7\n"
"	.long	3\n"
"	.long	5\n"
"	.long	9\n"
"	.long	2\n"
"	.long	5\n"
"	.long	7\n"
"	.long	4\n"
"	.long	8\n"
"	.long	7\n"
"	.long	3\n"
"	.long	1\n"
"	.long	9\n"
"	.long	5\n"
"	.long	3\n"
"	.long	7\n"
"	.long	5\n"
"	.long	7\n"
"	.long	2\n"
"	.long	3\n"
"	.long	7\n"
"	.long	5\n"
"	.long	4\n"
"	.long	7\n"
"	.long	8\n"
"	.long	0\n"
"	.long	7\n"
"	.long	5\n"
"	.long	7\n"
"	.long	3\n"
"	.long	5\n"
"	.long	9\n"
"	.long	2\n"
"	.long	5\n"
"	.long	7\n"
"	.long	4\n"
"	.long	8\n"
"	.long	7\n"
"	.long	3\n"
"	.long	1\n"
"	.long	9\n"
"	.long	5\n"
"	.long	3\n"
"	.long	7\n"
"	.long	5\n"
"	.long	7\n"
"	.long	2\n"
"	.long	3\n"
"	.long	7\n"
"	.long	5\n"
"	.long	4\n"
"	.long	7\n"
"	.long	8\n"
"	.long	0\n"
"	.long	8\n"
"	.long	7\n"
"	.long	4\n"
"	.long	5\n"
"	.long	7\n"
"	.long	3\n"
"	.long	2\n"
"	.long	7\n"
"	.long	5\n"
"	.long	7\n"
"	.long	3\n"
"	.long	5\n"
"	.long	9\n"
"	.long	1\n"
"	.long	3\n"
"	.long	7\n"
"	.long	8\n"
"	.long	4\n"
"	.long	7\n"
"	.long	5\n"
"	.long	2\n"
"	.long	9\n"
"	.long	5\n"
"	.long	3\n"
"	.long	7\n"
"	.long	5\n"
"	.long	7\n"
"	.long	0\n"
"	.long	8\n"
"	.long	7\n"
"	.long	4\n"
"	.long	5\n"
"	.long	7\n"
"	.long	3\n"
"	.long	2\n"
"	.long	7\n"
"	.long	5\n"
"	.long	7\n"
"	.long	3\n"
"	.long	5\n"
"	.long	9\n"
"	.long	1\n"
"	.long	3\n"
"	.long	7\n"
"	.long	8\n"
"	.long	4\n"
"	.long	7\n"
"	.long	5\n"
"	.long	2\n"
"	.long	9\n"
"	.long	5\n"
"	.long	3\n"
"	.long	7\n"
"	.long	5\n"
"	.long	7\n"
"	.align 4\n"
"_sol_none:\n"
"	.space 4\n"
"	.align 4\n"
"_pre_none:\n"
"	.space 4\n"
"	.align 32\n"
"_sol_list:\n"
"	.long	_sol_none\n"
"	.long	_sol_none\n"
"	.long	_sol_none\n"
"	.long	_sol_none\n"
"	.long	_sol_none\n"
"	.long	_sol_none\n"
"	.long	_sol_none\n"
"	.long	_sol7\n"
"	.long	_sol8\n"
"	.long	_sol_none\n"
"	.long	_sol_none\n"
"	.long	_sol_none\n"
"	.long	_sol_none\n"
"	.long	_sol_none\n"
"	.long	_sol_none\n"
"	.long	_sol15\n"
"	.long	_sol16\n"
"	.long	_sol_none\n"
"	.long	_sol_none\n"
"	.long	_sol_none\n"
"	.long	_sol_none\n"
"	.align 32\n"
"_pre_list:\n"
"	.long	_pre_none\n"
"	.long	_pre_none\n"
"	.long	_pre_none\n"
"	.long	_pre_none\n"
"	.long	_pre_none\n"
"	.long	_pre_none\n"
"	.long	_pre_none\n"
"	.long	_pre7\n"
"	.long	_pre8\n"
"	.long	_pre_none\n"
"	.long	_pre_none\n"
"	.long	_pre_none\n"
"	.long	_pre_none\n"
"	.long	_pre_none\n"
"	.long	_pre_none\n"
"	.long	_pre15\n"
"	.long	_pre16\n"
"	.long	_pre_none\n"
"	.long	_pre_none\n"
"	.long	_pre_none\n"
"	.long	_pre_none\n"
".lcomm _isdig.3,1024\n"
".lcomm _isdigm.4,1024\n"
".lcomm _tmp.2,256\n"
".lcomm _inbuf.0,1048576\n"
".lcomm _outbuf.1,4194304\n"
);
}
