int main()
{
__asm__ __volatile__(
"	jmp	_main2\n"
"	.p2align 4,,15\n"
"_f:\n"
"	pushl	%ebp\n"
"	movl	%esp, %ebp\n"
"	pushl	%edi\n"
"	pushl	%esi\n"
"	pushl	%ebx\n"
"	subl	$60, %esp\n"
"	movl	8(%ebp), %ebx\n"
"	movl	12(%ebp), %esi\n"
"	movl	$1, -24(%ebp)\n"
"	movl	$0, -20(%ebp)\n"
"	cmpl	$0, %esi\n"
"	ja	L2\n"
"	cmpl	$-2, %ebx\n"
"	jbe	L37\n"
"L2:\n"
"	movl	_p, %edx\n"
"	movl	%edx, %eax\n"
"	imull	%edx, %eax\n"
"	movl	%eax, -48(%ebp)\n"
"	movl	%eax, %ecx\n"
"	sarl	$31, %ecx\n"
"	movl	%ecx, -44(%ebp)\n"
"	cmpl	%esi, -44(%ebp)\n"
"	jae	L41\n"
"L32:\n"
"	movl	%edx, %ecx\n"
"	.p2align 4,,15\n"
"L40:\n"
"	movl	%ecx, -32(%ebp)\n"
"	movl	%ecx, %eax\n"
"	sarl	$31, %eax\n"
"	movl	%eax, -28(%ebp)\n"
"	movl	-32(%ebp), %edx\n"
"	movl	-28(%ebp), %ecx\n"
"	movl	%edx, 8(%esp)\n"
"	movl	%ecx, 12(%esp)\n"
"	movl	%ebx, (%esp)\n"
"	movl	%esi, 4(%esp)\n"
"	call	__umoddi3\n"
"	movl	%edx, %ecx\n"
"	orl	%eax, %ecx\n"
"	jne	L10\n"
"	movl	-32(%ebp), %eax\n"
"	movl	-28(%ebp), %edx\n"
"	movl	%eax, 8(%esp)\n"
"	movl	%edx, 12(%esp)\n"
"	movl	%ebx, (%esp)\n"
"	movl	%esi, 4(%esp)\n"
"	call	__udivdi3\n"
"	movl	%eax, %ebx\n"
"	movl	%edx, %esi\n"
"	movl	$2, %edi\n"
"	movl	-32(%ebp), %edx\n"
"	movl	-28(%ebp), %ecx\n"
"	movl	%edx, -40(%ebp)\n"
"	movl	%ecx, -36(%ebp)\n"
"	.p2align 4,,15\n"
"L11:\n"
"	movl	-40(%ebp), %edx\n"
"	movl	-36(%ebp), %ecx\n"
"	movl	%edx, 8(%esp)\n"
"	movl	%ecx, 12(%esp)\n"
"	movl	%ebx, (%esp)\n"
"	movl	%esi, 4(%esp)\n"
"	call	__umoddi3\n"
"	movl	%edx, %ecx\n"
"	orl	%eax, %ecx\n"
"	jne	L42\n"
"	incl	%edi\n"
"	movl	-40(%ebp), %eax\n"
"	movl	-36(%ebp), %edx\n"
"	movl	%eax, 8(%esp)\n"
"	movl	%edx, 12(%esp)\n"
"	movl	%ebx, (%esp)\n"
"	movl	%esi, 4(%esp)\n"
"	call	__udivdi3\n"
"	movl	%eax, %ebx\n"
"	movl	%edx, %esi\n"
"	jmp	L11\n"
"L42:\n"
"	movl	-24(%ebp), %edx\n"
"	imull	%edx, %edi\n"
"	movl	%edi, -24(%ebp)\n"
"	incl	-20(%ebp)\n"
"	cmpl	$0, %esi\n"
"	ja	L5\n"
"	cmpl	$-2, %ebx\n"
"	jbe	L43\n"
"	.p2align 4,,15\n"
"L5:\n"
"	movl	-20(%ebp), %edx\n"
"	movl	_p(,%edx,4), %ecx\n"
"	movl	%ecx, %eax\n"
"	imull	%ecx, %eax\n"
"	cltd\n"
"	cmpl	%esi, %edx\n"
"	jb	L40\n"
"	ja	L4\n"
"	cmpl	%ebx, %eax\n"
"	jbe	L40\n"
"L4:\n"
"	movl	%ecx, %eax\n"
"	imull	%ecx, %eax\n"
"	cmpl	%ebx, %eax\n"
"	ja	L34\n"
"L30:\n"
"	movl	%ebx, %eax\n"
"	xorl	%edx, %edx\n"
"	divl	%ecx\n"
"	testl	%edx, %edx\n"
"	jne	L22\n"
"	movl	%eax, %ebx\n"
"	movl	$2, %edi\n"
"	xorl	%edx, %edx\n"
"	divl	%ecx\n"
"	testl	%edx, %edx\n"
"	jne	L36\n"
"	.p2align 4,,15\n"
"L29:\n"
"	incl	%edi\n"
"	movl	%ebx, %eax\n"
"	xorl	%edx, %edx\n"
"	divl	%ecx\n"
"	movl	%eax, %ebx\n"
"	xorl	%edx, %edx\n"
"	divl	%ecx\n"
"	testl	%edx, %edx\n"
"	je	L29\n"
"L36:\n"
"	movl	-24(%ebp), %eax\n"
"	imull	%eax, %edi\n"
"	movl	%edi, -24(%ebp)\n"
"L22:\n"
"	incl	-20(%ebp)\n"
"	movl	-20(%ebp), %edx\n"
"	movl	_p(,%edx,4), %eax\n"
"	movl	%eax, %ecx\n"
"	imull	%eax, %eax\n"
"	cmpl	%ebx, %eax\n"
"	jbe	L30\n"
"L34:\n"
"	movl	-24(%ebp), %eax\n"
"	decl	%ebx\n"
"	je	L31\n"
"	addl	%eax, %eax\n"
"L31:\n"
"	addl	$60, %esp\n"
"	popl	%ebx\n"
"	popl	%esi\n"
"	popl	%edi\n"
"	popl	%ebp\n"
"	ret\n"
"L43:\n"
"	movl	-20(%ebp), %eax\n"
"	movl	_p(,%eax,4), %ecx\n"
"	jmp	L4\n"
"	.p2align 4,,7\n"
"L10:\n"
"	incl	-20(%ebp)\n"
"	jmp	L5\n"
"L41:\n"
"	ja	L37\n"
"	movl	%edx, %ecx\n"
"	cmpl	%ebx, -48(%ebp)\n"
"	jbe	L32\n"
"	jmp	L4\n"
"L37:\n"
"	movl	_p, %ecx\n"
"	jmp	L4\n"
"	.p2align 4,,15\n"
"_sieve:\n"
"	pushl	%ebp\n"
"	movl	%esp, %ebp\n"
"	movl	$2, %edx\n"
"L55:\n"
"	cmpb	$0, _s.0(%edx)\n"
"	jne	L47\n"
"	movl	%edx, %eax\n"
"	imull	%edx, %eax\n"
"	cmpl	$1023, %eax\n"
"	jg	L47\n"
"L54:\n"
"	movb	$1, _s.0(%eax)\n"
"	addl	%edx, %eax\n"
"	cmpl	$1023, %eax\n"
"	jle	L54\n"
"L47:\n"
"	incl	%edx\n"
"	cmpl	$31, %edx\n"
"	jle	L55\n"
"	movl	$2, %edx\n"
"	xorl	%eax, %eax\n"
"	.p2align 4,,15\n"
"L61:\n"
"	cmpb	$0, _s.0(%edx)\n"
"	jne	L58\n"
"	movl	%edx, _p(,%eax,4)\n"
"	incl	%eax\n"
"L58:\n"
"	incl	%edx\n"
"	cmpl	$1023, %edx\n"
"	jle	L61\n"
"	popl	%ebp\n"
"	ret\n"
"	.p2align 4,,15\n"
"_main2:\n"
"	pushl	%ebp\n"
"	movl	%esp, %ebp\n"
"	pushl	%edi\n"
"	pushl	%esi\n"
"	pushl	%ebx\n"
"	subl	$60, %esp\n"
"	call	_sieve\n"
"	movl	$48, %edx\n"
"	.p2align 4,,15\n"
"L72:\n"
"	movl	$1, %eax\n"
"	movl	%eax, _d.2(,%edx,4)\n"
"	incl	%edx\n"
"	cmpl	$57, %edx\n"
"	jle	L72\n"
"	movl	$16384, %eax\n"
"	movl	%eax, 8(%esp)\n"
"	movl	$_inbuf.1, -20(%ebp)\n"
"	movl	$_inbuf.1, %edi\n"
"	movl	%edi, 4(%esp)\n"
"	movl	$0, (%esp)\n"
"	call	read\n"
"	movl	$1, -24(%ebp)\n"
"	.p2align 4,,15\n"
"L73:\n"
"	movl	-20(%ebp), %eax\n"
"	movzbl	(%eax), %edx\n"
"	movsbl	%dl,%eax\n"
"	movl	_d.2(,%eax,4), %esi\n"
"	testl	%esi, %esi\n"
"	jne	L107\n"
"	.p2align 4,,15\n"
"L79:\n"
"	incl	-20(%ebp)\n"
"	movl	-20(%ebp), %ecx\n"
"	movzbl	(%ecx), %edx\n"
"	movsbl	%dl,%eax\n"
"	movl	_d.2(,%eax,4), %ebx\n"
"	testl	%ebx, %ebx\n"
"	je	L79\n"
"L107:\n"
"	movsbl	%dl,%eax\n"
"	leal	-48(%eax), %edx\n"
"	incl	-20(%ebp)\n"
"	movl	-20(%ebp), %ecx\n"
"	movsbl	(%ecx),%eax\n"
"	movl	_d.2(,%eax,4), %ecx\n"
"	testl	%ecx, %ecx\n"
"	je	L109\n"
"	movl	%eax, %edi\n"
"	.p2align 4,,15\n"
"L84:\n"
"	leal	(%edx,%edx,4), %eax\n"
"	leal	-48(%edi,%eax,2), %edx\n"
"	incl	-20(%ebp)\n"
"	movl	-20(%ebp), %ecx\n"
"	movsbl	(%ecx),%eax\n"
"	movl	%eax, %edi\n"
"	movl	_d.2(,%eax,4), %eax\n"
"	testl	%eax, %eax\n"
"	jne	L84\n"
"L109:\n"
"	incl	-20(%ebp)\n"
"	testl	%edx, %edx\n"
"	je	L74\n"
"	movl	%edx, -32(%ebp)\n"
"	movl	%edx, %eax\n"
"	sarl	$31, %eax\n"
"	movl	%eax, -28(%ebp)\n"
"	movl	-20(%ebp), %ecx\n"
"	movzbl	(%ecx), %edx\n"
"	movsbl	%dl,%eax\n"
"	movl	_d.2(,%eax,4), %esi\n"
"	testl	%esi, %esi\n"
"	jne	L111\n"
"	.p2align 4,,15\n"
"L89:\n"
"	incl	-20(%ebp)\n"
"	movl	-20(%ebp), %eax\n"
"	movzbl	(%eax), %edx\n"
"	movsbl	%dl,%eax\n"
"	movl	_d.2(,%eax,4), %ebx\n"
"	testl	%ebx, %ebx\n"
"	je	L89\n"
"L111:\n"
"	movsbl	%dl,%eax\n"
"	leal	-48(%eax), %edx\n"
"	incl	-20(%ebp)\n"
"	movl	-20(%ebp), %ecx\n"
"	movsbl	(%ecx),%eax\n"
"	movl	_d.2(,%eax,4), %ecx\n"
"	testl	%ecx, %ecx\n"
"	je	L113\n"
"	movl	%eax, %edi\n"
"	.p2align 4,,15\n"
"L94:\n"
"	leal	(%edx,%edx,4), %eax\n"
"	leal	-48(%edi,%eax,2), %edx\n"
"	incl	-20(%ebp)\n"
"	movl	-20(%ebp), %ecx\n"
"	movsbl	(%ecx),%eax\n"
"	movl	%eax, %edi\n"
"	movl	_d.2(,%eax,4), %eax\n"
"	testl	%eax, %eax\n"
"	jne	L94\n"
"L113:\n"
"	incl	-20(%ebp)\n"
"	movl	%edx, %esi\n"
"	movl	%edx, %edi\n"
"	sarl	$31, %edi\n"
"	movl	-32(%ebp), %eax\n"
"	mull	%edx\n"
"	movl	%eax, -40(%ebp)\n"
"	movl	-32(%ebp), %ebx\n"
"	imull	%edi, %ebx\n"
"	movl	%edx, %eax\n"
"	addl	%ebx, %eax\n"
"	movl	-28(%ebp), %edx\n"
"	imull	%esi, %edx\n"
"	leal	(%edx,%eax), %edx\n"
"	movl	%edx, -36(%ebp)\n"
"	movl	-20(%ebp), %ecx\n"
"	movzbl	(%ecx), %edx\n"
"	movsbl	%dl,%eax\n"
"	movl	_d.2(,%eax,4), %esi\n"
"	testl	%esi, %esi\n"
"	jne	L115\n"
"	.p2align 4,,15\n"
"L98:\n"
"	incl	-20(%ebp)\n"
"	movl	-20(%ebp), %eax\n"
"	movzbl	(%eax), %edx\n"
"	movsbl	%dl,%eax\n"
"	movl	_d.2(,%eax,4), %ebx\n"
"	testl	%ebx, %ebx\n"
"	je	L98\n"
"L115:\n"
"	movsbl	%dl,%eax\n"
"	leal	-48(%eax), %edx\n"
"	incl	-20(%ebp)\n"
"	movl	-20(%ebp), %ecx\n"
"	movsbl	(%ecx),%eax\n"
"	movl	_d.2(,%eax,4), %ecx\n"
"	testl	%ecx, %ecx\n"
"	je	L117\n"
"	movl	%eax, %edi\n"
"	.p2align 4,,15\n"
"L103:\n"
"	leal	(%edx,%edx,4), %eax\n"
"	leal	-48(%edi,%eax,2), %edx\n"
"	incl	-20(%ebp)\n"
"	movl	-20(%ebp), %ecx\n"
"	movsbl	(%ecx),%eax\n"
"	movl	%eax, %edi\n"
"	movl	_d.2(,%eax,4), %eax\n"
"	testl	%eax, %eax\n"
"	jne	L103\n"
"L117:\n"
"	incl	-20(%ebp)\n"
"	imull	%edx, %edx\n"
"	movl	%edx, %ebx\n"
"	movl	%edx, %esi\n"
"	sarl	$31, %esi\n"
"	movl	-40(%ebp), %eax\n"
"	mull	%edx\n"
"	movl	%eax, -48(%ebp)\n"
"	movl	-40(%ebp), %edi\n"
"	imull	%esi, %edi\n"
"	movl	%edx, %ecx\n"
"	addl	%edi, %ecx\n"
"	movl	-36(%ebp), %esi\n"
"	imull	%esi, %ebx\n"
"	leal	(%ebx,%ecx), %ebx\n"
"	movl	%ebx, -44(%ebp)\n"
"	movl	-48(%ebp), %edx\n"
"	movl	-44(%ebp), %ecx\n"
"	movl	%edx, (%esp)\n"
"	movl	%ecx, 4(%esp)\n"
"	call	_f\n"
"	leal	-1(%eax,%eax), %eax\n"
"	movl	%eax, 8(%esp)\n"
"	movl	-24(%ebp), %ecx\n"
"	movl	%ecx, 4(%esp)\n"
"	movl	$LC0, (%esp)\n"
"	call	printf\n"
"	incl	-24(%ebp)\n"
"	jmp	L73\n"
"L74:\n"
"	movl	$0, (%esp)\n"
"	call	exit\n"
".align 32\n"
"LC0:\n"
"	.ascii \"Case %d: %d\\12\\0\"\n"
".align 32\n"
".lcomm _p,1024\n"
".lcomm _s.0,1024\n"
".lcomm _d.2,512\n"
".lcomm _inbuf.1,16384\n"
);
}
