int main()
{
__asm__ __volatile__(
"	pushl	%ebp\n"
"	movl	%esp, %ebp\n"
"	pushl	%edi\n"
"	pushl	%esi\n"
"	pushl	%ebx\n"
"	subl	$76, %esp\n"
"	movl	$48, %ebx\n"
"L31:\n"
"	movl	$1, %edx\n"
"	movl	%edx, _isdig.5(,%ebx,4)\n"
"	incl	%ebx\n"
"	cmpl	$57, %ebx\n"
"	jle	L31\n"
"	movl	$4194304, %edx\n"
"	movl	%edx, 8(%esp)\n"
"	movl	$_inbuf.2, %esi\n"
"	movl	%esi, 4(%esp)\n"
"	movl	$0, (%esp)\n"
"	call	read\n"
"	movl	$_outbuf.3, -20(%ebp)\n"
"	movl	$_adjgot, %edi\n"
"	movl	$65536, %eax\n"
"	xorl	%edx, %edx\n"
"	testl	$4, %edi\n"
"	je	L32\n"
"	xorl	%ecx, %ecx\n"
"	movl	%ecx, _adjgot\n"
"	movl	$_adjgot+4, %edi\n"
"	movl	$65532, %eax\n"
"L32:\n"
"	cld\n"
"	movl	%eax, %ecx\n"
"	shrl	$2, %ecx\n"
"	movl	%edx, %eax\n"
"	rep\n"
"	stosl\n"
"	movl	$_findgot, %edi\n"
"	movl	$512, %eax\n"
"	testl	$4, %edi\n"
"	je	L33\n"
"	xorl	%ebx, %ebx\n"
"	movl	%ebx, _findgot\n"
"	movl	$_findgot+4, %edi\n"
"	movl	$508, %eax\n"
"L33:\n"
"	cld\n"
"	movl	%eax, %ecx\n"
"	shrl	$2, %ecx\n"
"	movl	%edx, %eax\n"
"	rep\n"
"	stosl\n"
"	movl	$1, %edx\n"
"	movl	%edx, _findid\n"
"	movl	$1, %edi\n"
"	movl	%edi, _testno\n"
"L34:\n"
"	movzbl	(%esi), %ecx\n"
"	movsbl	%cl,%edi\n"
"	movl	_isdig.5(,%edi,4), %ebx\n"
"	testl	%ebx, %ebx\n"
"	jne	L141\n"
"	.p2align 4,,15\n"
"L40:\n"
"	incl	%esi\n"
"	movzbl	(%esi), %ecx\n"
"	movsbl	%cl,%ebx\n"
"	movl	_isdig.5(,%ebx,4), %edx\n"
"	testl	%edx, %edx\n"
"	je	L40\n"
"L141:\n"
"	movsbl	%cl,%edx\n"
"	leal	-48(%edx), %ebx\n"
"	incl	%esi\n"
"	movzbl	(%esi), %ecx\n"
"	movsbl	%cl,%eax\n"
"	movl	_isdig.5(,%eax,4), %edi\n"
"	testl	%edi, %edi\n"
"	je	L143\n"
"	movl	%eax, %edx\n"
"	.p2align 4,,15\n"
"L45:\n"
"	leal	(%ebx,%ebx,4), %ecx\n"
"	leal	-48(%edx,%ecx,2), %ebx\n"
"	incl	%esi\n"
"	movzbl	(%esi), %ecx\n"
"	movsbl	%cl,%edi\n"
"	movl	%edi, %edx\n"
"	movl	_isdig.5(,%edi,4), %edi\n"
"	testl	%edi, %edi\n"
"	jne	L45\n"
"L143:\n"
"	movl	%ebx, _n\n"
"	testl	%ebx, %ebx\n"
"	je	L35\n"
"	movsbl	%cl,%edx\n"
"	movl	_isdig.5(,%edx,4), %ebx\n"
"	testl	%ebx, %ebx\n"
"	jne	L145\n"
"	.p2align 4,,15\n"
"L50:\n"
"	incl	%esi\n"
"	movzbl	(%esi), %ecx\n"
"	movsbl	%cl,%ebx\n"
"	movl	_isdig.5(,%ebx,4), %edi\n"
"	testl	%edi, %edi\n"
"	je	L50\n"
"L145:\n"
"	movsbl	%cl,%edx\n"
"	leal	-48(%edx), %ebx\n"
"	incl	%esi\n"
"	movzbl	(%esi), %ecx\n"
"	movsbl	%cl,%eax\n"
"	movl	_isdig.5(,%eax,4), %edi\n"
"	testl	%edi, %edi\n"
"	je	L147\n"
"	movl	%eax, %edx\n"
"	.p2align 4,,15\n"
"L55:\n"
"	leal	(%ebx,%ebx,4), %ecx\n"
"	leal	-48(%edx,%ecx,2), %ebx\n"
"	incl	%esi\n"
"	movzbl	(%esi), %ecx\n"
"	movsbl	%cl,%edi\n"
"	movl	%edi, %edx\n"
"	movl	_isdig.5(,%edi,4), %edi\n"
"	testl	%edi, %edi\n"
"	jne	L55\n"
"L147:\n"
"	movl	%ebx, _source\n"
"	movsbl	%cl,%edx\n"
"	movl	_isdig.5(,%edx,4), %ebx\n"
"	testl	%ebx, %ebx\n"
"	jne	L149\n"
"	.p2align 4,,15\n"
"L59:\n"
"	incl	%esi\n"
"	movzbl	(%esi), %ecx\n"
"	movsbl	%cl,%ebx\n"
"	movl	_isdig.5(,%ebx,4), %edi\n"
"	testl	%edi, %edi\n"
"	je	L59\n"
"L149:\n"
"	movsbl	%cl,%edx\n"
"	leal	-48(%edx), %ebx\n"
"	incl	%esi\n"
"	movzbl	(%esi), %ecx\n"
"	movsbl	%cl,%eax\n"
"	movl	_isdig.5(,%eax,4), %edi\n"
"	testl	%edi, %edi\n"
"	je	L151\n"
"	movl	%eax, %edx\n"
"	.p2align 4,,15\n"
"L64:\n"
"	leal	(%ebx,%ebx,4), %ecx\n"
"	leal	-48(%edx,%ecx,2), %ebx\n"
"	incl	%esi\n"
"	movzbl	(%esi), %ecx\n"
"	movsbl	%cl,%edi\n"
"	movl	%edi, %edx\n"
"	movl	_isdig.5(,%edi,4), %edi\n"
"	testl	%edi, %edi\n"
"	jne	L64\n"
"L151:\n"
"	movl	%ebx, _sink\n"
"	movsbl	%cl,%edx\n"
"	movl	_isdig.5(,%edx,4), %ebx\n"
"	testl	%ebx, %ebx\n"
"	jne	L153\n"
"	.p2align 4,,15\n"
"L68:\n"
"	incl	%esi\n"
"	movzbl	(%esi), %ecx\n"
"	movsbl	%cl,%ebx\n"
"	movl	_isdig.5(,%ebx,4), %edi\n"
"	testl	%edi, %edi\n"
"	je	L68\n"
"L153:\n"
"	movsbl	%cl,%edx\n"
"	leal	-48(%edx), %ebx\n"
"	incl	%esi\n"
"	movzbl	(%esi), %ecx\n"
"	movsbl	%cl,%eax\n"
"	movl	_isdig.5(,%eax,4), %edi\n"
"	testl	%edi, %edi\n"
"	je	L155\n"
"	movl	%eax, %edx\n"
"	.p2align 4,,15\n"
"L73:\n"
"	leal	(%ebx,%ebx,4), %ecx\n"
"	leal	-48(%edx,%ecx,2), %ebx\n"
"	incl	%esi\n"
"	movzbl	(%esi), %ecx\n"
"	movsbl	%cl,%edi\n"
"	movl	%edi, %edx\n"
"	movl	_isdig.5(,%edi,4), %eax\n"
"	testl	%eax, %eax\n"
"	jne	L73\n"
"L155:\n"
"	movl	%ebx, _m.6\n"
"	xorl	%ebx, %ebx\n"
"	movl	_n, %eax\n"
"	cmpl	%eax, %ebx\n"
"	jg	L157\n"
"	.p2align 4,,15\n"
"L78:\n"
"	xorl	%edi, %edi\n"
"	movl	%edi, _adj(,%ebx,4)\n"
"	incl	%ebx\n"
"	cmpl	%eax, %ebx\n"
"	jle	L78\n"
"L157:\n"
"	movl	_m.6, %ebx\n"
"	leal	-1(%ebx), %edx\n"
"	movl	%edx, -28(%ebp)\n"
"	movl	%edx, _m.6\n"
"	testl	%ebx, %ebx\n"
"	jle	L159\n"
"	movl	_testno, %eax\n"
"	movl	%eax, -44(%ebp)\n"
"	movl	_adjcnt, %edi\n"
"	movl	%edi, -48(%ebp)\n"
"	movl	%edx, -52(%ebp)\n"
"	.p2align 4,,15\n"
"L112:\n"
"	movsbl	%cl,%ebx\n"
"	movl	_isdig.5(,%ebx,4), %edx\n"
"	testl	%edx, %edx\n"
"	jne	L161\n"
"	.p2align 4,,15\n"
"L85:\n"
"	incl	%esi\n"
"	movzbl	(%esi), %ecx\n"
"	movsbl	%cl,%edx\n"
"	movl	_isdig.5(,%edx,4), %edi\n"
"	testl	%edi, %edi\n"
"	je	L85\n"
"L161:\n"
"	movsbl	%cl,%edx\n"
"	leal	-48(%edx), %ebx\n"
"	incl	%esi\n"
"	movzbl	(%esi), %ecx\n"
"	movsbl	%cl,%eax\n"
"	movl	_isdig.5(,%eax,4), %edi\n"
"	testl	%edi, %edi\n"
"	je	L163\n"
"	movl	%eax, %edx\n"
"	.p2align 4,,15\n"
"L90:\n"
"	leal	(%ebx,%ebx,4), %ecx\n"
"	leal	-48(%edx,%ecx,2), %ebx\n"
"	incl	%esi\n"
"	movzbl	(%esi), %ecx\n"
"	movsbl	%cl,%edi\n"
"	movl	%edi, %edx\n"
"	movl	_isdig.5(,%edi,4), %edi\n"
"	testl	%edi, %edi\n"
"	jne	L90\n"
"L163:\n"
"	movl	%ebx, -32(%ebp)\n"
"	movsbl	%cl,%edx\n"
"	movl	_isdig.5(,%edx,4), %ebx\n"
"	testl	%ebx, %ebx\n"
"	jne	L165\n"
"	.p2align 4,,15\n"
"L94:\n"
"	incl	%esi\n"
"	movzbl	(%esi), %ecx\n"
"	movsbl	%cl,%ebx\n"
"	movl	_isdig.5(,%ebx,4), %edi\n"
"	testl	%edi, %edi\n"
"	je	L94\n"
"L165:\n"
"	movsbl	%cl,%edx\n"
"	leal	-48(%edx), %ebx\n"
"	incl	%esi\n"
"	movzbl	(%esi), %ecx\n"
"	movsbl	%cl,%eax\n"
"	movl	_isdig.5(,%eax,4), %edi\n"
"	testl	%edi, %edi\n"
"	je	L167\n"
"	movl	%eax, %edx\n"
"	.p2align 4,,15\n"
"L99:\n"
"	leal	(%ebx,%ebx,4), %ecx\n"
"	leal	-48(%edx,%ecx,2), %ebx\n"
"	incl	%esi\n"
"	movzbl	(%esi), %ecx\n"
"	movsbl	%cl,%edi\n"
"	movl	%edi, %edx\n"
"	movl	_isdig.5(,%edi,4), %edi\n"
"	testl	%edi, %edi\n"
"	jne	L99\n"
"L167:\n"
"	movl	%ebx, -36(%ebp)\n"
"	movsbl	%cl,%edx\n"
"	movl	_isdig.5(,%edx,4), %ebx\n"
"	testl	%ebx, %ebx\n"
"	jne	L169\n"
"	.p2align 4,,15\n"
"L103:\n"
"	incl	%esi\n"
"	movzbl	(%esi), %ecx\n"
"	movsbl	%cl,%ebx\n"
"	movl	_isdig.5(,%ebx,4), %edi\n"
"	testl	%edi, %edi\n"
"	je	L103\n"
"L169:\n"
"	movsbl	%cl,%edi\n"
"	leal	-48(%edi), %ebx\n"
"	incl	%esi\n"
"	movzbl	(%esi), %edx\n"
"	movb	%dl, %cl\n"
"	movsbl	%dl,%eax\n"
"	movl	_isdig.5(,%eax,4), %edi\n"
"	testl	%edi, %edi\n"
"	je	L171\n"
"	movl	%eax, %edx\n"
"	.p2align 4,,15\n"
"L108:\n"
"	leal	(%ebx,%ebx,4), %ecx\n"
"	leal	-48(%edx,%ecx,2), %ebx\n"
"	incl	%esi\n"
"	movzbl	(%esi), %edx\n"
"	movb	%dl, %cl\n"
"	movsbl	%dl,%edi\n"
"	movl	%edi, %edx\n"
"	movl	_isdig.5(,%edi,4), %edi\n"
"	testl	%edi, %edi\n"
"	jne	L108\n"
"L171:\n"
"	movl	%ebx, %edi\n"
"	movl	%ebx, -40(%ebp)\n"
"	movl	-36(%ebp), %edx\n"
"	cmpl	%edx, -32(%ebp)\n"
"	je	L79\n"
"	movl	-32(%ebp), %ebx\n"
"	sall	$7, %ebx\n"
"	leal	(%edx,%ebx), %edx\n"
"	movl	-44(%ebp), %ebx\n"
"	cmpl	%ebx, _adjgot(,%edx,4)\n"
"	je	L110\n"
"	movl	-36(%ebp), %eax\n"
"	sall	$7, %eax\n"
"	addl	-32(%ebp), %eax\n"
"	movl	%ebx, _adjgot(,%eax,4)\n"
"	movl	%ebx, _adjgot(,%edx,4)\n"
"	movl	-48(%ebp), %ebx\n"
"	incl	%ebx\n"
"	movl	%ebx, _adjid(,%edx,4)\n"
"	addl	$2, -48(%ebp)\n"
"	movl	-48(%ebp), %edx\n"
"	movl	%edx, _adjid(,%eax,4)\n"
"	movl	%edi, _cap(,%edx,4)\n"
"	movl	%edi, _cap(,%ebx,4)\n"
"	movl	-36(%ebp), %edi\n"
"	movl	%edi, _ref(,%ebx,4)\n"
"	movl	%edx, _back(,%ebx,4)\n"
"	movl	-32(%ebp), %edx\n"
"	movl	_adj(,%edx,4), %edi\n"
"	movl	%edi, _next(,%ebx,4)\n"
"	movl	%ebx, _adj(,%edx,4)\n"
"	movl	-48(%ebp), %edi\n"
"	movl	%edx, _ref(,%edi,4)\n"
"	movl	%ebx, _back(,%edi,4)\n"
"	movl	-36(%ebp), %edi\n"
"	movl	_adj(,%edi,4), %ebx\n"
"	movl	-48(%ebp), %edx\n"
"	movl	%ebx, _next(,%edx,4)\n"
"	movl	%edx, _adj(,%edi,4)\n"
"L79:\n"
"	movl	-28(%ebp), %edi\n"
"	movl	-52(%ebp), %eax\n"
"	decl	%eax\n"
"	movl	%eax, -28(%ebp)\n"
"	movl	%eax, -52(%ebp)\n"
"	testl	%edi, %edi\n"
"	jg	L112\n"
"	movl	%eax, _m.6\n"
"	movl	-48(%ebp), %edx\n"
"	movl	%edx, _adjcnt\n"
"	movl	-40(%ebp), %ebx\n"
"	movl	%ebx, _z.9\n"
"	movl	-36(%ebp), %eax\n"
"	movl	%eax, _y.8\n"
"	movl	-32(%ebp), %ecx\n"
"	movl	%ecx, _x.7\n"
"L159:\n"
"	xorl	%edi, %edi\n"
"	movl	%edi, _z.9\n"
"	.p2align 4,,15\n"
"L113:\n"
"	call	_find\n"
"	movl	%eax, %ebx\n"
"	testl	%eax, %eax\n"
"	jle	L181\n"
"	addl	%ebx, _z.9\n"
"	jmp	L113\n"
"L181:\n"
"	movl	-20(%ebp), %ecx\n"
"	movb	$78, (%ecx)\n"
"	incl	%ecx\n"
"	movb	$101, (%ecx)\n"
"	incl	%ecx\n"
"	movb	$116, (%ecx)\n"
"	incl	%ecx\n"
"	movb	$119, (%ecx)\n"
"	incl	%ecx\n"
"	movb	$111, (%ecx)\n"
"	incl	%ecx\n"
"	movb	$114, (%ecx)\n"
"	incl	%ecx\n"
"	movb	$107, (%ecx)\n"
"	incl	%ecx\n"
"	movb	$32, (%ecx)\n"
"	incl	%ecx\n"
"	movl	%ecx, -20(%ebp)\n"
"	movl	_testno, %ebx\n"
"	movl	%ebx, -24(%ebp)\n"
"	movl	$_tmp.4, %ecx\n"
"	testl	%ebx, %ebx\n"
"	jle	L173\n"
"	movl	$1717986919, %edi\n"
"	.p2align 4,,15\n"
"L122:\n"
"	movl	%ebx, %eax\n"
"	imull	%edi\n"
"	movl	%eax, -64(%ebp)\n"
"	movl	%edx, -60(%ebp)\n"
"	movl	-60(%ebp), %edx\n"
"	sarl	$2, %edx\n"
"	movl	%ebx, %eax\n"
"	sarl	$31, %eax\n"
"	subl	%eax, %edx\n"
"	leal	(%edx,%edx,4), %eax\n"
"	addl	%eax, %eax\n"
"	subl	%eax, %ebx\n"
"	movb	%bl, %al\n"
"	addb	$48, %al\n"
"	movb	%al, (%ecx)\n"
"	incl	%ecx\n"
"	movl	%edx, %ebx\n"
"	testl	%edx, %edx\n"
"	jg	L122\n"
"L173:\n"
"	decl	%ecx\n"
"	cmpl	$_tmp.4-1, %ecx\n"
"	jbe	L175\n"
"	.p2align 4,,15\n"
"L126:\n"
"	movzbl	(%ecx), %edx\n"
"	movl	-20(%ebp), %ebx\n"
"	movb	%dl, (%ebx)\n"
"	incl	%ebx\n"
"	movl	%ebx, -20(%ebp)\n"
"	decl	%ecx\n"
"	cmpl	$_tmp.4-1, %ecx\n"
"	ja	L126\n"
"L175:\n"
"	movl	-20(%ebp), %ebx\n"
"	movb	$10, (%ebx)\n"
"	incl	%ebx\n"
"	movb	$84, (%ebx)\n"
"	incl	%ebx\n"
"	movb	$104, (%ebx)\n"
"	incl	%ebx\n"
"	movb	$101, (%ebx)\n"
"	incl	%ebx\n"
"	movb	$32, (%ebx)\n"
"	incl	%ebx\n"
"	movb	$98, (%ebx)\n"
"	incl	%ebx\n"
"	movb	$97, (%ebx)\n"
"	incl	%ebx\n"
"	movb	$110, (%ebx)\n"
"	incl	%ebx\n"
"	movb	$100, (%ebx)\n"
"	incl	%ebx\n"
"	movb	$119, (%ebx)\n"
"	incl	%ebx\n"
"	movb	$105, (%ebx)\n"
"	incl	%ebx\n"
"	movb	$100, (%ebx)\n"
"	incl	%ebx\n"
"	movb	$116, (%ebx)\n"
"	incl	%ebx\n"
"	movb	$104, (%ebx)\n"
"	incl	%ebx\n"
"	movb	$32, (%ebx)\n"
"	incl	%ebx\n"
"	movb	$105, (%ebx)\n"
"	incl	%ebx\n"
"	movb	$115, (%ebx)\n"
"	incl	%ebx\n"
"	movb	$32, (%ebx)\n"
"	incl	%ebx\n"
"	movl	%ebx, -20(%ebp)\n"
"	movl	_z.9, %edi\n"
"	testl	%edi, %edi\n"
"	jne	L127\n"
"	movb	$48, (%ebx)\n"
"	incl	%ebx\n"
"	movl	%ebx, -20(%ebp)\n"
"L128:\n"
"	movl	-20(%ebp), %eax\n"
"	movb	$46, (%eax)\n"
"	incl	%eax\n"
"	movb	$10, (%eax)\n"
"	incl	%eax\n"
"	movb	$10, (%eax)\n"
"	incl	%eax\n"
"	movl	%eax, -20(%ebp)\n"
"	movl	-24(%ebp), %ecx\n"
"	incl	%ecx\n"
"	movl	%ecx, _testno\n"
"	jmp	L34\n"
"L127:\n"
"	movl	$_tmp.4, %ecx\n"
"	jle	L177\n"
"	movl	$1717986919, %ebx\n"
"L133:\n"
"	movl	%edi, %eax\n"
"	imull	%ebx\n"
"	sarl	$2, %edx\n"
"	movl	%edi, %eax\n"
"	sarl	$31, %eax\n"
"	subl	%eax, %edx\n"
"	leal	(%edx,%edx,4), %eax\n"
"	addl	%eax, %eax\n"
"	subl	%eax, %edi\n"
"	movl	%edi, %eax\n"
"	addb	$48, %al\n"
"	movb	%al, (%ecx)\n"
"	incl	%ecx\n"
"	movl	%edx, %edi\n"
"	testl	%edx, %edx\n"
"	jg	L133\n"
"	movl	%edx, _z.9\n"
"L177:\n"
"	decl	%ecx\n"
"	cmpl	$_tmp.4-1, %ecx\n"
"	jbe	L128\n"
"L137:\n"
"	movzbl	(%ecx), %ebx\n"
"	movl	-20(%ebp), %edi\n"
"	movb	%bl, (%edi)\n"
"	incl	%edi\n"
"	movl	%edi, -20(%ebp)\n"
"	decl	%ecx\n"
"	cmpl	$_tmp.4-1, %ecx\n"
"	ja	L137\n"
"	jmp	L128\n"
"L110:\n"
"	movl	_adjid(,%edx,4), %ebx\n"
"	addl	%edi, _cap(,%ebx,4)\n"
"	movl	-36(%ebp), %eax\n"
"	sall	$7, %eax\n"
"	movl	-32(%ebp), %edx\n"
"	addl	%edx, %eax\n"
"	movl	_adjid(,%eax,4), %edx\n"
"	addl	%edi, _cap(,%edx,4)\n"
"	jmp	L79\n"
"L35:\n"
"	subl	$_outbuf.3, -20(%ebp)\n"
"	movl	-20(%ebp), %edx\n"
"	movl	%edx, 8(%esp)\n"
"	movl	$_outbuf.3, %esi\n"
"	movl	%esi, 4(%esp)\n"
"	movl	$1, (%esp)\n"
"	call	write\n"
"	movl	$0, (%esp)\n"
"	call	exit\n"
"	.p2align 4,,15\n"
"_find:\n"
"	pushl	%ebp\n"
"	movl	%esp, %ebp\n"
"	pushl	%edi\n"
"	pushl	%esi\n"
"	pushl	%ebx\n"
"	subl	$4, %esp\n"
"	movl	_findid, %ecx\n"
"	incl	%ecx\n"
"	movl	%ecx, _findid\n"
"	movl	_source, %edx\n"
"	movl	%edx, -16(%ebp)\n"
"	movl	%edx, _q.1\n"
"	movl	%ecx, _findgot(,%edx,4)\n"
"	xorl	%esi, %esi\n"
"	movl	$1, %ebx\n"
"	movl	_sink, %edi\n"
"	cmpl	%ecx, _findgot(,%edi,4)\n"
"	je	L14\n"
"	.p2align 4,,15\n"
"L13:\n"
"	movl	_q.1(,%esi,4), %eax\n"
"	incl	%esi\n"
"	movl	_adj(,%eax,4), %edx\n"
"	testl	%edx, %edx\n"
"	je	L192\n"
"	.p2align 4,,15\n"
"L12:\n"
"	movl	_cap(,%edx,4), %eax\n"
"	testl	%eax, %eax\n"
"	jle	L9\n"
"	movl	_ref(,%edx,4), %eax\n"
"	cmpl	%ecx, _findgot(,%eax,4)\n"
"	je	L9\n"
"	movl	%eax, _q.1(,%ebx,4)\n"
"	movl	%edx, _p.0(,%eax,4)\n"
"	incl	%ebx\n"
"	movl	%ecx, _findgot(,%eax,4)\n"
"L9:\n"
"	movl	_next(,%edx,4), %edx\n"
"	testl	%edx, %edx\n"
"	jne	L12\n"
"L192:\n"
"	cmpl	%ebx, %esi\n"
"	jge	L3\n"
"	cmpl	%ecx, _findgot(,%edi,4)\n"
"	jne	L13\n"
"L14:\n"
"	movl	%edi, %edx\n"
"	movl	$2147483647, %ebx\n"
"	cmpl	-16(%ebp), %edi\n"
"	je	L196\n"
"L20:\n"
"	movl	_p.0(,%edx,4), %edx\n"
"	movl	_cap(,%edx,4), %eax\n"
"	cmpl	%ebx, %eax\n"
"	jge	L17\n"
"	movl	%eax, %ebx\n"
"L17:\n"
"	movl	_back(,%edx,4), %ecx\n"
"	movl	_ref(,%ecx,4), %edx\n"
"	cmpl	-16(%ebp), %edx\n"
"	jne	L20\n"
"	movl	%edi, %edx\n"
"	cmpl	-16(%ebp), %edi\n"
"	je	L196\n"
"L25:\n"
"	movl	_p.0(,%edx,4), %edi\n"
"	subl	%ebx, _cap(,%edi,4)\n"
"	movl	_back(,%edi,4), %esi\n"
"	addl	%ebx, _cap(,%esi,4)\n"
"	movl	_ref(,%esi,4), %edx\n"
"	cmpl	-16(%ebp), %edx\n"
"	jne	L25\n"
"L196:\n"
"	movl	%ebx, %eax\n"
"L1:\n"
"	popl	%edx\n"
"	popl	%ebx\n"
"	popl	%esi\n"
"	popl	%edi\n"
"	popl	%ebp\n"
"	ret\n"
"L3:\n"
"	cmpl	%ecx, _findgot(,%edi,4)\n"
"	je	L14\n"
"	xorl	%eax, %eax\n"
"	jmp	L1\n"
".lcomm _p.0,4096\n"
".lcomm _q.1,4096\n"
".lcomm _m.6,16\n"
".lcomm _x.7,16\n"
".lcomm _y.8,16\n"
".lcomm _z.9,16\n"
".lcomm _adj,512\n"
".lcomm _n,16\n"
".lcomm _adjcnt,16\n"
".lcomm _source,16\n"
".lcomm _sink,16\n"
".lcomm _testno,16\n"
".lcomm _findid,16\n"
".lcomm _findgot,512\n"
".lcomm _adjid,65536\n"
".lcomm _adjgot,65536\n"
".lcomm _cap,524288\n"
".lcomm _back,524288\n"
".lcomm _ref,524288\n"
".lcomm _next,524288\n"
".lcomm _isdig.5,1024\n"
".lcomm _inbuf.2,4194304\n"
".lcomm _tmp.4,256\n"
".lcomm _outbuf.3,1048576\n"
);
}
