char inbuf[1048576];
int isdig[256], seq[65536], primes[65536], ntests, n;
unsigned sieve[8192];

void main2()
{
__asm__ __volatile(
"       jmp main2_real\n"
"	.type	make_sieve,@function\n"
"make_sieve:\n"
"	pushl	%ebp\n"
"	movl	%esp, %ebp\n"
"	movl	$3, %eax\n"
"	pushl	%edi\n"
"	pushl	%esi\n"
"	pushl	%ebx\n"
"	movl	$2, %ebx\n"
"	movl	%eax, sieve\n"
"	.p2align 4,,15\n"
".L12:\n"
"	movl	%ebx, %eax\n"
"	sarl	$5, %eax\n"
"	movl	sieve(,%eax,4), %eax\n"
"	movl	%ebx, %ecx\n"
"	andl	$31, %ecx\n"
"	shrl	%cl, %eax\n"
"	andl	$1, %eax\n"
"	jne	.L4\n"
"	movl	%ebx, %edx\n"
"	imull	%ebx, %edx\n"
"	cmpl	$65535, %edx\n"
"	jg	.L4\n"
"	movl	$sieve, %esi\n"
"	.p2align 4,,15\n"
".L11:\n"
"	movl	%edx, %ecx\n"
"	movl	%edx, %eax\n"
"	andl	$31, %ecx\n"
"	movl	$1, %edi\n"
"	sarl	$5, %eax\n"
"	sall	%cl, %edi\n"
"	orl	%edi, (%esi,%eax,4)\n"
"	addl	%ebx, %edx\n"
"	cmpl	$65535, %edx\n"
"	jle	.L11\n"
".L4:\n"
"	incl	%ebx\n"
"	cmpl	$255, %ebx\n"
"	jle	.L12\n"
"	xorl	%edx, %edx\n"
"	xorl	%ebx, %ebx\n"
"	movl	$sieve, %esi\n"
"	movl	$primes, %edi\n"
".L13:\n"
"	movl	%ebx, %eax\n"
"	sarl	$5, %eax\n"
"	movl	(%esi,%eax,4), %eax\n"
"	movl	%ebx, %ecx\n"
"	andl	$31, %ecx\n"
"	shrl	%cl, %eax\n"
"	andl	$1, %eax\n"
"	jne	.L15\n"
"	movl	%ebx, (%edi,%edx,4)\n"
"	incl	%edx\n"
"	cmpl	$450, %edx\n"
"	jg	.L1\n"
".L15:\n"
"	incl	%ebx\n"
"	jmp	.L13\n"
".L1:\n"
"	popl	%ebx\n"
"	popl	%esi\n"
"	popl	%edi\n"
"	popl	%ebp\n"
"	ret\n"
".Lendfn1:\n"
"	.size	make_sieve,.Lendfn1-make_sieve\n"
"	.section	.rodata.str1.1,\"aMS\",@progbits,1\n"
".LC2:\n"
"	.string	\"This sequence is anti-primed.\"\n"
"	.section	.rodata.str1.32,\"aMS\",@progbits,1\n"
"	.align 32\n"
".LC0:\n"
"	.string	\"Shortest primed subsequence is length %d:\"\n"
"	.section	.rodata.str1.1\n"
".LC1:\n"
"	.string	\" %d\"\n"
"	.text\n"
"	.p2align 4,,15\n"
"	.type	solve,@function\n"
"solve:\n"
"	pushl	%ebp\n"
"	movl	%esp, %ebp\n"
"	pushl	%edi\n"
"	pushl	%esi\n"
"	pushl	%ebx\n"
"	subl	$28, %esp\n"
"	movl	$2, -16(%ebp)\n"
"	movl	seq+4, %eax\n"
"	movl	%eax, -20(%ebp)\n"
"	movl	n, %eax\n"
"	cmpl	%eax, -16(%ebp)\n"
"	movl	%eax, -24(%ebp)\n"
"	jg	.L47\n"
".L45:\n"
"	movl	-16(%ebp), %esi\n"
"	movl	-20(%ebp), %ebx\n"
"	cmpl	%eax, %esi\n"
"	jg	.L49\n"
"	.p2align 4,,15\n"
".L44:\n"
"	movl	-16(%ebp), %edi\n"
"	movl	%esi, %edx\n"
"	movl	seq(,%esi,4), %eax\n"
"	subl	%edi, %edx\n"
"	movl	seq(,%edx,4), %ecx\n"
"	subl	%ecx, %eax\n"
"	addl	%eax, %ebx\n"
"	cmpl	$65535, %ebx\n"
"	jg	.L31\n"
"	movl	%ebx, %eax\n"
"	sarl	$5, %eax\n"
"	movl	sieve(,%eax,4), %eax\n"
"	movl	%ebx, %ecx\n"
"	andl	$31, %ecx\n"
"	shrl	%cl, %eax\n"
"	andl	$1, %eax\n"
"	xorl	$1, %eax\n"
".L32:\n"
"	testl	%eax, %eax\n"
"	jne	.L55\n"
"	incl	%esi\n"
"	cmpl	-24(%ebp), %esi\n"
"	jle	.L44\n"
".L49:\n"
"	movl	-16(%ebp), %eax\n"
"	incl	-16(%ebp)\n"
"	movl	seq(,%eax,4), %eax\n"
"	addl	%eax, -20(%ebp)\n"
"	movl	-24(%ebp), %eax\n"
"	cmpl	%eax, -16(%ebp)\n"
"	jle	.L45\n"
".L47:\n"
"	movl	$.LC2, (%esp)\n"
"	call	puts\n"
".L21:\n"
"	addl	$28, %esp\n"
"	popl	%ebx\n"
"	popl	%esi\n"
"	popl	%edi\n"
"	popl	%ebp\n"
"	ret\n"
".L55:\n"
"	movl	$.LC0, (%esp)\n"
"	movl	-16(%ebp), %eax\n"
"	movl	%eax, 4(%esp)\n"
"	call	printf\n"
"	movl	-16(%ebp), %edx\n"
"	movl	%esi, %eax\n"
"	subl	%edx, %eax\n"
"	leal	1(%eax), %esi\n"
"	movl	-16(%ebp), %eax\n"
"	decl	-16(%ebp)\n"
"	testl	%eax, %eax\n"
"	jle	.L53\n"
"	.p2align 4,,15\n"
".L43:\n"
"	movl	$.LC1, (%esp)\n"
"	movl	seq(,%esi,4), %eax\n"
"	incl	%esi\n"
"	movl	%eax, 4(%esp)\n"
"	call	printf\n"
"	movl	-16(%ebp), %eax\n"
"	decl	-16(%ebp)\n"
"	testl	%eax, %eax\n"
"	jg	.L43\n"
".L53:\n"
"	movl	$10, (%esp)\n"
"	call	putchar\n"
"	jmp	.L21\n"
"	.p2align 4,,7\n"
".L31:\n"
"	xorl	%ecx, %ecx\n"
"	cmpl	%ebx, %ecx\n"
"	jg	.L51\n"
"	movl	$primes, %edi\n"
"	.p2align 4,,15\n"
".L38:\n"
"	movl	%ebx, %eax\n"
"	cltd\n"
"	idivl	(%edi,%ecx,4)\n"
"	testl	%edx, %edx\n"
"	je	.L54\n"
"	incl	%ecx\n"
"	movl	%ecx, %eax\n"
"	imull	%ecx, %eax\n"
"	cmpl	%ebx, %eax\n"
"	jle	.L38\n"
".L51:\n"
"	movl	$1, %eax\n"
"	jmp	.L32\n"
".L54:\n"
"	xorl	%eax, %eax\n"
"	jmp	.L32\n"
".Lendfn2:\n"
"	.size	solve,.Lendfn2-solve\n"
"	.p2align 4,,15\n"
"main2_real:\n"
"	pushl	%ebp\n"
"	movl	%esp, %ebp\n"
"	pushl	%edi\n"
"	pushl	%esi\n"
"	pushl	%ebx\n"
"	subl	$28, %esp\n"
"	call	make_sieve\n"
"	movl	$isdig, (%esp)\n"
"	movl	$1024, 8(%esp)\n"
"	movl	$0, 4(%esp)\n"
/*"	call	memset\n"*/
"	movl	$isdig, %eax\n"
"	movl	$48, -16(%ebp)\n"
".L61:\n"
"	movl	-16(%ebp), %edx\n"
"	movl	$1, (%eax,%edx,4)\n"
"	incl	%edx\n"
"	cmpl	$57, %edx\n"
"	movl	%edx, -16(%ebp)\n"
"	jle	.L61\n"
"	movl	$1048576, 8(%esp)\n"
"	movl	$inbuf, %esi\n"
"	movl	%esi, 4(%esp)\n"
"	movl	$0, (%esp)\n"
"	call	read\n"
"	movb	$0, inbuf(%eax)\n"
"	movsbl	inbuf,%eax\n"
"	movl	isdig(,%eax,4), %eax\n"
"	testl	%eax, %eax\n"
"	jne	.L116\n"
"	movl	$isdig, %edx\n"
".L65:\n"
"	incl	%esi\n"
"	movzbl	(%esi), %ebx\n"
"	movsbl	%bl,%eax\n"
"	movl	(%edx,%eax,4), %eax\n"
"	testl	%eax, %eax\n"
"	je	.L65\n"
".L101:\n"
"	incl	%esi\n"
"	movsbl	%bl,%eax\n"
"	movzbl	(%esi), %ebx\n"
"	leal	-48(%eax), %edx\n"
"	movl	%edx, ntests\n"
"	movsbl	%bl,%eax\n"
"	movl	isdig(,%eax,4), %eax\n"
"	movb	%bl, %cl\n"
"	testl	%eax, %eax\n"
"	je	.L117\n"
"	movl	$isdig, %edi\n"
".L70:\n"
"	incl	%esi\n"
"	leal	(%edx,%edx,4), %eax\n"
"	movsbl	%cl,%edx\n"
"	movzbl	(%esi), %ebx\n"
"	leal	-48(%edx,%eax,2), %edx\n"
"	movl	%edx, ntests\n"
"	movsbl	%bl,%eax\n"
"	movl	(%edi,%eax,4), %eax\n"
"	movb	%bl, %cl\n"
"	testl	%eax, %eax\n"
"	jne	.L70\n"
".L103:\n"
"	movl	%edx, %eax\n"
"	decl	%edx\n"
"	testl	%eax, %eax\n"
"	movl	%edx, ntests\n"
"	jle	.L105\n"
".L97:\n"
"	movsbl	%bl,%eax\n"
"	movl	isdig(,%eax,4), %eax\n"
"	testl	%eax, %eax\n"
"	jne	.L107\n"
"	movl	$isdig, %edx\n"
"	.p2align 4,,15\n"
".L77:\n"
"	incl	%esi\n"
"	movzbl	(%esi), %ebx\n"
"	movsbl	%bl,%eax\n"
"	movl	(%edx,%eax,4), %edi\n"
"	testl	%edi, %edi\n"
"	je	.L77\n"
".L107:\n"
"	incl	%esi\n"
"	movsbl	%bl,%eax\n"
"	movzbl	(%esi), %ebx\n"
"	subl	$48, %eax\n"
"	movl	%eax, -20(%ebp)\n"
"	movl	%eax, n\n"
"	movsbl	%bl,%eax\n"
"	movl	isdig(,%eax,4), %ecx\n"
"	movb	%bl, %dl\n"
"	testl	%ecx, %ecx\n"
"	je	.L118\n"
"	movl	$isdig, %ecx\n"
"	.p2align 4,,15\n"
".L82:\n"
"	movl	-20(%ebp), %ebx\n"
"	incl	%esi\n"
"	movsbl	%dl,%edx\n"
"	leal	(%ebx,%ebx,4), %eax\n"
"	movzbl	(%esi), %ebx\n"
"	leal	-48(%edx,%eax,2), %eax\n"
"	movl	%eax, -20(%ebp)\n"
"	movl	%eax, n\n"
"	movsbl	%bl,%eax\n"
"	movl	(%ecx,%eax,4), %eax\n"
"	movb	%bl, %dl\n"
"	testl	%eax, %eax\n"
"	jne	.L82\n"
".L109:\n"
"	movl	$1, -16(%ebp)\n"
"	movl	-20(%ebp), %edx\n"
"	xorl	%eax, %eax\n"
"	cmpl	%edx, -16(%ebp)\n"
"	movl	%eax, seq\n"
"	jg	.L111\n"
"	.p2align 4,,15\n"
".L96:\n"
"	movsbl	%bl,%eax\n"
"	movl	isdig(,%eax,4), %eax\n"
"	testl	%eax, %eax\n"
"	jne	.L113\n"
"	movl	$isdig, %ecx\n"
"	.p2align 4,,15\n"
".L90:\n"
"	incl	%esi\n"
"	movzbl	(%esi), %ebx\n"
"	movsbl	%bl,%eax\n"
"	movl	(%ecx,%eax,4), %eax\n"
"	testl	%eax, %eax\n"
"	je	.L90\n"
".L113:\n"
"	movsbl	%bl,%eax\n"
"	incl	%esi\n"
"	leal	-48(%eax), %edx\n"
"	movzbl	(%esi), %eax\n"
"	movsbl	%al,%ecx\n"
"	movb	%al, %bl\n"
"	movl	isdig(,%ecx,4), %eax\n"
"	testl	%eax, %eax\n"
"	je	.L115\n"
"	movl	$isdig, %edi\n"
"	.p2align 4,,15\n"
".L95:\n"
"	leal	(%edx,%edx,4), %eax\n"
"	incl	%esi\n"
"	leal	-48(%ecx,%eax,2), %edx\n"
"	movzbl	(%esi), %eax\n"
"	movsbl	%al,%ecx\n"
"	movb	%al, %bl\n"
"	movl	(%edi,%ecx,4), %eax\n"
"	testl	%eax, %eax\n"
"	jne	.L95\n"
".L115:\n"
"	movl	-16(%ebp), %eax\n"
"	movl	%edx, seq(,%eax,4)\n"
"	movl	-20(%ebp), %edx\n"
"	incl	%eax\n"
"	movl	%eax, -16(%ebp)\n"
"	cmpl	%edx, %eax\n"
"	jle	.L96\n"
".L111:\n"
"	call	solve\n"
"	movl	ntests, %eax\n"
"	leal	-1(%eax), %edx\n"
"	testl	%eax, %eax\n"
"	movl	%edx, ntests\n"
"	jle	.L105\n"
"	movzbl	(%esi), %ebx\n"
"	jmp	.L97\n"
".L118:\n"
"	movl	n, %eax\n"
"	movl	%eax, -20(%ebp)\n"
"	jmp	.L109\n"
".L117:\n"
"	movl	ntests, %edx\n"
"	jmp	.L103\n"
".L116:\n"
"	movzbl	inbuf, %ebx\n"
"	jmp	.L101\n"
".L105:\n"
"	movl	$0, (%esp)\n"
"	call	exit\n"
);
}

int main()
{
	main2();
	return 0;
}
