int main()
{
__asm__ __volatile__(
"	pushl	%ebp\n"
"	movl	%esp, %ebp\n"
"	pushl	%edi\n"
"	pushl	%esi\n"
"	pushl	%ebx\n"
"	subl	$76, %esp\n"
"	movl	$0, -28(%ebp)\n"
"L11:\n"
"	xorl	%ecx, %ecx\n"
"	movl	-28(%ebp), %edx\n"
"	sall	$7, %edx\n"
"	.p2align 4,,15\n"
"L10:\n"
"	leal	(%ecx,%edx), %ebx\n"
"	movl	$1, %eax\n"
"	movl	%eax, _map(,%ebx,4)\n"
"	incl	%ecx\n"
"	cmpl	$100, %ecx\n"
"	jle	L10\n"
"	incl	-28(%ebp)\n"
"	cmpl	$100, -28(%ebp)\n"
"	jle	L11\n"
"	movl	$48, -28(%ebp)\n"
"L16:\n"
"	movl	-28(%ebp), %edx\n"
"	movl	$1, %ecx\n"
"	movl	%ecx, _isdig(,%edx,4)\n"
"	incl	%edx\n"
"	movl	%edx, -28(%ebp)\n"
"	cmpl	$57, %edx\n"
"	jle	L16\n"
"	movl	$1, %ecx\n"
"	movl	%ecx, _isnd+196\n"
"	movl	$1, %ebx\n"
"	movl	%ebx, _isnd+192\n"
"	movl	$1, %eax\n"
"	movl	%eax, _isnd+40\n"
"	movl	$1048576, %edx\n"
"	movl	%edx, 8(%esp)\n"
"	movl	$_inbuf, -20(%ebp)\n"
"	movl	$_inbuf, %edi\n"
"	movl	%edi, 4(%esp)\n"
"	movl	$0, (%esp)\n"
"	call	read\n"
"	movb	$10, _inbuf(%eax)\n"
"	movl	$_outbuf, -24(%ebp)\n"
"	movzbl	_inbuf, %esi\n"
"	movl	_isdig(,%esi,4), %ebx\n"
"	testl	%ebx, %ebx\n"
"	jne	L157\n"
"L20:\n"
"	incl	-20(%ebp)\n"
"	movl	-20(%ebp), %eax\n"
"	movzbl	(%eax), %ebx\n"
"	movzbl	%bl, %edi\n"
"	movl	_isdig(,%edi,4), %esi\n"
"	testl	%esi, %esi\n"
"	je	L20\n"
"L123:\n"
"	movzbl	%bl, %edi\n"
"	subl	$48, %edi\n"
"	movl	%edi, -28(%ebp)\n"
"	incl	-20(%ebp)\n"
"	movl	-20(%ebp), %edx\n"
"	movzbl	(%edx), %ebx\n"
"	movb	%bl, %dl\n"
"	movzbl	%bl, %esi\n"
"	movl	_isdig(,%esi,4), %ecx\n"
"	testl	%ecx, %ecx\n"
"	je	L125\n"
"L25:\n"
"	movl	-28(%ebp), %eax\n"
"	leal	(%eax,%eax,4), %ecx\n"
"	movzbl	%dl, %edi\n"
"	leal	-48(%edi,%ecx,2), %ebx\n"
"	movl	%ebx, -28(%ebp)\n"
"	incl	-20(%ebp)\n"
"	movl	-20(%ebp), %edx\n"
"	movzbl	(%edx), %ebx\n"
"	movb	%bl, %dl\n"
"	movzbl	%bl, %esi\n"
"	movl	_isdig(,%esi,4), %ecx\n"
"	testl	%ecx, %ecx\n"
"	jne	L25\n"
"L125:\n"
"	movl	-28(%ebp), %esi\n"
"	decl	%esi\n"
"	movl	%esi, -48(%ebp)\n"
"	movl	%esi, _ntests\n"
"	incl	%esi\n"
"	je	L127\n"
"L115:\n"
"	movzbl	%bl, %edi\n"
"	movl	_isdig(,%edi,4), %edx\n"
"	testl	%edx, %edx\n"
"	jne	L129\n"
"L32:\n"
"	incl	-20(%ebp)\n"
"	movl	-20(%ebp), %eax\n"
"	movzbl	(%eax), %ebx\n"
"	movzbl	%bl, %esi\n"
"	movl	_isdig(,%esi,4), %ecx\n"
"	testl	%ecx, %ecx\n"
"	je	L32\n"
"L129:\n"
"	movzbl	%bl, %esi\n"
"	subl	$48, %esi\n"
"	movl	%esi, -28(%ebp)\n"
"	incl	-20(%ebp)\n"
"	movl	-20(%ebp), %edx\n"
"	movzbl	(%edx), %ebx\n"
"	movb	%bl, %dl\n"
"	movzbl	%bl, %ecx\n"
"	movl	_isdig(,%ecx,4), %edi\n"
"	testl	%edi, %edi\n"
"	je	L131\n"
"L37:\n"
"	movl	-28(%ebp), %eax\n"
"	leal	(%eax,%eax,4), %edi\n"
"	movzbl	%dl, %esi\n"
"	leal	-48(%esi,%edi,2), %ebx\n"
"	movl	%ebx, -28(%ebp)\n"
"	incl	-20(%ebp)\n"
"	movl	-20(%ebp), %edx\n"
"	movzbl	(%edx), %ebx\n"
"	movb	%bl, %dl\n"
"	movzbl	%bl, %ecx\n"
"	movl	_isdig(,%ecx,4), %edi\n"
"	testl	%edi, %edi\n"
"	jne	L37\n"
"L131:\n"
"	movl	-28(%ebp), %esi\n"
"	movl	%esi, _sy\n"
"	movzbl	%bl, %edx\n"
"	movl	_isdig(,%edx,4), %ecx\n"
"	testl	%ecx, %ecx\n"
"	jne	L133\n"
"L41:\n"
"	incl	-20(%ebp)\n"
"	movl	-20(%ebp), %eax\n"
"	movzbl	(%eax), %ebx\n"
"	movzbl	%bl, %ecx\n"
"	movl	_isdig(,%ecx,4), %edi\n"
"	testl	%edi, %edi\n"
"	je	L41\n"
"L133:\n"
"	movzbl	%bl, %ecx\n"
"	subl	$48, %ecx\n"
"	movl	%ecx, -28(%ebp)\n"
"	incl	-20(%ebp)\n"
"	movl	-20(%ebp), %edx\n"
"	movzbl	(%edx), %ebx\n"
"	movb	%bl, %dl\n"
"	movzbl	%bl, %edi\n"
"	movl	_isdig(,%edi,4), %esi\n"
"	testl	%esi, %esi\n"
"	je	L135\n"
"L46:\n"
"	movl	-28(%ebp), %eax\n"
"	leal	(%eax,%eax,4), %esi\n"
"	movzbl	%dl, %ecx\n"
"	leal	-48(%ecx,%esi,2), %ebx\n"
"	movl	%ebx, -28(%ebp)\n"
"	incl	-20(%ebp)\n"
"	movl	-20(%ebp), %edx\n"
"	movzbl	(%edx), %ebx\n"
"	movb	%bl, %dl\n"
"	movzbl	%bl, %edi\n"
"	movl	_isdig(,%edi,4), %esi\n"
"	testl	%esi, %esi\n"
"	jne	L46\n"
"L135:\n"
"	movl	-28(%ebp), %edi\n"
"	movl	%edi, _sx\n"
"	cmpb	$47, %bl\n"
"	ja	L137\n"
"L50:\n"
"	incl	-20(%ebp)\n"
"	movl	-20(%ebp), %edx\n"
"	movzbl	(%edx), %ebx\n"
"	cmpb	$47, %bl\n"
"	jbe	L50\n"
"L137:\n"
"	movl	$0, -28(%ebp)\n"
"	movb	%bl, %al\n"
"	cmpb	$47, %bl\n"
"	jbe	L139\n"
"L55:\n"
"	incl	-28(%ebp)\n"
"	movzbl	%al, %ebx\n"
"	subl	$48, %ebx\n"
"	incl	-20(%ebp)\n"
"	movl	-28(%ebp), %edi\n"
"	movl	$_map, %ecx\n"
"	movl	%ebx, 512(%ecx,%edi,4)\n"
"	movl	-20(%ebp), %esi\n"
"	movzbl	(%esi), %ebx\n"
"	movb	%bl, %al\n"
"	cmpb	$47, %bl\n"
"	ja	L55\n"
"L139:\n"
"	movl	-28(%ebp), %edx\n"
"	movl	%edx, _width\n"
"	movl	$1, %ecx\n"
"	.p2align 4,,15\n"
"L160:\n"
"	incl	-20(%ebp)\n"
"	cmpb	$10, %bl\n"
"	je	L161\n"
"	movl	-20(%ebp), %eax\n"
"	movzbl	(%eax), %ebx\n"
"	jmp	L160\n"
"L161:\n"
"	movl	-20(%ebp), %edx\n"
"	movzbl	(%edx), %ebx\n"
"	movzbl	%bl, %edi\n"
"	movl	_isnd(,%edi,4), %esi\n"
"	testl	%esi, %esi\n"
"	jne	L141\n"
"	.p2align 4,,15\n"
"L65:\n"
"	incl	-20(%ebp)\n"
"	movl	-20(%ebp), %eax\n"
"	movzbl	(%eax), %ebx\n"
"	movzbl	%bl, %edi\n"
"	movl	_isnd(,%edi,4), %esi\n"
"	testl	%esi, %esi\n"
"	je	L65\n"
"L141:\n"
"	movb	%bl, %al\n"
"	cmpb	$10, %bl\n"
"	je	L57\n"
"	incl	%ecx\n"
"	movl	$0, -28(%ebp)\n"
"	cmpb	$47, %bl\n"
"	jbe	L160\n"
"	movl	%ecx, %esi\n"
"	sall	$7, %esi\n"
"	.p2align 4,,15\n"
"L71:\n"
"	incl	-28(%ebp)\n"
"	movl	-28(%ebp), %edx\n"
"	leal	(%edx,%esi), %edi\n"
"	movzbl	%al, %edx\n"
"	subl	$48, %edx\n"
"	incl	-20(%ebp)\n"
"	movl	%edx, _map(,%edi,4)\n"
"	movl	-20(%ebp), %ebx\n"
"	movzbl	(%ebx), %eax\n"
"	movb	%al, %bl\n"
"	cmpb	$47, %al\n"
"	ja	L71\n"
"	jmp	L160\n"
"L57:\n"
"	movl	%ecx, _height\n"
"	movl	_sy, %eax\n"
"	sall	$7, %eax\n"
"	movl	_sx, %ecx\n"
"	addl	%ecx, %eax\n"
"	movl	_map(,%eax,4), %esi\n"
"	testl	%esi, %esi\n"
"	je	L72\n"
"	movl	-24(%ebp), %eax\n"
"	movb	$48, (%eax)\n"
"	incl	%eax\n"
"	movb	$10, (%eax)\n"
"	incl	%eax\n"
"	movl	%eax, -24(%ebp)\n"
"L73:\n"
"	movl	-48(%ebp), %esi\n"
"	testl	%esi, %esi\n"
"	je	L26\n"
"	movl	-24(%ebp), %eax\n"
"	movb	$10, (%eax)\n"
"	incl	%eax\n"
"	movl	%eax, -24(%ebp)\n"
"	movl	$1, -28(%ebp)\n"
"	movl	_height, %edi\n"
"	cmpl	%edi, -28(%ebp)\n"
"	jg	L26\n"
"	movl	_width, %esi\n"
"L114:\n"
"	movl	$1, %ecx\n"
"	cmpl	%esi, %ecx\n"
"	jg	L156\n"
"	movl	-28(%ebp), %edx\n"
"	sall	$7, %edx\n"
"	.p2align 4,,15\n"
"L113:\n"
"	leal	(%ecx,%edx), %eax\n"
"	movl	$1, _map(,%eax,4)\n"
"	incl	%ecx\n"
"	cmpl	%esi, %ecx\n"
"	jle	L113\n"
"L156:\n"
"	incl	-28(%ebp)\n"
"	cmpl	%edi, -28(%ebp)\n"
"	jle	L114\n"
"L26:\n"
"	decl	-48(%ebp)\n"
"	movl	-48(%ebp), %edi\n"
"	movl	%edi, _ntests\n"
"	incl	%edi\n"
"	jne	L115\n"
"	jmp	L127\n"
"L72:\n"
"	movl	$1, %edi\n"
"	movl	%edi, _map(,%eax,4)\n"
"	movl	$1, %edi\n"
"	xorl	%esi, %esi\n"
"L94:\n"
"	movl	_sy(,%esi,4), %eax\n"
"	movl	%eax, -28(%ebp)\n"
"	movl	_sx(,%esi,4), %ecx\n"
"	movl	%ecx, -52(%ebp)\n"
"	sall	$7, %eax\n"
"	movl	%eax, -32(%ebp)\n"
"	movl	%eax, %edx\n"
"	addl	%ecx, %edx\n"
"	movl	_map+512(,%edx,4), %eax\n"
"	testl	%eax, %eax\n"
"	jne	L78\n"
"	movl	-28(%ebp), %eax\n"
"	incl	%eax\n"
"	movl	%eax, _sy(,%esi,4)\n"
"	sall	$7, %eax\n"
"	addl	%ecx, %eax\n"
"	movl	$1, _map(,%eax,4)\n"
"	incl	%edi\n"
"	incl	%esi\n"
"L78:\n"
"	movl	_map-512(,%edx,4), %eax\n"
"	testl	%eax, %eax\n"
"	jne	L79\n"
"	movl	-28(%ebp), %eax\n"
"	decl	%eax\n"
"	movl	%eax, _sy(,%esi,4)\n"
"	movl	%ecx, _sx(,%esi,4)\n"
"	sall	$7, %eax\n"
"	addl	%ecx, %eax\n"
"	movl	$1, %edx\n"
"	movl	%edx, _map(,%eax,4)\n"
"	incl	%edi\n"
"	incl	%esi\n"
"L79:\n"
"	incl	%ecx\n"
"	movl	-32(%ebp), %eax\n"
"	addl	%ecx, %eax\n"
"	movl	_map(,%eax,4), %edx\n"
"	testl	%edx, %edx\n"
"	jne	L147\n"
"	movl	-28(%ebp), %edx\n"
"	incl	%edx\n"
"	movl	%edx, -36(%ebp)\n"
"	movl	-28(%ebp), %edx\n"
"	decl	%edx\n"
"	movl	%edx, -56(%ebp)\n"
"	.p2align 4,,15\n"
"L86:\n"
"	movl	$1, %edx\n"
"	movl	%edx, _map(,%eax,4)\n"
"	incl	%edi\n"
"	movl	_map+512(,%eax,4), %edx\n"
"	testl	%edx, %edx\n"
"	jne	L84\n"
"	movl	-36(%ebp), %edx\n"
"	movl	%edx, _sy(,%esi,4)\n"
"	movl	%ecx, _sx(,%esi,4)\n"
"	movl	$1, %edx\n"
"	movl	%edx, _map+512(,%eax,4)\n"
"	incl	%edi\n"
"	incl	%esi\n"
"L84:\n"
"	movl	_map-512(,%eax,4), %edx\n"
"	testl	%edx, %edx\n"
"	jne	L82\n"
"	movl	-56(%ebp), %edx\n"
"	movl	%edx, _sy(,%esi,4)\n"
"	movl	%ecx, _sx(,%esi,4)\n"
"	movl	$1, %edx\n"
"	movl	%edx, _map-512(,%eax,4)\n"
"	incl	%edi\n"
"	incl	%esi\n"
"L82:\n"
"	incl	%ecx\n"
"	incl	%eax\n"
"	movl	_map(,%eax,4), %edx\n"
"	testl	%edx, %edx\n"
"	je	L86\n"
"L147:\n"
"	movl	-52(%ebp), %ecx\n"
"	decl	%ecx\n"
"	movl	-28(%ebp), %eax\n"
"	sall	$7, %eax\n"
"	addl	%ecx, %eax\n"
"	movl	_map(,%eax,4), %edx\n"
"	testl	%edx, %edx\n"
"	jne	L149\n"
"	movl	-28(%ebp), %edx\n"
"	incl	%edx\n"
"	movl	%edx, -40(%ebp)\n"
"	movl	-28(%ebp), %edx\n"
"	decl	%edx\n"
"	movl	%edx, -44(%ebp)\n"
"	leal	_map-512(,%eax,4), %edx\n"
"	movl	%edx, -56(%ebp)\n"
"	.p2align 4,,15\n"
"L93:\n"
"	movl	$1, %edx\n"
"	movl	%edx, _map(,%eax,4)\n"
"	incl	%edi\n"
"	movl	_map+512(,%eax,4), %edx\n"
"	testl	%edx, %edx\n"
"	jne	L91\n"
"	movl	-40(%ebp), %edx\n"
"	movl	%edx, _sy(,%esi,4)\n"
"	movl	%ecx, _sx(,%esi,4)\n"
"	movl	-56(%ebp), %edx\n"
"	movl	$1, 1024(%edx)\n"
"	incl	%edi\n"
"	incl	%esi\n"
"L91:\n"
"	movl	_map-512(,%eax,4), %edx\n"
"	testl	%edx, %edx\n"
"	jne	L89\n"
"	movl	-44(%ebp), %edx\n"
"	movl	%edx, _sy(,%esi,4)\n"
"	movl	%ecx, _sx(,%esi,4)\n"
"	movl	-56(%ebp), %edx\n"
"	movl	$1, (%edx)\n"
"	incl	%edi\n"
"	incl	%esi\n"
"L89:\n"
"	decl	%ecx\n"
"	decl	%eax\n"
"	subl	$4, -56(%ebp)\n"
"	movl	_map(,%eax,4), %edx\n"
"	testl	%edx, %edx\n"
"	je	L93\n"
"L149:\n"
"	movl	%esi, %edx\n"
"	decl	%esi\n"
"	testl	%edx, %edx\n"
"	jg	L94\n"
"	movl	-52(%ebp), %esi\n"
"	movl	%esi, _x0\n"
"	movl	%edi, %ecx\n"
"	movl	$0, -28(%ebp)\n"
"	testl	%edi, %edi\n"
"	jle	L151\n"
"	movl	$1717986919, %esi\n"
"L99:\n"
"	movl	%ecx, %eax\n"
"	imull	%esi\n"
"	movl	%eax, -64(%ebp)\n"
"	movl	%edx, -60(%ebp)\n"
"	movl	-60(%ebp), %edi\n"
"	sarl	$2, %edi\n"
"	movl	%ecx, %edx\n"
"	sarl	$31, %edx\n"
"	subl	%edx, %edi\n"
"	leal	(%edi,%edi,4), %edx\n"
"	addl	%edx, %edx\n"
"	subl	%edx, %ecx\n"
"	movb	%cl, %al\n"
"	addb	$48, %al\n"
"	movl	-28(%ebp), %edx\n"
"	movb	%al, _tmp(%edx)\n"
"	incl	%edx\n"
"	movl	%edx, -28(%ebp)\n"
"	movl	%edi, %ecx\n"
"	testl	%edi, %edi\n"
"	jg	L99\n"
"L151:\n"
"	decl	-28(%ebp)\n"
"	cmpl	$-1, -28(%ebp)\n"
"	je	L153\n"
"L103:\n"
"	movl	-28(%ebp), %esi\n"
"	movzbl	_tmp(%esi), %ecx\n"
"	movl	-24(%ebp), %edi\n"
"	movb	%cl, (%edi)\n"
"	incl	%edi\n"
"	movl	%edi, -24(%ebp)\n"
"	decl	%esi\n"
"	movl	%esi, -28(%ebp)\n"
"	incl	%esi\n"
"	jne	L103\n"
"L153:\n"
"	movl	-24(%ebp), %edx\n"
"	movb	$10, (%edx)\n"
"	incl	%edx\n"
"	movl	%edx, -24(%ebp)\n"
"	jmp	L73\n"
"L157:\n"
"	movzbl	_inbuf, %ebx\n"
"	jmp	L123\n"
"L127:\n"
"	subl	$_outbuf, -24(%ebp)\n"
"	movl	-24(%ebp), %ecx\n"
"	movl	%ecx, 8(%esp)\n"
"	movl	$_outbuf, %ebx\n"
"	movl	%ebx, 4(%esp)\n"
"	movl	$1, (%esp)\n"
"	call	write\n"
"	movl	$0, (%esp)\n"
"	call	exit\n"
".comm	_x0, 16\n"
".comm	_ntests, 16\n"
".comm	_width, 16\n"
".comm	_height, 16\n"
".comm	_map, 65536\n"
".comm	_sy, 262144\n"
".comm	_sx, 262144\n"
".comm	_tmp, 256\n"
".comm	_isdig, 1024\n"
".comm	_isnd, 1024\n"
".comm	_outbuf, 65536\n"
".comm	_inbuf, 1048576\n"
);
}
