void go()
{
__asm__ __volatile__(
"	jmp	main2\n"
"	.p2align 4,,15\n"
"xxsort:\n"
"	pushl	%ebp\n"
"	movl	%esp, %ebp\n"
"	pushl	%edi\n"
"	pushl	%esi\n"
"	pushl	%ebx\n"
"	subl	$28, %esp\n"
"	movl	8(%ebp), %edi\n"
"L2:\n"
"	cmpl	$31, 12(%ebp)\n"
"	jle	L31\n"
"	movl	12(%ebp), %edx\n"
"	decl	%edx\n"
"	sarl	%edx\n"
"	movl	(%edi,%edx,4), %esi\n"
"	movl	$-1, -16(%ebp)\n"
"	movl	12(%ebp), %ebx\n"
"	.p2align 4,,15\n"
"L29:\n"
"	movl	%esi, 4(%esp)\n"
"	incl	-16(%ebp)\n"
"	movl	-16(%ebp), %eax\n"
"	movl	(%edi,%eax,4), %ecx\n"
"	movl	%ecx, (%esp)\n"
"	call	strcmp\n"
"	testl	%eax, %eax\n"
"	js	L29\n"
"	.p2align 4,,15\n"
"L21:\n"
"	movl	%esi, 4(%esp)\n"
"	decl	%ebx\n"
"	movl	(%edi,%ebx,4), %edx\n"
"	movl	%edx, (%esp)\n"
"	call	strcmp\n"
"	testl	%eax, %eax\n"
"	jg	L21\n"
"	cmpl	%ebx, -16(%ebp)\n"
"	jge	L16\n"
"	movl	-16(%ebp), %edx\n"
"	movl	(%edi,%edx,4), %ecx\n"
"	movl	%ecx, -20(%ebp)\n"
"	movl	(%edi,%ebx,4), %edx\n"
"	movl	-16(%ebp), %ecx\n"
"	movl	%edx, (%edi,%ecx,4)\n"
"	movl	-20(%ebp), %ecx\n"
"	movl	%ecx, (%edi,%ebx,4)\n"
"	jmp	L29\n"
"L16:\n"
"	movl	12(%ebp), %eax\n"
"	movl	-16(%ebp), %esi\n"
"	subl	%esi, %eax\n"
"	cmpl	$1, %eax\n"
"	jg	L32\n"
"L25:\n"
"	movl	-16(%ebp), %ecx\n"
"	movl	%ecx, 12(%ebp)\n"
"	jmp	L2\n"
"L32:\n"
"	movl	%eax, 4(%esp)\n"
"	movl	-16(%ebp), %eax\n"
"	leal	(%edi,%eax,4), %ebx\n"
"	movl	%ebx, (%esp)\n"
"	call	xxsort\n"
"	jmp	L25\n"
"L31:\n"
"	movl	$1, -16(%ebp)\n"
"	movl	12(%ebp), %edx\n"
"	cmpl	%edx, -16(%ebp)\n"
"	jge	L1\n"
"L14:\n"
"	movl	-16(%ebp), %ecx\n"
"	movl	(%edi,%ecx,4), %eax\n"
"	movl	%eax, -20(%ebp)\n"
"	movl	-16(%ebp), %ebx\n"
"L30:\n"
"	decl	%ebx\n"
"	testl	%ebx, %ebx\n"
"	js	L9\n"
"	movl	-20(%ebp), %ecx\n"
"	movl	%ecx, 4(%esp)\n"
"	movl	(%edi,%ebx,4), %esi\n"
"	movl	%esi, (%esp)\n"
"	call	strcmp\n"
"	testl	%eax, %eax\n"
"	jle	L9\n"
"	movl	(%edi,%ebx,4), %edx\n"
"	movl	%edx, 4(%edi,%ebx,4)\n"
"	jmp	L30\n"
"L9:\n"
"	movl	-20(%ebp), %eax\n"
"	movl	%eax, 4(%edi,%ebx,4)\n"
"	incl	-16(%ebp)\n"
"	movl	12(%ebp), %ebx\n"
"	cmpl	%ebx, -16(%ebp)\n"
"	jl	L14\n"
"L1:\n"
"	addl	$28, %esp\n"
"	popl	%ebx\n"
"	popl	%esi\n"
"	popl	%edi\n"
"	popl	%ebp\n"
"	ret\n"
"	.p2align 4,,15\n"
"main2:\n"
"	pushl	%ebp\n"
"	movl	%esp, %ebp\n"
"	pushl	%edi\n"
"	pushl	%esi\n"
"	pushl	%ebx\n"
"	subl	$44, %esp\n"
"	movl	$97, %edi\n"
"	.p2align 4,,15\n"
"L38:\n"
"	movl	$1, %edx\n"
"	movl	%edx, _isalpz(,%edi,4)\n"
"	movl	$1, %eax\n"
"	movl	%eax, _isalp(,%edi,4)\n"
"	incl	%edi\n"
"	cmpl	$122, %edi\n"
"	jle	L38\n"
"	movl	$65, %edi\n"
"	.p2align 4,,15\n"
"L43:\n"
"	movl	$1, %ecx\n"
"	movl	%ecx, _isalpz(,%edi,4)\n"
"	movl	$1, %eax\n"
"	movl	%eax, _isalp(,%edi,4)\n"
"	incl	%edi\n"
"	cmpl	$90, %edi\n"
"	jle	L43\n"
"	movl	$1, %eax\n"
"	movl	%eax, _isalpz\n"
"	movl	$1048576, %edi\n"
"	movl	%edi, 8(%esp)\n"
"	movl	$_inbuf, -20(%ebp)\n"
"	movl	$_inbuf, %esi\n"
"	movl	%esi, 4(%esp)\n"
"	movl	$0, (%esp)\n"
"	call	read\n"
"	movb	$0, _inbuf(%eax)\n"
"	xorl	%ebx, %ebx\n"
"	movl	%ebx, _nwords\n"
"	movl	$_wordbuf, -24(%ebp)\n"
"L47:\n"
"	.p2align 4,,15\n"
"L89:\n"
"	movl	-20(%ebp), %esi\n"
"	movzbl	(%esi), %edx\n"
"	movzbl	%dl, %ebx\n"
"	movl	_isalpz(,%ebx,4), %ecx\n"
"	testl	%ecx, %ecx\n"
"	jne	L79\n"
"	.p2align 4,,15\n"
"L51:\n"
"	incl	-20(%ebp)\n"
"	movl	-20(%ebp), %eax\n"
"	movzbl	(%eax), %edx\n"
"	movzbl	%dl, %ecx\n"
"	movl	_isalpz(,%ecx,4), %edi\n"
"	testl	%edi, %edi\n"
"	je	L51\n"
"L79:\n"
"	testb	%dl, %dl\n"
"	je	L45\n"
"	movl	-24(%ebp), %ebx\n"
"	movb	%dl, %cl\n"
"	orb	$32, %cl\n"
"	incl	-20(%ebp)\n"
"	movb	%cl, (%ebx)\n"
"	movsbl	%cl,%edx\n"
"	leal	-97(%edx), %esi\n"
"	incl	%ebx\n"
"	movl	-20(%ebp), %edi\n"
"	movzbl	(%edi), %edx\n"
"	movzbl	%dl, %ecx\n"
"	movl	_isalp(,%ecx,4), %edi\n"
"	testl	%edi, %edi\n"
"	je	L81\n"
"	movl	$2147450881, %ecx\n"
"	.p2align 4,,15\n"
"L57:\n"
"	sall	$5, %esi\n"
"	movb	%dl, %al\n"
"	orb	$32, %al\n"
"	incl	-20(%ebp)\n"
"	movb	%al, (%ebx)\n"
"	movsbl	%al,%edi\n"
"	subl	$97, %edi\n"
"	orl	%edi, %esi\n"
"	incl	%ebx\n"
"	cmpl	$65536, %esi\n"
"	jle	L53\n"
"	movl	%esi, %eax\n"
"	imull	%ecx\n"
"	movl	%eax, -32(%ebp)\n"
"	movl	%edx, -28(%ebp)\n"
"	movl	-28(%ebp), %edx\n"
"	sarl	$15, %edx\n"
"	movl	%esi, %edi\n"
"	sarl	$31, %edi\n"
"	subl	%edi, %edx\n"
"	movl	%edx, %edi\n"
"	sall	$16, %edi\n"
"	addl	%edx, %edi\n"
"	subl	%edi, %esi\n"
"L53:\n"
"	movl	-20(%ebp), %edi\n"
"	movzbl	(%edi), %eax\n"
"	movb	%al, %dl\n"
"	movzbl	%al, %eax\n"
"	movl	_isalp(,%eax,4), %edi\n"
"	testl	%edi, %edi\n"
"	jne	L57\n"
"L81:\n"
"	movb	$0, (%ebx)\n"
"	incl	%ebx\n"
"	movl	_htab(,%esi,4), %edi\n"
"	movl	%edi, %edx\n"
"	testl	%edi, %edi\n"
"	jne	L63\n"
"L83:\n"
"	movl	_nwords, %edi\n"
"	incl	%edi\n"
"	movl	%edi, _nwords\n"
"	movl	-24(%ebp), %eax\n"
"	movl	%eax, _words(,%edi,4)\n"
"	movl	%ebx, -24(%ebp)\n"
"	movl	%edx, _tab_next(,%edi,4)\n"
"	movl	%edi, _htab(,%esi,4)\n"
"	jmp	L89\n"
"	.p2align 4,,7\n"
"L63:\n"
"	movl	-24(%ebp), %eax\n"
"	movl	%eax, 4(%esp)\n"
"	movl	_words(,%edi,4), %edx\n"
"	movl	%edx, (%esp)\n"
"	call	strcmp\n"
"	testl	%eax, %eax\n"
"	je	L89\n"
"	movl	_tab_next(,%edi,4), %edi\n"
"	testl	%edi, %edi\n"
"	jne	L63\n"
"	movl	_htab(,%esi,4), %edx\n"
"	jmp	L83\n"
"L45:\n"
"	movl	_nwords, %ebx\n"
"	movl	%ebx, 4(%esp)\n"
"	movl	$_words+4, (%esp)\n"
"	call	xxsort\n"
"	movl	$1, %edi\n"
"	movl	$_inbuf, -20(%ebp)\n"
"	cmpl	_nwords, %edi\n"
"	jg	L85\n"
"L73:\n"
"	movl	_words(,%edi,4), %ebx\n"
"	movzbl	(%ebx), %eax\n"
"	testb	%al, %al\n"
"	je	L87\n"
"	.p2align 4,,15\n"
"L72:\n"
"	incl	%ebx\n"
"	movl	-20(%ebp), %esi\n"
"	movb	%al, (%esi)\n"
"	incl	%esi\n"
"	movl	%esi, -20(%ebp)\n"
"	movzbl	(%ebx), %eax\n"
"	testb	%al, %al\n"
"	jne	L72\n"
"L87:\n"
"	movl	-20(%ebp), %edx\n"
"	movb	$10, (%edx)\n"
"	incl	%edx\n"
"	movl	%edx, -20(%ebp)\n"
"	incl	%edi\n"
"	cmpl	_nwords, %edi\n"
"	jle	L73\n"
"L85:\n"
"	subl	$_inbuf, -20(%ebp)\n"
"	movl	-20(%ebp), %ecx\n"
"	movl	%ecx, 8(%esp)\n"
"	movl	$_inbuf, %edi\n"
"	movl	%edi, 4(%esp)\n"
"	movl	$1, (%esp)\n"
"	call	write\n"
"	movl	$0, (%esp)\n"
"	call	exit\n"
"	.comm	_inbuf, 1048576	 # 1048576\n"
"	.comm	_wordbuf, 1048576	 # 1048576\n"
"	.comm	_words, 32768	 # 32768\n"
"	.comm	_isalp, 1024	 # 1024\n"
"	.comm	_isalpz, 1024	 # 1024\n"
"	.comm	_tab_next, 32768	 # 32768\n"
"	.comm	_htab, 262160	 # 262148\n"
"	.comm	_nwords, 16	 # 4\n"
);
}

int main()
{
	go();
	return 0;
}

