int main()
{
__asm__ __volatile__(
"	pushl	%ebp\n"
"	movl	%esp, %ebp\n"
"	pushl	%edi\n"
"	pushl	%esi\n"
"	pushl	%ebx\n"
"	subl	$28, %esp\n"
"	movl	$48, %esi\n"
"	.p2align 4,,15\n"
"L63:\n"
"	movl	$1, %edx\n"
"	movl	%edx, _isdig.6(,%esi,4)\n"
"	incl	%esi\n"
"	cmpl	$57, %esi\n"
"	jbe	L63\n"
"	movl	$65536, %edx\n"
"	movl	%edx, 8(%esp)\n"
"	movl	$_inbuf.3, -16(%ebp)\n"
"	movl	$_inbuf.3, %eax\n"
"	movl	%eax, 4(%esp)\n"
"	movl	$0, (%esp)\n"
"	call	read\n"
"	movl	$_outbuf.4, %edi\n"
"	.p2align 4,,15\n"
"L64:\n"
"	movl	-16(%ebp), %edx\n"
"	movzbl	(%edx), %ecx\n"
"	movsbl	%cl,%esi\n"
"	movl	_isdig.6(,%esi,4), %ebx\n"
"	testl	%ebx, %ebx\n"
"	jne	L93\n"
"	.p2align 4,,15\n"
"L70:\n"
"	incl	-16(%ebp)\n"
"	movl	-16(%ebp), %eax\n"
"	movzbl	(%eax), %ecx\n"
"	movsbl	%cl,%ebx\n"
"	movl	_isdig.6(,%ebx,4), %esi\n"
"	testl	%esi, %esi\n"
"	je	L70\n"
"L93:\n"
"	movl	-16(%ebp), %ebx\n"
"	movsbl	%cl,%edx\n"
"	leal	-48(%edx), %esi\n"
"	leal	1(%ebx), %ecx\n"
"	movl	%ecx, -16(%ebp)\n"
"	movzbl	1(%ebx), %edx\n"
"	movsbl	%dl,%eax\n"
"	movl	_isdig.6(,%eax,4), %ecx\n"
"	testl	%ecx, %ecx\n"
"	je	L95\n"
"	movb	%dl, %cl\n"
"	.p2align 4,,15\n"
"L75:\n"
"	leal	(%esi,%esi,4), %edx\n"
"	movsbl	%cl,%eax\n"
"	leal	-48(%eax,%edx,2), %esi\n"
"	incl	-16(%ebp)\n"
"	movl	-16(%ebp), %ecx\n"
"	movzbl	(%ecx), %eax\n"
"	movb	%al, %cl\n"
"	movsbl	%al,%eax\n"
"	movl	_isdig.6(,%eax,4), %edx\n"
"	testl	%edx, %edx\n"
"	jne	L75\n"
"L95:\n"
"	testl	%esi, %esi\n"
"	je	L65\n"
"	cmpl	-16(%ebp), %ebx\n"
"	jae	L97\n"
"	.p2align 4,,15\n"
"L80:\n"
"	movzbl	(%ebx), %edx\n"
"	incl	%ebx\n"
"	movb	%dl, (%edi)\n"
"	incl	%edi\n"
"	cmpl	-16(%ebp), %ebx\n"
"	jb	L80\n"
"L97:\n"
"	movb	$32, (%edi)\n"
"	incl	%edi\n"
"	movl	%esi, (%esp)\n"
"	call	_solve\n"
"	movl	%eax, %esi\n"
"	movl	$_tmp.5, %ebx\n"
"	testl	%eax, %eax\n"
"	je	L99\n"
"	movl	$-858993459, %ecx\n"
"	.p2align 4,,15\n"
"L85:\n"
"	movl	%esi, %eax\n"
"	mull	%ecx\n"
"	shrl	$3, %edx\n"
"	leal	(%edx,%edx,4), %eax\n"
"	addl	%eax, %eax\n"
"	subl	%eax, %esi\n"
"	movl	%esi, %eax\n"
"	addb	$48, %al\n"
"	movb	%al, (%ebx)\n"
"	incl	%ebx\n"
"	movl	%edx, %esi\n"
"	testl	%edx, %edx\n"
"	jne	L85\n"
"L99:\n"
"	decl	%ebx\n"
"	cmpl	$_tmp.5-1, %ebx\n"
"	jbe	L101\n"
"	.p2align 4,,15\n"
"L89:\n"
"	movzbl	(%ebx), %ecx\n"
"	movb	%cl, (%edi)\n"
"	incl	%edi\n"
"	decl	%ebx\n"
"	cmpl	$_tmp.5-1, %ebx\n"
"	ja	L89\n"
"L101:\n"
"	movb	$10, (%edi)\n"
"	incl	%edi\n"
"	jmp	L64\n"
"L65:\n"
"	subl	$_outbuf.4, %edi\n"
"	movl	%edi, 8(%esp)\n"
"	movl	$_outbuf.4, %edi\n"
"	movl	%edi, 4(%esp)\n"
"	movl	$1, (%esp)\n"
"	call	write\n"
"	movl	$0, (%esp)\n"
"	call	exit\n"
"	.p2align 4,,15\n"
"_solve:\n"
"	pushl	%ebp\n"
"	movl	%esp, %ebp\n"
"	pushl	%esi\n"
"	pushl	%ebx\n"
"	subl	$16, %esp\n"
"	movl	8(%ebp), %edx\n"
"	movl	%edx, 4(%esp)\n"
"	movl	$_e.1, (%esp)\n"
"	call	_factorize\n"
"	movl	%eax, %ecx\n"
"	movl	%eax, _n.2\n"
"	xorl	%edx, %edx\n"
"	.p2align 4,,15\n"
"L40:\n"
"	xorl	%ebx, %ebx\n"
"	movl	%ebx, _a.0(,%edx,4)\n"
"	incl	%edx\n"
"	cmpl	%ecx, %edx\n"
"	jbe	L40\n"
"	xorl	%esi, %esi\n"
"L41:\n"
"	movl	$1, %ebx\n"
"	xorl	%edx, %edx\n"
"	cmpl	%ecx, %edx\n"
"	jae	L112\n"
"	.p2align 4,,15\n"
"L49:\n"
"	movl	_a.0(,%edx,4), %eax\n"
"	cmpl	_e.1(,%edx,4), %eax\n"
"	je	L115\n"
"L46:\n"
"	incl	%edx\n"
"	cmpl	%ecx, %edx\n"
"	jb	L49\n"
"L112:\n"
"	addl	%ebx, %esi\n"
"	xorl	%edx, %edx\n"
"	cmpl	%ecx, %edx\n"
"	jae	L114\n"
"	.p2align 4,,15\n"
"L56:\n"
"	movl	_a.0(,%edx,4), %ebx\n"
"	incl	%ebx\n"
"	movl	%ebx, _a.0(,%edx,4)\n"
"	cmpl	_e.1(,%edx,4), %ebx\n"
"	jbe	L51\n"
"	xorl	%ebx, %ebx\n"
"	movl	%ebx, _a.0(,%edx,4)\n"
"	incl	%edx\n"
"	cmpl	%ecx, %edx\n"
"	jb	L56\n"
"L114:\n"
"	leal	1(%esi), %eax\n"
"	shrl	%eax\n"
"	addl	$16, %esp\n"
"	popl	%ebx\n"
"	popl	%esi\n"
"	popl	%ebp\n"
"	ret\n"
"L51:\n"
"	cmpl	%ecx, %edx\n"
"	jb	L41\n"
"	jmp	L114\n"
"	.p2align 4,,7\n"
"L115:\n"
"	incl	%eax\n"
"	imull	%eax, %ebx\n"
"	jmp	L46\n"
"	.p2align 4,,15\n"
"_factorize:\n"
"	pushl	%ebp\n"
"	movl	%esp, %ebp\n"
"	pushl	%edi\n"
"	pushl	%esi\n"
"	pushl	%ebx\n"
"	subl	$4, %esp\n"
"	movl	12(%ebp), %ebx\n"
"	xorl	%edi, %edi\n"
"	xorl	%eax, %eax\n"
"	testl	%ebx, %ebx\n"
"	je	L1\n"
"	testb	$1, %bl\n"
"	jne	L3\n"
"	movl	8(%ebp), %edx\n"
"	movl	$0, (%edx)\n"
"	.p2align 4,,15\n"
"L8:\n"
"	movl	8(%ebp), %ecx\n"
"	movl	(%ecx), %edx\n"
"	incl	%edx\n"
"	movl	%edx, (%ecx,%edi,4)\n"
"	shrl	%ebx\n"
"	testb	$1, %bl\n"
"	je	L8\n"
"	movl	$1, %edi\n"
"L3:\n"
"	movl	$3, %esi\n"
"	movl	%ebx, %ecx\n"
"	cmpl	$1, %ebx\n"
"	jbe	L10\n"
"	.p2align 4,,15\n"
"L14:\n"
"	movl	%ebx, %eax\n"
"	xorl	%edx, %edx\n"
"	divl	%ecx\n"
"	leal	(%eax,%ecx), %eax\n"
"	shrl	%eax\n"
"	cmpl	%ecx, %eax\n"
"	jae	L10\n"
"	movl	%eax, %ecx\n"
"	cmpl	$1, %eax\n"
"	ja	L14\n"
"L10:\n"
"	incl	%ecx\n"
"	movl	%ecx, -16(%ebp)\n"
"	cmpl	%ecx, %esi\n"
"	ja	L120\n"
"	.p2align 4,,15\n"
"L33:\n"
"	movl	%ebx, %eax\n"
"	xorl	%edx, %edx\n"
"	divl	%esi\n"
"	testl	%edx, %edx\n"
"	jne	L18\n"
"	movl	8(%ebp), %ebx\n"
"	movl	$1, (%ebx,%edi,4)\n"
"	movl	%eax, %ebx\n"
"	xorl	%edx, %edx\n"
"	divl	%esi\n"
"	testl	%edx, %edx\n"
"	jne	L122\n"
"	movl	$1, %ecx\n"
"	.p2align 4,,15\n"
"L25:\n"
"	movl	%ebx, %eax\n"
"	xorl	%edx, %edx\n"
"	divl	%esi\n"
"	movl	%eax, %ebx\n"
"	incl	%ecx\n"
"	xorl	%edx, %edx\n"
"	divl	%esi\n"
"	testl	%edx, %edx\n"
"	je	L25\n"
"	movl	8(%ebp), %eax\n"
"	movl	%ecx, (%eax,%edi,4)\n"
"L122:\n"
"	incl	%edi\n"
"	movl	%ebx, %ecx\n"
"	cmpl	$1, %ebx\n"
"	jbe	L27\n"
"	.p2align 4,,15\n"
"L31:\n"
"	movl	%ebx, %eax\n"
"	xorl	%edx, %edx\n"
"	divl	%ecx\n"
"	leal	(%eax,%ecx), %eax\n"
"	shrl	%eax\n"
"	cmpl	%ecx, %eax\n"
"	jae	L27\n"
"	movl	%eax, %ecx\n"
"	cmpl	$1, %eax\n"
"	ja	L31\n"
"L27:\n"
"	movl	%ecx, -16(%ebp)\n"
"L18:\n"
"	addl	$2, %esi\n"
"	cmpl	-16(%ebp), %esi\n"
"	jbe	L33\n"
"L120:\n"
"	cmpl	$1, %ebx\n"
"	jbe	L34\n"
"	movl	8(%ebp), %esi\n"
"	movl	$1, (%esi,%edi,4)\n"
"	incl	%edi\n"
"L34:\n"
"	movl	%edi, %eax\n"
"L1:\n"
"	popl	%edx\n"
"	popl	%ebx\n"
"	popl	%esi\n"
"	popl	%edi\n"
"	popl	%ebp\n"
"	ret\n"
".lcomm _a.0,512\n"
".lcomm _e.1,512\n"
".lcomm _n.2,16\n"
".lcomm _tmp.5,256\n"
".lcomm _isdig.6,1024\n"
".lcomm _inbuf.3,65536\n"
".lcomm _outbuf.4,65536\n"
);
}
