void go()
{
__asm__ __volatile__(
"	jmp	main2\n"
"	.p2align 4,,15\n"
"heap_up:\n"
"	pushl	%ebp\n"
"	movl	%esp, %ebp\n"
"	pushl	%edi\n"
"	movl	8(%ebp), %ecx\n"
"	pushl	%esi\n"
"	pushl	%ebx\n"
"	cmpl	$1, %ecx\n"
"	movl	xxheap(,%ecx,4), %esi\n"
"	jle	LB3\n"
"	movl	%ecx, %ebx\n"
"	sarl	%ebx\n"
"	movl	xxheap(,%ebx,4), %eax\n"
"	movl	xxdist(,%eax,4), %eax\n"
"	cmpl	xxdist(,%esi,4), %eax\n"
"	jle	LB3\n"
"	movl	$xxdist, %edi\n"
"	.p2align 4,,15\n"
"LB7:\n"
"	movl	xxheap(,%ebx,4), %eax\n"
"	cmpl	$1, %ebx\n"
"	movl	%eax, xxheap(,%ecx,4)\n"
"	movl	%ecx, xxrank(,%eax,4)\n"
"	movl	%ebx, %ecx\n"
"	jle	LB3\n"
"	sarl	%ebx\n"
"	movl	xxheap(,%ebx,4), %edx\n"
"	movl	(%edi,%esi,4), %eax\n"
"	cmpl	%eax, (%edi,%edx,4)\n"
"	jg	LB7\n"
"LB3:\n"
"	popl	%ebx\n"
"	movl	%esi, xxheap(,%ecx,4)\n"
"	movl	%ecx, xxrank(,%esi,4)\n"
"	popl	%esi\n"
"	popl	%edi\n"
"	popl	%ebp\n"
"	ret\n"
"	.p2align 4,,15\n"
"heap_down:\n"
"	pushl	%ebp\n"
"	movl	%esp, %ebp\n"
"	pushl	%edi\n"
"	pushl	%esi\n"
"	pushl	%ebx\n"
"	subl	$4, %esp\n"
"	movl	8(%ebp), %ebx\n"
"	movl	xxheap_n, %eax\n"
"	leal	(%ebx,%ebx), %ecx\n"
"	cmpl	%eax, %ecx\n"
"	movl	%eax, -16(%ebp)\n"
"	jg	LB13\n"
"	movl	$xxheap, %edi\n"
"	.p2align 4,,15\n"
"LB19:\n"
"	movl	xxheap(,%ebx,4), %edx\n"
"	movl	xxheap(,%ecx,4), %eax\n"
"	movl	xxdist(,%edx,4), %edx\n"
"	cmpl	%edx, xxdist(,%eax,4)\n"
"	jge	LB15\n"
"	movl	%ecx, %esi\n"
"LB16:\n"
"	incl	%ecx\n"
"	cmpl	-16(%ebp), %ecx\n"
"	jg	LB17\n"
"	movl	xxheap(,%esi,4), %edx\n"
"	movl	xxheap(,%ecx,4), %eax\n"
"	movl	xxdist(,%edx,4), %edx\n"
"	cmpl	%edx, xxdist(,%eax,4)\n"
"	jge	LB17\n"
"	movl	%ecx, %esi\n"
"LB17:\n"
"	cmpl	%ebx, %esi\n"
"	je	LB13\n"
"	leal	(%esi,%esi), %ecx\n"
"	movl	(%edi,%ebx,4), %edx\n"
"	movl	(%edi,%esi,4), %eax\n"
"	cmpl	-16(%ebp), %ecx\n"
"	movl	%eax, (%edi,%ebx,4)\n"
"	movl	%ebx, xxrank(,%eax,4)\n"
"	movl	%esi, %ebx\n"
"	movl	%edx, (%edi,%esi,4)\n"
"	jle	LB19\n"
"LB13:\n"
"	movl	xxheap(,%ebx,4), %eax\n"
"	movl	%ebx, xxrank(,%eax,4)\n"
"	popl	%eax\n"
"	popl	%ebx\n"
"	popl	%esi\n"
"	popl	%edi\n"
"	popl	%ebp\n"
"	ret\n"
"	.p2align 4,,7\n"
"LB15:\n"
"	movl	%ebx, %esi\n"
"	jmp	LB16\n"
"	.p2align 4,,15\n"
"heap_add:\n"
"	pushl	%ebp\n"
"	movl	%esp, %ebp\n"
"	movl	xxheap_n, %eax\n"
"	movl	8(%ebp), %edx\n"
"	incl	%eax\n"
"	movl	%eax, xxheap_n\n"
"	movl	%eax, xxrank(,%edx,4)\n"
"	movl	%edx, xxheap(,%eax,4)\n"
"	movl	%eax, 8(%ebp)\n"
"	popl	%ebp\n"
"	jmp	heap_up\n"
"	.p2align 4,,15\n"
"heap_get:\n"
"	pushl	%ebp\n"
"	movl	%esp, %ebp\n"
"	subl	$8, %esp\n"
"	movl	%ebx, -4(%ebp)\n"
"	movl	xxheap_n, %eax\n"
"	movl	$-1, %edx\n"
"	testl	%eax, %eax\n"
"	jle	LB23\n"
"	cmpl	$1, %eax\n"
"	movl	xxheap+4, %ebx\n"
"	je	LB27\n"
"	movl	$1, (%esp)\n"
"	movl	xxheap(,%eax,4), %edx\n"
"	movl	$1, %ecx\n"
"	decl	%eax\n"
"	movl	%edx, xxheap+4\n"
"	movl	%eax, xxheap_n\n"
"	movl	%ecx, xxrank(,%edx,4)\n"
"	call	heap_down\n"
"LB26:\n"
"	movl	$-1, %edx\n"
"	movl	%edx, xxrank(,%ebx,4)\n"
"	movl	%ebx, %edx\n"
"LB23:\n"
"	movl	-4(%ebp), %ebx\n"
"	movl	%ebp, %esp\n"
"	movl	%edx, %eax\n"
"	popl	%ebp\n"
"	ret\n"
"	.p2align 4,,7\n"
"LB27:\n"
"	xorl	%eax, %eax\n"
"	movl	%eax, xxheap_n\n"
"	jmp	LB26\n"
"	.p2align 4,,15\n"
"xxtake:\n"
"	pushl	%ebp\n"
"	movl	%esp, %ebp\n"
"	movl	n, %ecx\n"
"	pushl	%edi\n"
"	pushl	%esi\n"
"	movl	12(%ebp), %esi\n"
"	decl	%ecx\n"
"	pushl	%ebx\n"
"	movl	8(%ebp), %ebx\n"
"	testl	%ecx, %ecx\n"
"	movl	$0, (%esi)\n"
"	movl	$0, (%ebx)\n"
"	js	LB28\n"
"	movl	xxinp, %edx\n"
"	cmpb	$0, (%edx)\n"
"	je	LB28\n"
"	movl	$1, %edi\n"
"	.p2align 4,,15\n"
"LB39:\n"
"	movzbl	(%edx), %eax\n"
"	cmpb	$48, %al\n"
"	je	LB41\n"
"	cmpb	$43, %al\n"
"	je	LB42\n"
"	cmpb	$45, %al\n"
"	je	LB43\n"
"LB31:\n"
"	movl	%edx, %eax\n"
"	incl	%edx\n"
"	testl	%ecx, %ecx\n"
"	movl	%edx, xxinp\n"
"	js	LB28\n"
"	cmpb	$0, 1(%eax)\n"
"	jne	LB39\n"
"LB28:\n"
"	popl	%ebx\n"
"	popl	%esi\n"
"	popl	%edi\n"
"	popl	%ebp\n"
"	ret\n"
"	.p2align 4,,7\n"
"LB43:\n"
"	movl	$1, %eax\n"
"	sall	%cl, %eax\n"
"	orl	%eax, (%esi)\n"
"LB41:\n"
"	decl	%ecx\n"
"	jmp	LB31\n"
"	.p2align 4,,7\n"
"LB42:\n"
"	movl	%edi, %eax\n"
"	sall	%cl, %eax\n"
"	orl	%eax, (%ebx)\n"
"	jmp	LB41\n"
"	.p2align 4,,15\n"
"xxsolve:\n"
"	pushl	%ebp\n"
"	movl	%esp, %ebp\n"
"	pushl	%edi\n"
"	pushl	%esi\n"
"	pushl	%ebx\n"
"	xorl	%ebx, %ebx\n"
"	subl	$12, %esp\n"
"	movl	xxall, %eax\n"
"	cmpl	%eax, %ebx\n"
"	jg	LB74\n"
"	movl	$xxdist, %edx\n"
"	.p2align 4,,15\n"
"LB49:\n"
"	movl	$2147483647, (%edx,%ebx,4)\n"
"	incl	%ebx\n"
"	cmpl	%eax, %ebx\n"
"	jle	LB49\n"
"	xorl	%ebx, %ebx\n"
"	cmpl	%eax, %ebx\n"
"	jg	LB74\n"
"	movl	$xxrank, %edx\n"
"	.p2align 4,,15\n"
"LB54:\n"
"	movl	$0, (%edx,%ebx,4)\n"
"	incl	%ebx\n"
"	cmpl	%eax, %ebx\n"
"	jle	LB54\n"
"LB74:\n"
"	movl	%eax, (%esp)\n"
"	xorl	%esi, %esi\n"
"	xorl	%ebx, %ebx\n"
"	movl	%esi, xxheap_n\n"
"	movl	%ebx, xxdist(,%eax,4)\n"
"	call	heap_add\n"
"	.p2align 4,,15\n"
"LB55:\n"
"	call	heap_get\n"
"	testl	%eax, %eax\n"
"	movl	%eax, %edi\n"
"	jle	LB78\n"
"	movl	m, %edx\n"
"	xorl	%ebx, %ebx\n"
"	cmpl	%edx, %ebx\n"
"	jge	LB55\n"
"	xorl	%esi, %esi\n"
"	.p2align 4,,15\n"
"LB67:\n"
"	movl	xxpatch+24(%esi), %ecx\n"
"	movl	%edi, %eax\n"
"	andl	%ecx, %eax\n"
"	cmpl	xxpatch+28(%esi), %eax\n"
"	je	LB79\n"
"LB60:\n"
"	incl	%ebx\n"
"	addl	$32, %esi\n"
"	cmpl	%edx, %ebx\n"
"	jl	LB67\n"
"	jmp	LB55\n"
"	.p2align 4,,7\n"
"LB79:\n"
"	movl	xxpatch+8(%esi), %eax\n"
"	movl	%edi, %ecx\n"
"	orl	%eax, %ecx\n"
"	movl	xxpatch+16(%esi), %eax\n"
"	andl	%eax, %ecx\n"
"	movl	xxpatch+20(%esi), %eax\n"
"	addl	xxdist(,%edi,4), %eax\n"
"	cmpl	%eax, xxdist(,%ecx,4)\n"
"	jle	LB60\n"
"	movl	%eax, xxdist(,%ecx,4)\n"
"	movl	xxrank(,%ecx,4), %eax\n"
"	testl	%eax, %eax\n"
"	je	LB80\n"
"	testl	%eax, %eax\n"
"	jle	LB60\n"
"	movl	%eax, (%esp)\n"
"	call	heap_up\n"
"LB77:\n"
"	movl	m, %edx\n"
"	jmp	LB60\n"
"LB80:\n"
"	movl	%ecx, (%esp)\n"
"	call	heap_add\n"
"	jmp	LB77\n"
"LB78:\n"
"	testl	%edi, %edi\n"
"	movl	$-1, %eax\n"
"	jne	LB70\n"
"	movl	xxdist, %eax\n"
"LB70:\n"
"	addl	$12, %esp\n"
"	popl	%ebx\n"
"	popl	%esi\n"
"	popl	%edi\n"
"	popl	%ebp\n"
"	ret\n"
"LBC0:\n"
"	.string	\"Product %d\\n\"\n"
"	.align 32\n"
"LBC2:\n"
"	.string	\"Fastest sequence takes %d seconds.\\n\\n\"\n"
"LBC1:\n"
"	.string	\"Bugs cannot be fixed.\\n\\n\"\n"
"	.text\n"
"	.p2align 4,,15\n"
"main2:\n"
"	pushl	%ebp\n"
"	movl	%esp, %ebp\n"
"	movl	$inbuf, %edx\n"
"	pushl	%edi\n"
"	xorl	%edi, %edi\n"
"	pushl	%esi\n"
"	pushl	%ebx\n"
"	subl	$28, %esp\n"
"	movl	%edx, xxinp\n"
"	movl	$1048576, 8(%esp)\n"
"	movl	$inbuf, 4(%esp)\n"
"	movl	$0, (%esp)\n"
"	call	read\n"
"	movl	$xxisdig, %edx\n"
"	movb	$0, inbuf(%eax)\n"
"	.p2align 4,,15\n"
"LB86:\n"
"	leal	-48(%edi), %eax\n"
"	cmpl	$9, %eax\n"
"	setbe	%al\n"
"	movzbl	%al, %eax\n"
"	movl	%eax, (%edx,%edi,4)\n"
"	incl	%edi\n"
"	cmpl	$255, %edi\n"
"	jle	LB86\n"
"	movl	$1, -16(%ebp)\n"
"LB87:\n"
"	movl	xxinp, %ebx\n"
"	movl	%ebx, %ecx\n"
"	movsbl	(%ebx),%eax\n"
"	movl	xxisdig(,%eax,4), %eax\n"
"	testl	%eax, %eax\n"
"	jne	LB128\n"
"	movl	$xxisdig, %esi\n"
"	leal	1(%ebx), %edx\n"
"	.p2align 4,,15\n"
"LB93:\n"
"	movl	%edx, xxinp\n"
"	movl	%edx, %ebx\n"
"	leal	2(%ecx), %edx\n"
"	movsbl	-1(%edx),%eax\n"
"	movl	%ebx, %ecx\n"
"	movl	(%esi,%eax,4), %eax\n"
"	testl	%eax, %eax\n"
"	je	LB93\n"
"LB128:\n"
"	movsbl	(%ebx),%edx\n"
"	movl	%ebx, %eax\n"
"	incl	%ebx\n"
"	movl	%ebx, xxinp\n"
"	leal	-48(%edx), %esi\n"
"	movl	%esi, n\n"
"	movsbl	1(%eax),%eax\n"
"	movl	xxisdig(,%eax,4), %eax\n"
"	testl	%eax, %eax\n"
"	je	LB141\n"
"	movl	$xxisdig, %edi\n"
"	.p2align 4,,15\n"
"LB98:\n"
"	movsbl	(%ebx),%eax\n"
"	leal	(%esi,%esi,4), %edx\n"
"	movl	%ebx, %ecx\n"
"	incl	%ebx\n"
"	movl	%ebx, xxinp\n"
"	leal	-48(%eax,%edx,2), %esi\n"
"	movl	%esi, n\n"
"	movsbl	1(%ecx),%eax\n"
"	movl	(%edi,%eax,4), %eax\n"
"	testl	%eax, %eax\n"
"	jne	LB98\n"
"LB130:\n"
"	testl	%esi, %esi\n"
"	je	LB88\n"
"	movsbl	(%ebx),%eax\n"
"	movl	%ebx, %ecx\n"
"	movl	xxisdig(,%eax,4), %eax\n"
"	testl	%eax, %eax\n"
"	jne	LB132\n"
"	movl	$xxisdig, %edi\n"
"	leal	1(%ebx), %edx\n"
"	.p2align 4,,15\n"
"LB103:\n"
"	movl	%edx, xxinp\n"
"	movl	%edx, %ebx\n"
"	leal	2(%ecx), %edx\n"
"	movsbl	-1(%edx),%eax\n"
"	movl	%ebx, %ecx\n"
"	movl	(%edi,%eax,4), %eax\n"
"	testl	%eax, %eax\n"
"	je	LB103\n"
"LB132:\n"
"	movsbl	(%ebx),%edx\n"
"	movl	%ebx, %eax\n"
"	incl	%ebx\n"
"	movl	%ebx, xxinp\n"
"	subl	$48, %edx\n"
"	movl	%edx, m\n"
"	movsbl	1(%eax),%eax\n"
"	movl	xxisdig(,%eax,4), %eax\n"
"	testl	%eax, %eax\n"
"	je	LB142\n"
"	movl	$xxisdig, %edi\n"
"	.p2align 4,,15\n"
"LB108:\n"
"	movsbl	(%ebx),%eax\n"
"	leal	(%edx,%edx,4), %edx\n"
"	movl	%ebx, %ecx\n"
"	incl	%ebx\n"
"	movl	%ebx, xxinp\n"
"	leal	-48(%eax,%edx,2), %edx\n"
"	movl	%edx, m\n"
"	movsbl	1(%ecx),%eax\n"
"	movl	(%edi,%eax,4), %eax\n"
"	testl	%eax, %eax\n"
"	jne	LB108\n"
"LB134:\n"
"	movl	$1, %eax\n"
"	movl	%esi, %ecx\n"
"	sall	%cl, %eax\n"
"	xorl	%edi, %edi\n"
"	decl	%eax\n"
"	cmpl	%edx, %edi\n"
"	movl	%eax, xxall\n"
"	jge	LB136\n"
"	movl	$0, -20(%ebp)\n"
"	movl	$xxpatch+4, -24(%ebp)\n"
"	.p2align 4,,15\n"
"LB122:\n"
"	movsbl	(%ebx),%eax\n"
"	movl	%ebx, %ecx\n"
"	movl	xxisdig(,%eax,4), %eax\n"
"	testl	%eax, %eax\n"
"	jne	LB138\n"
"	movl	$xxisdig, %esi\n"
"	leal	1(%ebx), %edx\n"
"	.p2align 4,,15\n"
"LB116:\n"
"	movl	%edx, xxinp\n"
"	movl	%edx, %ebx\n"
"	leal	2(%ecx), %edx\n"
"	movsbl	-1(%edx),%eax\n"
"	movl	%ebx, %ecx\n"
"	movl	(%esi,%eax,4), %eax\n"
"	testl	%eax, %eax\n"
"	je	LB116\n"
"LB138:\n"
"	movsbl	(%ebx),%edx\n"
"	movl	%ebx, %eax\n"
"	movl	-24(%ebp), %ecx\n"
"	incl	%ebx\n"
"	movl	%ebx, xxinp\n"
"	subl	$48, %edx\n"
"	movl	%edx, 16(%ecx)\n"
"	movsbl	1(%eax),%eax\n"
"	movl	xxisdig(,%eax,4), %eax\n"
"	testl	%eax, %eax\n"
"	je	LB140\n"
"	movl	%ecx, %esi\n"
"	.p2align 4,,15\n"
"LB121:\n"
"	movsbl	(%ebx),%edx\n"
"	movl	%ebx, %ecx\n"
"	movl	16(%esi), %eax\n"
"	incl	%ebx\n"
"	movl	%ebx, xxinp\n"
"	leal	(%eax,%eax,4), %eax\n"
"	leal	-48(%edx,%eax,2), %eax\n"
"	movl	%eax, 16(%esi)\n"
"	movsbl	1(%ecx),%eax\n"
"	movl	xxisdig(,%eax,4), %eax\n"
"	testl	%eax, %eax\n"
"	jne	LB121\n"
"LB140:\n"
"	movl	-20(%ebp), %eax\n"
"	incl	%edi\n"
"	movl	-24(%ebp), %ebx\n"
"	addl	$xxpatch, %eax\n"
"	movl	%ebx, 4(%esp)\n"
"	movl	%eax, (%esp)\n"
"	call	xxtake\n"
"	movl	(%ebx), %esi\n"
"	movl	-4(%ebx), %edx\n"
"	movl	-20(%ebp), %ecx\n"
"	movl	%edx, 24(%ebx)\n"
"	movl	%edx, %eax\n"
"	orl	%esi, %eax\n"
"	movl	%eax, 20(%ebx)\n"
"	movl	-20(%ebp), %eax\n"
"	addl	$xxpatch+8, %ecx\n"
"	movl	%ecx, (%esp)\n"
"	addl	$xxpatch+12, %eax\n"
"	movl	%eax, 4(%esp)\n"
"	call	xxtake\n"
"	movl	8(%ebx), %edx\n"
"	movl	xxall, %eax\n"
"	addl	$32, -20(%ebp)\n"
"	xorl	%edx, %eax\n"
"	movl	%eax, 12(%ebx)\n"
"	addl	$32, %ebx\n"
"	cmpl	m, %edi\n"
"	movl	%ebx, -24(%ebp)\n"
"	jge	LB136\n"
"	movl	xxinp, %ebx\n"
"	jmp	LB122\n"
"LB136:\n"
"	movl	$LBC0, (%esp)\n"
"	movl	-16(%ebp), %eax\n"
"	movl	%eax, 4(%esp)\n"
"	call	printf\n"
"	call	xxsolve\n"
"	testl	%eax, %eax\n"
"	js	LB144\n"
"	movl	%eax, 4(%esp)\n"
"	movl	$LBC2, (%esp)\n"
"	call	printf\n"
"LB89:\n"
"	incl	-16(%ebp)\n"
"	jmp	LB87\n"
"LB144:\n"
"	movl	$LBC1, (%esp)\n"
"	call	printf\n"
"	jmp	LB89\n"
"LB142:\n"
"	movl	m, %edx\n"
"	jmp	LB134\n"
"LB141:\n"
"	movl	n, %esi\n"
"	jmp	LB130\n"
"LB88:\n"
"	movl	$0, (%esp)\n"
"	call	exit\n"
"	.comm	inbuf,1048576\n"
"	.comm	xxinp,4\n"
"	.comm	xxisdig,1024\n"
"	.comm	xxdist,4194304\n"
"	.comm	xxrank,4194304\n"
"	.comm	xxheap,4194320\n"
"	.comm	xxheap_n,4\n"
"	.comm	n,4\n"
"	.comm	m,4\n"
"	.comm	xxall,4\n"
"	.comm	xxpatch,4096\n"
);
}

int main()
{
	go();
	return 0;
}
