int main()
{
__asm__ __volatile__(
"	pushl	%ebp\n"
"	movl	%esp, %ebp\n"
"	pushl	%edi\n"
"	pushl	%esi\n"
"	pushl	%ebx\n"
"	subl	$60, %esp\n"
"	movl	$2, %ecx\n"
"L12:\n"
"	movl	_sieve.1(,%ecx,4), %edx\n"
"	testl	%edx, %edx\n"
"	jne	L4\n"
"	movl	%ecx, %ebx\n"
"	imull	%ecx, %ebx\n"
"	cmpl	$3164, %ebx\n"
"	jg	L4\n"
"L11:\n"
"	movl	$1, %edx\n"
"	movl	%edx, _sieve.1(,%ebx,4)\n"
"	addl	%ecx, %ebx\n"
"	cmpl	$3164, %ebx\n"
"	jle	L11\n"
"L4:\n"
"	incl	%ecx\n"
"	cmpl	$57, %ecx\n"
"	jle	L12\n"
"	movl	$2, %ecx\n"
"	movl	%ecx, _prime.2\n"
"	movl	$1, %ebx\n"
"	movl	$3, %ecx\n"
"	.p2align 4,,15\n"
"L18:\n"
"	movl	_sieve.1(,%ecx,4), %esi\n"
"	testl	%esi, %esi\n"
"	jne	L15\n"
"	movl	%ecx, _prime.2(,%ebx,4)\n"
"	incl	%ebx\n"
"L15:\n"
"	addl	$2, %ecx\n"
"	cmpl	$3164, %ecx\n"
"	jle	L18\n"
"	movl	$48, %ecx\n"
"L23:\n"
"	movl	$1, %ebx\n"
"	movl	%ebx, _isdig.0(,%ecx,4)\n"
"	incl	%ecx\n"
"	cmpl	$57, %ecx\n"
"	jle	L23\n"
"	movl	$1048576, %ecx\n"
"	movl	%ecx, 8(%esp)\n"
"	movl	$_inbuf.3, -20(%ebp)\n"
"	movl	$_inbuf.3, %eax\n"
"	movl	%eax, 4(%esp)\n"
"	movl	$0, (%esp)\n"
"	call	read\n"
"	movl	$_outbuf.4, -24(%ebp)\n"
"	movsbl	_inbuf.3,%edx\n"
"	movl	_isdig.0(,%edx,4), %edi\n"
"	testl	%edi, %edi\n"
"	jne	L258\n"
"L27:\n"
"	incl	-20(%ebp)\n"
"	movl	-20(%ebp), %edi\n"
"	movzbl	(%edi), %edx\n"
"	movsbl	%dl,%ebx\n"
"	movl	_isdig.0(,%ebx,4), %esi\n"
"	testl	%esi, %esi\n"
"	je	L27\n"
"L191:\n"
"	movsbl	%dl,%ecx\n"
"	subl	$48, %ecx\n"
"	movl	%ecx, -32(%ebp)\n"
"	incl	-20(%ebp)\n"
"	movl	-20(%ebp), %eax\n"
"	movzbl	(%eax), %edx\n"
"	movsbl	%dl,%eax\n"
"	movl	_isdig.0(,%eax,4), %esi\n"
"	testl	%esi, %esi\n"
"	je	L193\n"
"	movl	%eax, %ecx\n"
"L32:\n"
"	movl	-32(%ebp), %eax\n"
"	leal	(%eax,%eax,4), %edi\n"
"	leal	-48(%ecx,%edi,2), %edx\n"
"	movl	%edx, -32(%ebp)\n"
"	incl	-20(%ebp)\n"
"	movl	-20(%ebp), %esi\n"
"	movzbl	(%esi), %edx\n"
"	movsbl	%dl,%edi\n"
"	movl	%edi, %ecx\n"
"	movl	_isdig.0(,%edi,4), %ebx\n"
"	testl	%ebx, %ebx\n"
"	jne	L32\n"
"L193:\n"
"	movl	$1, -28(%ebp)\n"
"	movl	-32(%ebp), %ebx\n"
"	cmpl	%ebx, -28(%ebp)\n"
"	jg	L195\n"
"L182:\n"
"	movsbl	%dl,%edi\n"
"	movl	_isdig.0(,%edi,4), %esi\n"
"	testl	%esi, %esi\n"
"	jne	L197\n"
"L40:\n"
"	incl	-20(%ebp)\n"
"	movl	-20(%ebp), %esi\n"
"	movzbl	(%esi), %edx\n"
"	movsbl	%dl,%ecx\n"
"	movl	_isdig.0(,%ecx,4), %ebx\n"
"	testl	%ebx, %ebx\n"
"	je	L40\n"
"L197:\n"
"	movsbl	%dl,%ecx\n"
"	leal	-48(%ecx), %edi\n"
"	incl	-20(%ebp)\n"
"	movl	-20(%ebp), %ebx\n"
"	movsbl	(%ebx),%eax\n"
"	movl	_isdig.0(,%eax,4), %edx\n"
"	testl	%edx, %edx\n"
"	je	L199\n"
"	movl	%eax, %edx\n"
"L45:\n"
"	leal	(%edi,%edi,4), %ebx\n"
"	leal	-48(%edx,%ebx,2), %edi\n"
"	incl	-20(%ebp)\n"
"	movl	-20(%ebp), %edx\n"
"	movsbl	(%edx),%esi\n"
"	movl	%esi, %edx\n"
"	movl	_isdig.0(,%esi,4), %eax\n"
"	testl	%eax, %eax\n"
"	jne	L45\n"
"L199:\n"
"	movl	-24(%ebp), %ecx\n"
"	movb	$67, (%ecx)\n"
"	incl	%ecx\n"
"	movb	$97, (%ecx)\n"
"	incl	%ecx\n"
"	movb	$115, (%ecx)\n"
"	incl	%ecx\n"
"	movb	$101, (%ecx)\n"
"	incl	%ecx\n"
"	movb	$32, (%ecx)\n"
"	incl	%ecx\n"
"	movb	$35, (%ecx)\n"
"	incl	%ecx\n"
"	movl	%ecx, -24(%ebp)\n"
"	movl	-28(%ebp), %ecx\n"
"	movl	$_tmp.5, %esi\n"
"	testl	%ecx, %ecx\n"
"	jle	L201\n"
"	movl	$1717986919, %ebx\n"
"L50:\n"
"	movl	%ecx, %eax\n"
"	imull	%ebx\n"
"	movl	%eax, -56(%ebp)\n"
"	movl	%edx, -52(%ebp)\n"
"	movl	-52(%ebp), %edx\n"
"	sarl	$2, %edx\n"
"	movl	%ecx, %eax\n"
"	sarl	$31, %eax\n"
"	subl	%eax, %edx\n"
"	leal	(%edx,%edx,4), %eax\n"
"	addl	%eax, %eax\n"
"	subl	%eax, %ecx\n"
"	movb	%cl, %al\n"
"	addb	$48, %al\n"
"	movb	%al, (%esi)\n"
"	incl	%esi\n"
"	movl	%edx, %ecx\n"
"	testl	%edx, %edx\n"
"	jg	L50\n"
"L201:\n"
"	decl	%esi\n"
"	cmpl	$_tmp.5-1, %esi\n"
"	jbe	L203\n"
"L54:\n"
"	movzbl	(%esi), %edx\n"
"	movl	-24(%ebp), %ebx\n"
"	movb	%dl, (%ebx)\n"
"	incl	%ebx\n"
"	movl	%ebx, -24(%ebp)\n"
"	decl	%esi\n"
"	cmpl	$_tmp.5-1, %esi\n"
"	ja	L54\n"
"L203:\n"
"	movl	-24(%ebp), %eax\n"
"	movb	$58, (%eax)\n"
"	incl	%eax\n"
"	movb	$32, (%eax)\n"
"	incl	%eax\n"
"	movl	%eax, -24(%ebp)\n"
"	testl	$3, %edi\n"
"	jne	L55\n"
"	movl	%edi, %ecx\n"
"	movl	$_tmp.5, %esi\n"
"	testl	%edi, %edi\n"
"	jle	L205\n"
"	movl	$1717986919, %ebx\n"
"L60:\n"
"	movl	%ecx, %eax\n"
"	imull	%ebx\n"
"	sarl	$2, %edx\n"
"	movl	%ecx, %eax\n"
"	sarl	$31, %eax\n"
"	subl	%eax, %edx\n"
"	leal	(%edx,%edx,4), %eax\n"
"	addl	%eax, %eax\n"
"	subl	%eax, %ecx\n"
"	movb	%cl, %al\n"
"	addb	$48, %al\n"
"	movb	%al, (%esi)\n"
"	incl	%esi\n"
"	movl	%edx, %ecx\n"
"	testl	%edx, %edx\n"
"	jg	L60\n"
"L205:\n"
"	decl	%esi\n"
"	cmpl	$_tmp.5-1, %esi\n"
"	jbe	L207\n"
"L64:\n"
"	movzbl	(%esi), %ebx\n"
"	movl	-24(%ebp), %ecx\n"
"	movb	%bl, (%ecx)\n"
"	incl	%ecx\n"
"	movl	%ecx, -24(%ebp)\n"
"	decl	%esi\n"
"	cmpl	$_tmp.5-1, %esi\n"
"	ja	L64\n"
"L207:\n"
"	movl	-24(%ebp), %esi\n"
"	movb	$32, (%esi)\n"
"	incl	%esi\n"
"	movb	$61, (%esi)\n"
"	incl	%esi\n"
"	movb	$32, (%esi)\n"
"	incl	%esi\n"
"	movb	$50, (%esi)\n"
"	incl	%esi\n"
"	movb	$32, (%esi)\n"
"	incl	%esi\n"
"	movb	$42, (%esi)\n"
"	incl	%esi\n"
"	movb	$32, (%esi)\n"
"	incl	%esi\n"
"	movl	%esi, -24(%ebp)\n"
"	movl	%edi, %ecx\n"
"	sarl	%ecx\n"
"	movl	$_tmp.5, %esi\n"
"	testl	%ecx, %ecx\n"
"	jle	L209\n"
"	movl	$1717986919, %ebx\n"
"L69:\n"
"	movl	%ecx, %eax\n"
"	imull	%ebx\n"
"	sarl	$2, %edx\n"
"	movl	%ecx, %eax\n"
"	sarl	$31, %eax\n"
"	subl	%eax, %edx\n"
"	leal	(%edx,%edx,4), %eax\n"
"	addl	%eax, %eax\n"
"	subl	%eax, %ecx\n"
"	movb	%cl, %al\n"
"	addb	$48, %al\n"
"	movb	%al, (%esi)\n"
"	incl	%esi\n"
"	movl	%edx, %ecx\n"
"	testl	%edx, %edx\n"
"	jg	L69\n"
"L209:\n"
"	decl	%esi\n"
"	cmpl	$_tmp.5-1, %esi\n"
"	jbe	L211\n"
"L73:\n"
"	movzbl	(%esi), %edx\n"
"	movl	-24(%ebp), %ecx\n"
"	movb	%dl, (%ecx)\n"
"	incl	%ecx\n"
"	movl	%ecx, -24(%ebp)\n"
"	decl	%esi\n"
"	cmpl	$_tmp.5-1, %esi\n"
"	ja	L73\n"
"L211:\n"
"	movl	-24(%ebp), %eax\n"
"	movb	$32, (%eax)\n"
"	incl	%eax\n"
"	movb	$61, (%eax)\n"
"	incl	%eax\n"
"	movb	$32, (%eax)\n"
"	incl	%eax\n"
"	movb	$52, (%eax)\n"
"	incl	%eax\n"
"	movb	$32, (%eax)\n"
"	incl	%eax\n"
"	movb	$42, (%eax)\n"
"	incl	%eax\n"
"	movb	$32, (%eax)\n"
"	incl	%eax\n"
"	movl	%eax, -24(%ebp)\n"
"	movl	%edi, %ecx\n"
"	sarl	$2, %ecx\n"
"	movl	$_tmp.5, %esi\n"
"	testl	%ecx, %ecx\n"
"	jle	L213\n"
"	movl	$1717986919, %ebx\n"
"L78:\n"
"	movl	%ecx, %eax\n"
"	imull	%ebx\n"
"	sarl	$2, %edx\n"
"	movl	%ecx, %edi\n"
"	sarl	$31, %edi\n"
"	subl	%edi, %edx\n"
"	leal	(%edx,%edx,4), %edi\n"
"	addl	%edi, %edi\n"
"	subl	%edi, %ecx\n"
"	movb	%cl, %al\n"
"	addb	$48, %al\n"
"	movb	%al, (%esi)\n"
"	incl	%esi\n"
"	movl	%edx, %ecx\n"
"	testl	%edx, %edx\n"
"	jg	L78\n"
"L213:\n"
"	decl	%esi\n"
"	cmpl	$_tmp.5-1, %esi\n"
"	jbe	L257\n"
"L82:\n"
"	movzbl	(%esi), %ecx\n"
"	movl	-24(%ebp), %ebx\n"
"	movb	%cl, (%ebx)\n"
"	incl	%ebx\n"
"	movl	%ebx, -24(%ebp)\n"
"	decl	%esi\n"
"	cmpl	$_tmp.5-1, %esi\n"
"	ja	L82\n"
"L257:\n"
"	movl	-24(%ebp), %eax\n"
"	movb	$10, (%eax)\n"
"	incl	%eax\n"
"	movl	%eax, -24(%ebp)\n"
"	incl	-28(%ebp)\n"
"	movl	-32(%ebp), %esi\n"
"	cmpl	%esi, -28(%ebp)\n"
"	jg	L195\n"
"	movl	-20(%ebp), %ecx\n"
"	movzbl	(%ecx), %edx\n"
"	jmp	L182\n"
"L55:\n"
"	testl	$1, %edi\n"
"	jne	L84\n"
"	movl	%edi, %esi\n"
"	sarl	%esi\n"
"	movl	%esi, -36(%ebp)\n"
"	movl	$1, %ebx\n"
"	movl	-36(%ebp), %eax\n"
"	cltd\n"
"	idivl	_prime.2+4\n"
"	testl	%edx, %edx\n"
"	je	L217\n"
"L89:\n"
"	incl	%ebx\n"
"	movl	-36(%ebp), %eax\n"
"	cltd\n"
"	idivl	_prime.2(,%ebx,4)\n"
"	testl	%edx, %edx\n"
"	jne	L89\n"
"L217:\n"
"	movl	%edi, %ecx\n"
"	movl	$_tmp.5, %esi\n"
"	testl	%edi, %edi\n"
"	jle	L219\n"
"	movl	$1717986919, %edi\n"
"L94:\n"
"	movl	%ecx, %eax\n"
"	imull	%edi\n"
"	movl	%eax, -56(%ebp)\n"
"	movl	%edx, -52(%ebp)\n"
"	movl	-52(%ebp), %edx\n"
"	sarl	$2, %edx\n"
"	movl	%ecx, %eax\n"
"	sarl	$31, %eax\n"
"	subl	%eax, %edx\n"
"	leal	(%edx,%edx,4), %eax\n"
"	addl	%eax, %eax\n"
"	subl	%eax, %ecx\n"
"	movb	%cl, %al\n"
"	addb	$48, %al\n"
"	movb	%al, (%esi)\n"
"	incl	%esi\n"
"	movl	%edx, %ecx\n"
"	testl	%edx, %edx\n"
"	jg	L94\n"
"L219:\n"
"	decl	%esi\n"
"	cmpl	$_tmp.5-1, %esi\n"
"	jbe	L221\n"
"L98:\n"
"	movzbl	(%esi), %edx\n"
"	movl	-24(%ebp), %edi\n"
"	movb	%dl, (%edi)\n"
"	incl	%edi\n"
"	movl	%edi, -24(%ebp)\n"
"	decl	%esi\n"
"	cmpl	$_tmp.5-1, %esi\n"
"	ja	L98\n"
"L221:\n"
"	movl	-24(%ebp), %eax\n"
"	movb	$32, (%eax)\n"
"	incl	%eax\n"
"	movb	$61, (%eax)\n"
"	incl	%eax\n"
"	movb	$32, (%eax)\n"
"	incl	%eax\n"
"	movb	$50, (%eax)\n"
"	incl	%eax\n"
"	movb	$32, (%eax)\n"
"	incl	%eax\n"
"	movb	$42, (%eax)\n"
"	incl	%eax\n"
"	movb	$32, (%eax)\n"
"	incl	%eax\n"
"	movl	%eax, -24(%ebp)\n"
"	movl	-36(%ebp), %ecx\n"
"	movl	$_tmp.5, %esi\n"
"	testl	%ecx, %ecx\n"
"	jle	L223\n"
"	movl	$1717986919, %edi\n"
"L103:\n"
"	movl	%ecx, %eax\n"
"	imull	%edi\n"
"	sarl	$2, %edx\n"
"	movl	%ecx, %eax\n"
"	sarl	$31, %eax\n"
"	subl	%eax, %edx\n"
"	leal	(%edx,%edx,4), %eax\n"
"	addl	%eax, %eax\n"
"	subl	%eax, %ecx\n"
"	movb	%cl, %al\n"
"	addb	$48, %al\n"
"	movb	%al, (%esi)\n"
"	incl	%esi\n"
"	movl	%edx, %ecx\n"
"	testl	%edx, %edx\n"
"	jg	L103\n"
"L223:\n"
"	decl	%esi\n"
"	cmpl	$_tmp.5-1, %esi\n"
"	jbe	L225\n"
"L107:\n"
"	movzbl	(%esi), %edx\n"
"	movl	-24(%ebp), %ecx\n"
"	movb	%dl, (%ecx)\n"
"	incl	%ecx\n"
"	movl	%ecx, -24(%ebp)\n"
"	decl	%esi\n"
"	cmpl	$_tmp.5-1, %esi\n"
"	ja	L107\n"
"L225:\n"
"	movl	-24(%ebp), %esi\n"
"	movb	$32, (%esi)\n"
"	incl	%esi\n"
"	movb	$61, (%esi)\n"
"	incl	%esi\n"
"	movb	$32, (%esi)\n"
"	incl	%esi\n"
"	movl	%esi, -24(%ebp)\n"
"	movl	_prime.2(,%ebx,4), %edx\n"
"	leal	(%edx,%edx), %ecx\n"
"	movl	$_tmp.5, %esi\n"
"	testl	%ecx, %ecx\n"
"	jle	L227\n"
"	movl	$1717986919, %edi\n"
"L112:\n"
"	movl	%ecx, %eax\n"
"	imull	%edi\n"
"	sarl	$2, %edx\n"
"	movl	%ecx, %eax\n"
"	sarl	$31, %eax\n"
"	subl	%eax, %edx\n"
"	leal	(%edx,%edx,4), %eax\n"
"	addl	%eax, %eax\n"
"	subl	%eax, %ecx\n"
"	movb	%cl, %al\n"
"	addb	$48, %al\n"
"	movb	%al, (%esi)\n"
"	incl	%esi\n"
"	movl	%edx, %ecx\n"
"	testl	%edx, %edx\n"
"	jg	L112\n"
"	movl	_prime.2(,%ebx,4), %edx\n"
"L227:\n"
"	decl	%esi\n"
"	cmpl	$_tmp.5-1, %esi\n"
"	jbe	L229\n"
"L116:\n"
"	movzbl	(%esi), %ecx\n"
"	movl	-24(%ebp), %ebx\n"
"	movb	%cl, (%ebx)\n"
"	incl	%ebx\n"
"	movl	%ebx, -24(%ebp)\n"
"	decl	%esi\n"
"	cmpl	$_tmp.5-1, %esi\n"
"	ja	L116\n"
"L229:\n"
"	movl	-24(%ebp), %eax\n"
"	movb	$32, (%eax)\n"
"	incl	%eax\n"
"	movb	$42, (%eax)\n"
"	incl	%eax\n"
"	movb	$32, (%eax)\n"
"	incl	%eax\n"
"	movl	%eax, -24(%ebp)\n"
"	movl	-36(%ebp), %eax\n"
"	movl	%edx, %edi\n"
"	cltd\n"
"	idivl	%edi\n"
"	movl	%eax, %ecx\n"
"	movl	$_tmp.5, %esi\n"
"	testl	%eax, %eax\n"
"	jle	L231\n"
"	movl	$1717986919, %ebx\n"
"L121:\n"
"	movl	%ecx, %eax\n"
"	imull	%ebx\n"
"	movl	%eax, -56(%ebp)\n"
"	movl	%edx, -52(%ebp)\n"
"	movl	-52(%ebp), %edi\n"
"	sarl	$2, %edi\n"
"	movl	%ecx, %edx\n"
"	sarl	$31, %edx\n"
"	subl	%edx, %edi\n"
"	leal	(%edi,%edi,4), %edx\n"
"	addl	%edx, %edx\n"
"	subl	%edx, %ecx\n"
"	movb	%cl, %dl\n"
"	addb	$48, %dl\n"
"	movb	%dl, (%esi)\n"
"	incl	%esi\n"
"	movl	%edi, %ecx\n"
"	testl	%edi, %edi\n"
"	jg	L121\n"
"L231:\n"
"	decl	%esi\n"
"	cmpl	$_tmp.5-1, %esi\n"
"	jbe	L257\n"
"L125:\n"
"	movzbl	(%esi), %ecx\n"
"	movl	-24(%ebp), %ebx\n"
"	movb	%cl, (%ebx)\n"
"	incl	%ebx\n"
"	movl	%ebx, -24(%ebp)\n"
"	decl	%esi\n"
"	cmpl	$_tmp.5-1, %esi\n"
"	ja	L125\n"
"	jmp	L257\n"
"L84:\n"
"	movl	$1, %ecx\n"
"	movl	%edi, %eax\n"
"	cltd\n"
"	idivl	_prime.2+4\n"
"	testl	%edx, %edx\n"
"	je	L260\n"
"L131:\n"
"	incl	%ecx\n"
"	movl	_prime.2(,%ecx,4), %esi\n"
"	movl	%esi, -44(%ebp)\n"
"	movl	%edi, %eax\n"
"	cltd\n"
"	idivl	-44(%ebp)\n"
"	testl	%edx, %edx\n"
"	jne	L131\n"
"L235:\n"
"	movl	%edi, %eax\n"
"	cltd\n"
"	idivl	-44(%ebp)\n"
"	movl	%eax, -40(%ebp)\n"
"	movl	%ecx, %ebx\n"
"	cltd\n"
"	idivl	-44(%ebp)\n"
"	testl	%edx, %edx\n"
"	je	L237\n"
"L136:\n"
"	incl	%ebx\n"
"	movl	-40(%ebp), %eax\n"
"	cltd\n"
"	idivl	_prime.2(,%ebx,4)\n"
"	testl	%edx, %edx\n"
"	jne	L136\n"
"L237:\n"
"	movl	$_tmp.5, %esi\n"
"	testl	%edi, %edi\n"
"	jle	L239\n"
"L141:\n"
"	movl	$1717986919, %eax\n"
"	imull	%edi\n"
"	movl	%eax, -56(%ebp)\n"
"	movl	%edx, -52(%ebp)\n"
"	movl	-52(%ebp), %edx\n"
"	sarl	$2, %edx\n"
"	movl	%edi, %eax\n"
"	sarl	$31, %eax\n"
"	subl	%eax, %edx\n"
"	leal	(%edx,%edx,4), %eax\n"
"	addl	%eax, %eax\n"
"	subl	%eax, %edi\n"
"	movl	%edi, %eax\n"
"	addb	$48, %al\n"
"	movb	%al, (%esi)\n"
"	incl	%esi\n"
"	movl	%edx, %edi\n"
"	testl	%edx, %edx\n"
"	jg	L141\n"
"	movl	_prime.2(,%ecx,4), %edi\n"
"	movl	%edi, -44(%ebp)\n"
"L239:\n"
"	decl	%esi\n"
"	cmpl	$_tmp.5-1, %esi\n"
"	jbe	L241\n"
"L145:\n"
"	movzbl	(%esi), %edx\n"
"	movl	-24(%ebp), %edi\n"
"	movb	%dl, (%edi)\n"
"	incl	%edi\n"
"	movl	%edi, -24(%ebp)\n"
"	decl	%esi\n"
"	cmpl	$_tmp.5-1, %esi\n"
"	ja	L145\n"
"L241:\n"
"	movl	-24(%ebp), %esi\n"
"	movb	$32, (%esi)\n"
"	incl	%esi\n"
"	movb	$61, (%esi)\n"
"	incl	%esi\n"
"	movb	$32, (%esi)\n"
"	incl	%esi\n"
"	movl	%esi, -24(%ebp)\n"
"	movl	-44(%ebp), %edi\n"
"	movl	$_tmp.5, %esi\n"
"	testl	%edi, %edi\n"
"	jle	L243\n"
"L150:\n"
"	movl	$1717986919, %eax\n"
"	imull	%edi\n"
"	sarl	$2, %edx\n"
"	movl	%edi, %eax\n"
"	sarl	$31, %eax\n"
"	subl	%eax, %edx\n"
"	leal	(%edx,%edx,4), %eax\n"
"	addl	%eax, %eax\n"
"	subl	%eax, %edi\n"
"	movl	%edi, %eax\n"
"	addb	$48, %al\n"
"	movb	%al, (%esi)\n"
"	incl	%esi\n"
"	movl	%edx, %edi\n"
"	testl	%edx, %edx\n"
"	jg	L150\n"
"L243:\n"
"	decl	%esi\n"
"	cmpl	$_tmp.5-1, %esi\n"
"	jbe	L245\n"
"L154:\n"
"	movzbl	(%esi), %edx\n"
"	movl	-24(%ebp), %edi\n"
"	movb	%dl, (%edi)\n"
"	incl	%edi\n"
"	movl	%edi, -24(%ebp)\n"
"	decl	%esi\n"
"	cmpl	$_tmp.5-1, %esi\n"
"	ja	L154\n"
"L245:\n"
"	movl	-24(%ebp), %esi\n"
"	movb	$32, (%esi)\n"
"	incl	%esi\n"
"	movb	$42, (%esi)\n"
"	incl	%esi\n"
"	movb	$32, (%esi)\n"
"	incl	%esi\n"
"	movl	%esi, -24(%ebp)\n"
"	movl	-40(%ebp), %edi\n"
"	movl	$_tmp.5, %esi\n"
"	testl	%edi, %edi\n"
"	jle	L247\n"
"L159:\n"
"	movl	$1717986919, %eax\n"
"	imull	%edi\n"
"	sarl	$2, %edx\n"
"	movl	%edi, %eax\n"
"	sarl	$31, %eax\n"
"	subl	%eax, %edx\n"
"	leal	(%edx,%edx,4), %eax\n"
"	addl	%eax, %eax\n"
"	subl	%eax, %edi\n"
"	movl	%edi, %eax\n"
"	addb	$48, %al\n"
"	movb	%al, (%esi)\n"
"	incl	%esi\n"
"	movl	%edx, %edi\n"
"	testl	%edx, %edx\n"
"	jg	L159\n"
"L247:\n"
"	decl	%esi\n"
"	cmpl	$_tmp.5-1, %esi\n"
"	jbe	L249\n"
"L163:\n"
"	movzbl	(%esi), %edx\n"
"	movl	-24(%ebp), %edi\n"
"	movb	%dl, (%edi)\n"
"	incl	%edi\n"
"	movl	%edi, -24(%ebp)\n"
"	decl	%esi\n"
"	cmpl	$_tmp.5-1, %esi\n"
"	ja	L163\n"
"L249:\n"
"	movl	-24(%ebp), %esi\n"
"	movb	$32, (%esi)\n"
"	incl	%esi\n"
"	movb	$61, (%esi)\n"
"	incl	%esi\n"
"	movb	$32, (%esi)\n"
"	incl	%esi\n"
"	movl	%esi, -24(%ebp)\n"
"	movl	_prime.2(,%ebx,4), %edx\n"
"	movl	_prime.2(,%ecx,4), %ecx\n"
"	imull	%edx, %ecx\n"
"	movl	$_tmp.5, %esi\n"
"	testl	%ecx, %ecx\n"
"	jle	L251\n"
"	movl	$1717986919, %edi\n"
"L168:\n"
"	movl	%ecx, %eax\n"
"	imull	%edi\n"
"	sarl	$2, %edx\n"
"	movl	%ecx, %eax\n"
"	sarl	$31, %eax\n"
"	subl	%eax, %edx\n"
"	leal	(%edx,%edx,4), %eax\n"
"	addl	%eax, %eax\n"
"	subl	%eax, %ecx\n"
"	movb	%cl, %al\n"
"	addb	$48, %al\n"
"	movb	%al, (%esi)\n"
"	incl	%esi\n"
"	movl	%edx, %ecx\n"
"	testl	%edx, %edx\n"
"	jg	L168\n"
"	movl	_prime.2(,%ebx,4), %edx\n"
"L251:\n"
"	decl	%esi\n"
"	cmpl	$_tmp.5-1, %esi\n"
"	jbe	L253\n"
"L172:\n"
"	movzbl	(%esi), %ecx\n"
"	movl	-24(%ebp), %ebx\n"
"	movb	%cl, (%ebx)\n"
"	incl	%ebx\n"
"	movl	%ebx, -24(%ebp)\n"
"	decl	%esi\n"
"	cmpl	$_tmp.5-1, %esi\n"
"	ja	L172\n"
"L253:\n"
"	movl	-24(%ebp), %eax\n"
"	movb	$32, (%eax)\n"
"	incl	%eax\n"
"	movb	$42, (%eax)\n"
"	incl	%eax\n"
"	movb	$32, (%eax)\n"
"	incl	%eax\n"
"	movl	%eax, -24(%ebp)\n"
"	movl	-40(%ebp), %eax\n"
"	movl	%edx, %edi\n"
"	cltd\n"
"	idivl	%edi\n"
"	movl	%eax, %ecx\n"
"	movl	$_tmp.5, %esi\n"
"	testl	%eax, %eax\n"
"	jle	L255\n"
"	movl	$1717986919, %ebx\n"
"L177:\n"
"	movl	%ecx, %eax\n"
"	imull	%ebx\n"
"	movl	%eax, -56(%ebp)\n"
"	movl	%edx, -52(%ebp)\n"
"	movl	-52(%ebp), %edi\n"
"	sarl	$2, %edi\n"
"	movl	%ecx, %edx\n"
"	sarl	$31, %edx\n"
"	subl	%edx, %edi\n"
"	leal	(%edi,%edi,4), %edx\n"
"	addl	%edx, %edx\n"
"	subl	%edx, %ecx\n"
"	movb	%cl, %dl\n"
"	addb	$48, %dl\n"
"	movb	%dl, (%esi)\n"
"	incl	%esi\n"
"	movl	%edi, %ecx\n"
"	testl	%edi, %edi\n"
"	jg	L177\n"
"L255:\n"
"	decl	%esi\n"
"	cmpl	$_tmp.5-1, %esi\n"
"	jbe	L257\n"
"L181:\n"
"	movzbl	(%esi), %ecx\n"
"	movl	-24(%ebp), %ebx\n"
"	movb	%cl, (%ebx)\n"
"	incl	%ebx\n"
"	movl	%ebx, -24(%ebp)\n"
"	decl	%esi\n"
"	cmpl	$_tmp.5-1, %esi\n"
"	ja	L181\n"
"	jmp	L257\n"
"L260:\n"
"	movl	_prime.2+4, %eax\n"
"	movl	%eax, -44(%ebp)\n"
"	jmp	L235\n"
"L258:\n"
"	movzbl	_inbuf.3, %edx\n"
"	jmp	L191\n"
"L195:\n"
"	subl	$_outbuf.4, -24(%ebp)\n"
"	movl	-24(%ebp), %edx\n"
"	movl	%edx, 8(%esp)\n"
"	movl	$_outbuf.4, %edi\n"
"	movl	%edi, 4(%esp)\n"
"	movl	$1, (%esp)\n"
"	call	write\n"
"	movl	$0, (%esp)\n"
"	call	exit\n"
"	.p2align 4,,15\n"
".lcomm _tmp.5,256\n"
".lcomm _isdig.0,1024\n"
".lcomm _sieve.1,16000\n"
".lcomm _prime.2,16000\n"
".lcomm _inbuf.3,1048576\n"
".lcomm _outbuf.4,1048576\n"
);
}
