int main()
{
__asm__ __volatile__(
"	jmp	_main2\n"
"	.align 32\n"
"_sym:\n"
"	.long	0\n"
"	.long	1\n"
"	.long	2\n"
"	.long	3\n"
"	.long	4\n"
"	.long	5\n"
"	.space 8\n"
"	.long	0\n"
"	.long	2\n"
"	.long	5\n"
"	.long	3\n"
"	.long	1\n"
"	.long	4\n"
"	.space 8\n"
"	.long	0\n"
"	.long	4\n"
"	.long	1\n"
"	.long	3\n"
"	.long	5\n"
"	.long	2\n"
"	.space 8\n"
"	.long	0\n"
"	.long	5\n"
"	.long	4\n"
"	.long	3\n"
"	.long	2\n"
"	.long	1\n"
"	.space 8\n"
"	.long	1\n"
"	.long	0\n"
"	.long	4\n"
"	.long	5\n"
"	.long	2\n"
"	.long	3\n"
"	.space 8\n"
"	.long	1\n"
"	.long	2\n"
"	.long	0\n"
"	.long	5\n"
"	.long	3\n"
"	.long	4\n"
"	.space 8\n"
"	.long	1\n"
"	.long	3\n"
"	.long	2\n"
"	.long	5\n"
"	.long	4\n"
"	.long	0\n"
"	.space 8\n"
"	.long	1\n"
"	.long	4\n"
"	.long	3\n"
"	.long	5\n"
"	.long	0\n"
"	.long	2\n"
"	.space 8\n"
"	.long	2\n"
"	.long	0\n"
"	.long	1\n"
"	.long	4\n"
"	.long	5\n"
"	.long	3\n"
"	.space 8\n"
"	.long	2\n"
"	.long	1\n"
"	.long	3\n"
"	.long	4\n"
"	.long	0\n"
"	.long	5\n"
"	.space 8\n"
"	.long	2\n"
"	.long	3\n"
"	.long	5\n"
"	.long	4\n"
"	.long	1\n"
"	.long	0\n"
"	.space 8\n"
"	.long	2\n"
"	.long	5\n"
"	.long	0\n"
"	.long	4\n"
"	.long	3\n"
"	.long	1\n"
"	.space 8\n"
"	.long	3\n"
"	.long	1\n"
"	.long	4\n"
"	.long	0\n"
"	.long	2\n"
"	.long	5\n"
"	.space 8\n"
"	.long	3\n"
"	.long	2\n"
"	.long	1\n"
"	.long	0\n"
"	.long	5\n"
"	.long	4\n"
"	.space 8\n"
"	.long	3\n"
"	.long	4\n"
"	.long	5\n"
"	.long	0\n"
"	.long	1\n"
"	.long	2\n"
"	.space 8\n"
"	.long	3\n"
"	.long	5\n"
"	.long	2\n"
"	.long	0\n"
"	.long	4\n"
"	.long	1\n"
"	.space 8\n"
"	.long	4\n"
"	.long	0\n"
"	.long	5\n"
"	.long	2\n"
"	.long	1\n"
"	.long	3\n"
"	.space 8\n"
"	.long	4\n"
"	.long	1\n"
"	.long	0\n"
"	.long	2\n"
"	.long	3\n"
"	.long	5\n"
"	.space 8\n"
"	.long	4\n"
"	.long	3\n"
"	.long	1\n"
"	.long	2\n"
"	.long	5\n"
"	.long	0\n"
"	.space 8\n"
"	.long	4\n"
"	.long	5\n"
"	.long	3\n"
"	.long	2\n"
"	.long	0\n"
"	.long	1\n"
"	.space 8\n"
"	.long	5\n"
"	.long	0\n"
"	.long	2\n"
"	.long	1\n"
"	.long	4\n"
"	.long	3\n"
"	.space 8\n"
"	.long	5\n"
"	.long	2\n"
"	.long	3\n"
"	.long	1\n"
"	.long	0\n"
"	.long	4\n"
"	.space 8\n"
"	.long	5\n"
"	.long	3\n"
"	.long	4\n"
"	.long	1\n"
"	.long	2\n"
"	.long	0\n"
"	.space 8\n"
"	.long	5\n"
"	.long	4\n"
"	.long	0\n"
"	.long	1\n"
"	.long	3\n"
"	.long	2\n"
"	.space 8\n"
"	.p2align 4,,15\n"
"_sort:\n"
"	pushl	%ebp\n"
"	movl	%esp, %ebp\n"
"	pushl	%edi\n"
"	pushl	%esi\n"
"	pushl	%ebx\n"
"	subl	$8, %esp\n"
"	movl	8(%ebp), %esi\n"
"L2:\n"
"	cmpl	$32, 12(%ebp)\n"
"	jle	L31\n"
"	movl	12(%ebp), %edx\n"
"	decl	%edx\n"
"	sarl	%edx\n"
"	movl	(%esi,%edx,4), %ecx\n"
"	movl	$-1, %edi\n"
"	movl	12(%ebp), %eax\n"
"	.p2align 4,,15\n"
"L30:\n"
"	incl	%edi\n"
"	movl	(%esi,%edi,4), %ebx\n"
"	cmpl	%ecx, %ebx\n"
"	jl	L30\n"
"	.p2align 4,,15\n"
"L21:\n"
"	decl	%eax\n"
"	movl	(%esi,%eax,4), %edx\n"
"	cmpl	%ecx, %edx\n"
"	jg	L21\n"
"	cmpl	%eax, %edi\n"
"	jge	L16\n"
"	movl	%edx, (%esi,%edi,4)\n"
"	movl	%ebx, (%esi,%eax,4)\n"
"	jmp	L30\n"
"L16:\n"
"	movl	12(%ebp), %eax\n"
"	subl	%edi, %eax\n"
"	cmpl	$1, %eax\n"
"	jg	L32\n"
"L25:\n"
"	movl	%edi, 12(%ebp)\n"
"	jmp	L2\n"
"L32:\n"
"	movl	%eax, 4(%esp)\n"
"	leal	(%esi,%edi,4), %edx\n"
"	movl	%edx, (%esp)\n"
"	call	_sort\n"
"	jmp	L25\n"
"L31:\n"
"	movl	$1, %edi\n"
"	cmpl	12(%ebp), %edi\n"
"	jge	L1\n"
"L14:\n"
"	movl	(%esi,%edi,4), %ecx\n"
"	movl	%edi, %eax\n"
"	decl	%eax\n"
"	js	L9\n"
"	movl	(%esi,%eax,4), %edx\n"
"	cmpl	%ecx, %edx\n"
"	jle	L9\n"
"L13:\n"
"	movl	%edx, 4(%esi,%eax,4)\n"
"	decl	%eax\n"
"	js	L9\n"
"	movl	(%esi,%eax,4), %edx\n"
"	cmpl	%ecx, %edx\n"
"	jg	L13\n"
"L9:\n"
"	movl	%ecx, 4(%esi,%eax,4)\n"
"	incl	%edi\n"
"	cmpl	12(%ebp), %edi\n"
"	jl	L14\n"
"L1:\n"
"	addl	$8, %esp\n"
"	popl	%ebx\n"
"	popl	%esi\n"
"	popl	%edi\n"
"	popl	%ebp\n"
"	ret\n"
"	.p2align 4,,15\n"
"_main2:\n"
"	pushl	%ebp\n"
"	movl	%esp, %ebp\n"
"	pushl	%edi\n"
"	pushl	%esi\n"
"	pushl	%ebx\n"
"	subl	$60, %esp\n"
"	movl	$48, -20(%ebp)\n"
"L38:\n"
"	movl	-20(%ebp), %edx\n"
"	movl	$1, %eax\n"
"	movl	%eax, _isdig.5(,%edx,4)\n"
"	incl	%edx\n"
"	movl	%edx, -20(%ebp)\n"
"	cmpl	$57, %edx\n"
"	jle	L38\n"
"	movl	$131072, %edx\n"
"	movl	%edx, 8(%esp)\n"
"	movl	$_inbuf.0, %edi\n"
"	movl	%edi, 4(%esp)\n"
"	movl	$0, (%esp)\n"
"	call	read\n"
"	movb	$0, _inbuf.0(%eax)\n"
"	movl	$_outbuf.1, -32(%ebp)\n"
"L39:\n"
"	movzbl	(%edi), %eax\n"
"	movb	%al, -33(%ebp)\n"
"	movsbl	%al,%ebx\n"
"	movl	_isdig.5(,%ebx,4), %ecx\n"
"	testl	%ecx, %ecx\n"
"	jne	L100\n"
"L45:\n"
"	incl	%edi\n"
"	movzbl	(%edi), %ebx\n"
"	movb	%bl, -33(%ebp)\n"
"	movsbl	%bl,%edx\n"
"	movl	_isdig.5(,%edx,4), %esi\n"
"	testl	%esi, %esi\n"
"	je	L45\n"
"L100:\n"
"	movsbl	-33(%ebp),%esi\n"
"	subl	$48, %esi\n"
"	movl	%esi, -28(%ebp)\n"
"	incl	%edi\n"
"	movzbl	(%edi), %edx\n"
"	movb	%dl, -33(%ebp)\n"
"	movsbl	%dl,%eax\n"
"	movl	_isdig.5(,%eax,4), %ecx\n"
"	testl	%ecx, %ecx\n"
"	je	L102\n"
"	movl	%eax, %edx\n"
"L50:\n"
"	movl	-28(%ebp), %eax\n"
"	leal	(%eax,%eax,4), %ebx\n"
"	leal	-48(%edx,%ebx,2), %esi\n"
"	movl	%esi, -28(%ebp)\n"
"	incl	%edi\n"
"	movzbl	(%edi), %edx\n"
"	movb	%dl, -33(%ebp)\n"
"	movsbl	%dl,%ecx\n"
"	movl	%ecx, %edx\n"
"	movl	_isdig.5(,%ecx,4), %ebx\n"
"	testl	%ebx, %ebx\n"
"	jne	L50\n"
"L102:\n"
"	movl	-28(%ebp), %ecx\n"
"	testl	%ecx, %ecx\n"
"	je	L40\n"
"	movl	$0, -20(%ebp)\n"
"	movl	-28(%ebp), %esi\n"
"	cmpl	%esi, -20(%ebp)\n"
"	jge	L104\n"
"L81:\n"
"	xorl	%esi, %esi\n"
"L69:\n"
"	movsbl	-33(%ebp),%ebx\n"
"	movl	_isdig.5(,%ebx,4), %edx\n"
"	testl	%edx, %edx\n"
"	jne	L108\n"
"	.p2align 4,,15\n"
"L63:\n"
"	incl	%edi\n"
"	movzbl	(%edi), %eax\n"
"	movb	%al, -33(%ebp)\n"
"	movsbl	%al,%ebx\n"
"	movl	_isdig.5(,%ebx,4), %edx\n"
"	testl	%edx, %edx\n"
"	je	L63\n"
"L108:\n"
"	movsbl	-33(%ebp),%ebx\n"
"	leal	-48(%ebx), %ecx\n"
"	incl	%edi\n"
"	movzbl	(%edi), %edx\n"
"	movb	%dl, -33(%ebp)\n"
"	movsbl	%dl,%eax\n"
"	movl	_isdig.5(,%eax,4), %ebx\n"
"	testl	%ebx, %ebx\n"
"	je	L110\n"
"	movl	%eax, %edx\n"
"	.p2align 4,,15\n"
"L68:\n"
"	leal	(%ecx,%ecx,4), %ebx\n"
"	leal	-48(%edx,%ebx,2), %ecx\n"
"	incl	%edi\n"
"	movzbl	(%edi), %edx\n"
"	movb	%dl, -33(%ebp)\n"
"	movsbl	%dl,%ebx\n"
"	movl	%ebx, %edx\n"
"	movl	_isdig.5(,%ebx,4), %eax\n"
"	testl	%eax, %eax\n"
"	jne	L68\n"
"L110:\n"
"	leal	-1(%ecx), %edx\n"
"	movl	%edx, _b.4(,%esi,4)\n"
"	incl	%esi\n"
"	cmpl	$5, %esi\n"
"	jle	L69\n"
"	xorl	%esi, %esi\n"
"	movl	$1073741823, -24(%ebp)\n"
"	.p2align 4,,15\n"
"L80:\n"
"	xorl	%ecx, %ecx\n"
"	xorl	%eax, %eax\n"
"	leal	0(,%esi,8), %ebx\n"
"	.p2align 4,,15\n"
"L78:\n"
"	leal	(%eax,%eax,2), %edx\n"
"	leal	(%ecx,%ebx), %eax\n"
"	movl	_sym(,%eax,4), %eax\n"
"	movl	_b.4(,%eax,4), %eax\n"
"	leal	(%eax,%edx,2), %eax\n"
"	incl	%ecx\n"
"	cmpl	$5, %ecx\n"
"	jle	L78\n"
"	cmpl	-24(%ebp), %eax\n"
"	jge	L72\n"
"	movl	%eax, -24(%ebp)\n"
"L72:\n"
"	incl	%esi\n"
"	cmpl	$23, %esi\n"
"	jle	L80\n"
"	movl	-24(%ebp), %eax\n"
"	movl	-20(%ebp), %ecx\n"
"	movl	%eax, _a.3(,%ecx,4)\n"
"	incl	%ecx\n"
"	movl	%ecx, -20(%ebp)\n"
"	movl	-28(%ebp), %esi\n"
"	cmpl	%esi, %ecx\n"
"	jl	L81\n"
"L104:\n"
"	movl	-28(%ebp), %edx\n"
"	movl	%edx, 4(%esp)\n"
"	movl	$_a.3, (%esp)\n"
"	call	_sort\n"
"	movl	$1, -24(%ebp)\n"
"	movl	$1, -20(%ebp)\n"
"	movl	-28(%ebp), %ebx\n"
"	cmpl	%ebx, -24(%ebp)\n"
"	jge	L116\n"
"L87:\n"
"	movl	-20(%ebp), %eax\n"
"	movl	_a.3(,%eax,4), %esi\n"
"	cmpl	%esi, _a.3-4(,%eax,4)\n"
"	je	L84\n"
"	incl	-24(%ebp)\n"
"L84:\n"
"	incl	-20(%ebp)\n"
"	movl	-28(%ebp), %ecx\n"
"	cmpl	%ecx, -20(%ebp)\n"
"	jl	L87\n"
"L116:\n"
"	movl	$_tmp.2, %ecx\n"
"	movl	-24(%ebp), %ebx\n"
"	testl	%ebx, %ebx\n"
"	jle	L118\n"
"	movl	$1717986919, %ebx\n"
"L92:\n"
"	movl	-24(%ebp), %eax\n"
"	imull	%ebx\n"
"	movl	%eax, -48(%ebp)\n"
"	movl	%edx, -44(%ebp)\n"
"	movl	-44(%ebp), %esi\n"
"	sarl	$2, %esi\n"
"	movl	-24(%ebp), %edx\n"
"	sarl	$31, %edx\n"
"	subl	%edx, %esi\n"
"	leal	(%esi,%esi,4), %edx\n"
"	addl	%edx, %edx\n"
"	subl	%edx, -24(%ebp)\n"
"	movzbl	-24(%ebp), %edx\n"
"	addb	$48, %dl\n"
"	movb	%dl, (%ecx)\n"
"	incl	%ecx\n"
"	movl	%esi, -24(%ebp)\n"
"	testl	%esi, %esi\n"
"	jg	L92\n"
"L118:\n"
"	decl	%ecx\n"
"	cmpl	$_tmp.2-1, %ecx\n"
"	jbe	L120\n"
"L96:\n"
"	movzbl	(%ecx), %edx\n"
"	movl	-32(%ebp), %ebx\n"
"	movb	%dl, (%ebx)\n"
"	incl	%ebx\n"
"	movl	%ebx, -32(%ebp)\n"
"	decl	%ecx\n"
"	cmpl	$_tmp.2-1, %ecx\n"
"	ja	L96\n"
"L120:\n"
"	movl	-32(%ebp), %eax\n"
"	movb	$10, (%eax)\n"
"	incl	%eax\n"
"	movl	%eax, -32(%ebp)\n"
"	jmp	L39\n"
"L40:\n"
"	subl	$_outbuf.1, -32(%ebp)\n"
"	movl	-32(%ebp), %ecx\n"
"	movl	%ecx, 8(%esp)\n"
"	movl	$_outbuf.1, %edi\n"
"	movl	%edi, 4(%esp)\n"
"	movl	$1, (%esp)\n"
"	call	write\n"
"	movl	$0, (%esp)\n"
"	call	exit\n"
".lcomm _b.4,32\n"
".lcomm _a.3,4096\n"
".lcomm _isdig.5,1024\n"
".lcomm _tmp.2,256\n"
".lcomm _inbuf.0,131072\n"
".lcomm _outbuf.1,65536\n"
);
}
