int main()
{
__asm__ __volatile__(
"	pushl	%ebp\n"
"	movl	%esp, %ebp\n"
"	pushl	%edi\n"
"	pushl	%esi\n"
"	pushl	%ebx\n"
"	subl	$28, %esp\n"
"	movl	$48, %edi\n"
"L6:\n"
"	movl	$1, %edx\n"
"	movl	%edx, _isdig.3(,%edi,4)\n"
"	incl	%edi\n"
"	cmpl	$57, %edi\n"
"	jle	L6\n"
"	movl	$48, %edi\n"
"L11:\n"
"	movl	$1, %edx\n"
"	movl	%edx, _isdigm.4(,%edi,4)\n"
"	incl	%edi\n"
"	cmpl	$57, %edi\n"
"	jle	L11\n"
"	movl	$1, %esi\n"
"	movl	%esi, _isdigm.4+180\n"
"	movl	$65536, %ebx\n"
"	movl	%ebx, 8(%esp)\n"
"	movl	$_inbuf.0, -16(%ebp)\n"
"	movl	$_inbuf.0, %ecx\n"
"	movl	%ecx, 4(%esp)\n"
"	movl	$0, (%esp)\n"
"	call	read\n"
"	movl	$_outbuf.1, %ebx\n"
"	movzbl	_inbuf.0, %ecx\n"
"L12:\n"
"	movsbl	%cl,%edi\n"
"	movl	_isdigm.4(,%edi,4), %edx\n"
"	testl	%edx, %edx\n"
"	jne	L62\n"
"L18:\n"
"	incl	-16(%ebp)\n"
"	movl	-16(%ebp), %edi\n"
"	movzbl	(%edi), %ecx\n"
"	movsbl	%cl,%esi\n"
"	movl	_isdigm.4(,%esi,4), %edx\n"
"	testl	%edx, %edx\n"
"	je	L18\n"
"L62:\n"
"	cmpb	$45, %cl\n"
"	je	L77\n"
"	movsbl	%cl,%edx\n"
"	leal	-48(%edx), %edi\n"
"	incl	-16(%ebp)\n"
"	movl	-16(%ebp), %eax\n"
"	movzbl	(%eax), %ecx\n"
"	movsbl	%cl,%eax\n"
"	movl	_isdig.3(,%eax,4), %esi\n"
"	testl	%esi, %esi\n"
"	je	L66\n"
"	movl	%eax, %edx\n"
"L30:\n"
"	leal	(%edi,%edi,4), %ecx\n"
"	leal	-48(%edx,%ecx,2), %edi\n"
"	incl	-16(%ebp)\n"
"	movl	-16(%ebp), %edx\n"
"	movzbl	(%edx), %ecx\n"
"	movsbl	%cl,%esi\n"
"	movl	%esi, %edx\n"
"	movl	_isdig.3(,%esi,4), %eax\n"
"	testl	%eax, %eax\n"
"	jne	L30\n"
"L66:\n"
"	testl	%edi, %edi\n"
"	je	L13\n"
"	movl	$_htext, %esi\n"
"L25:\n"
"	movzbl	(%esi), %eax\n"
"	testb	%al, %al\n"
"	je	L68\n"
"L56:\n"
"	movl	$_t.2, %ecx\n"
"	cmpb	$10, %al\n"
"	je	L70\n"
"	.p2align 4,,15\n"
"L45:\n"
"	movsbl	%al,%eax\n"
"	incl	%esi\n"
"	testl	%edi, %edi\n"
"	jle	L72\n"
"	movl	%edi, %edx\n"
"	.p2align 4,,15\n"
"L44:\n"
"	movb	%al, (%ecx)\n"
"	incl	%ecx\n"
"	decl	%edx\n"
"	jne	L44\n"
"L72:\n"
"	movzbl	(%esi), %eax\n"
"	cmpb	$10, %al\n"
"	jne	L45\n"
"L70:\n"
"	movb	$10, (%ecx)\n"
"	movb	$0, 1(%ecx)\n"
"	testl	%edi, %edi\n"
"	jle	L74\n"
"	movzbl	_t.2, %eax\n"
"	movb	%al, -18(%ebp)\n"
"	movb	%al, -17(%ebp)\n"
"	movl	%edi, %edx\n"
"	.p2align 4,,15\n"
"L55:\n"
"	movl	$_t.2, %ecx\n"
"	cmpb	$0, -17(%ebp)\n"
"	je	L76\n"
"	movzbl	-18(%ebp), %eax\n"
"	.p2align 4,,15\n"
"L54:\n"
"	incl	%ecx\n"
"	movb	%al, (%ebx)\n"
"	incl	%ebx\n"
"	movzbl	(%ecx), %eax\n"
"	testb	%al, %al\n"
"	jne	L54\n"
"L76:\n"
"	decl	%edx\n"
"	jne	L55\n"
"L74:\n"
"	incl	%esi\n"
"	movzbl	(%esi), %eax\n"
"	testb	%al, %al\n"
"	jne	L56\n"
"	movl	-16(%ebp), %edi\n"
"	movzbl	(%edi), %ecx\n"
"L68:\n"
"	movb	$10, (%ebx)\n"
"	incl	%ebx\n"
"	movb	$10, (%ebx)\n"
"	incl	%ebx\n"
"	jmp	L12\n"
"L77:\n"
"	incl	-16(%ebp)\n"
"	movl	-16(%ebp), %esi\n"
"	movsbl	(%esi),%ecx\n"
"	leal	-48(%ecx), %edi\n"
"	incl	%esi\n"
"	movl	%esi, -16(%ebp)\n"
"	movzbl	(%esi), %ecx\n"
"	movsbl	%cl,%eax\n"
"	movl	_isdig.3(,%eax,4), %esi\n"
"	testl	%esi, %esi\n"
"	je	L64\n"
"	movl	%eax, %edx\n"
"L24:\n"
"	leal	(%edi,%edi,4), %ecx\n"
"	leal	-48(%edx,%ecx,2), %edi\n"
"	incl	-16(%ebp)\n"
"	movl	-16(%ebp), %edx\n"
"	movzbl	(%edx), %ecx\n"
"	movsbl	%cl,%esi\n"
"	movl	%esi, %edx\n"
"	movl	_isdig.3(,%esi,4), %eax\n"
"	testl	%eax, %eax\n"
"	jne	L24\n"
"L64:\n"
"	movl	$_vtext, %esi\n"
"	jmp	L25\n"
"L13:\n"
"	subl	$_outbuf.1, %ebx\n"
"	movl	%ebx, 8(%esp)\n"
"	movl	$_outbuf.1, %ebx\n"
"	movl	%ebx, 4(%esp)\n"
"	movl	$1, (%esp)\n"
"	call	write\n"
"	movl	$0, (%esp)\n"
"	call	exit\n"
"	.align 32\n"
"_htext:\n"
".ascii \"*****..***..*...*.*****...*...*.*****.*****.***...*****.*...*\\12*...\"\n"
".ascii \"..*...*.*...*.*.......*...*.*...*...*...*..*..*...*..*.*.\\12*****.**\"\n"
".ascii \"***.*...*.***.....*****.*****...*...*...*.*...*...*..\\12....*.*...*.\"\n"
".ascii \".*.*..*.......*...*.*.*.....*...*..*..*...*...*..\\12*****.*...*...*.\"\n"
".ascii \"..*****...*...*.*..**.*****.***...*****...*..\\12\\0\"\n"
"	.align 32\n"
"_vtext:\n"
".ascii \"*****\\12*....\\12*****\\12....*\\12*****\\12.....\\12.***.\\12*...*\\12*****\\12*...*\\12*...*\"\n"
".ascii \"\\12.....\\12*...*\\12*...*\\12*...*\\12.*.*.\\12..*..\\12.....\\12*****\\12*....\\12***..\\12*\"\n"
".ascii \"....\\12*****\\12.....\\12.....\\12.....\\12*...*\\12*...*\\12*****\\12*...*\\12*...*\\12.....\\12*\"\n"
".ascii \"****\\12*...*\\12*****\\12*.*..\\12*..**\\12.....\\12*****\\12..*..\\12..*..\\12..*..\\12*****\\12.\"\n"
".ascii \"....\\12***..\\12*..*.\\12*...*\\12*..*.\\12***..\\12.....\\12*****\\12*...*\\12*...*\\12*...*\\12*\"\n"
".ascii \"****\\12.....\\12*...*\\12.*.*.\\12..*..\\12..*..\\12..*..\\12\\0\"\n"
".lcomm _isdig.3,1024\n"
".lcomm _isdigm.4,1024\n"
".lcomm _inbuf.0,65536\n"
".lcomm _t.2,65536\n"
".lcomm _outbuf.1,31457280\n"
);
}
