void go()
{
__asm__ __volatile__(
"	jmp main2\n"
"LC0:\n"
"	.ascii \"%d\\12\\12\\0\"\n"
"	.text\n"
"	.p2align 4,,15\n"
"main2:\n"
"	pushl	%ebp\n"
"	movl	%esp, %ebp\n"
"	pushl	%edi\n"
"	pushl	%esi\n"
"	pushl	%ebx\n"
"	subl	$28, %esp\n"
"	xorl	%edx, %edx\n"
"	.p2align 4,,15\n"
"L6:\n"
"	leal	-48(%edx), %eax\n"
"	cmpl	$9, %eax\n"
"	setbe	%al\n"
"	movzbl	%al, %eax\n"
"	movl	%eax, _isdig(,%edx,4)\n"
"	testl	%eax, %eax\n"
"	sete	%al\n"
"	movzbl	%al, %eax\n"
"	movl	%eax, _not_isdigz(,%edx,4)\n"
"	movl	%eax, _not_isdigzn(,%edx,4)\n"
"	incl	%edx\n"
"	cmpl	$255, %edx\n"
"	jle	L6\n"
"	xorl	%edx, %edx\n"
"	movl	%edx, _not_isdigz\n"
"	xorl	%eax, %eax\n"
"	movl	%eax, _not_isdigzn\n"
"	xorl	%eax, %eax\n"
"	movl	%eax, _not_isdigzn+40\n"
"	movl	$8388607, %eax\n"
"	movl	%eax, 8(%esp)\n"
"	movl	$_inbuf, %ebx\n"
"	movl	%ebx, 4(%esp)\n"
"	movl	$0, (%esp)\n"
"	call	read\n"
"	movb	$0, _inbuf(%eax)\n"
"	movzbl	_inbuf, %edx\n"
"	movsbl	%dl,%eax\n"
"	movl	_not_isdigz(,%eax,4), %eax\n"
"	testl	%eax, %eax\n"
"	je	L125\n"
"L10:\n"
"	incl	%ebx\n"
"	movzbl	(%ebx), %ecx\n"
"	movsbl	%cl,%eax\n"
"	movl	_not_isdigz(,%eax,4), %eax\n"
"	testl	%eax, %eax\n"
"	jne	L10\n"
"L11:\n"
"	movsbl	%cl,%eax\n"
"	movl	_not_isdigzn(,%eax,4), %eax\n"
"	testl	%eax, %eax\n"
"	je	L104\n"
"	.p2align 4,,15\n"
"L17:\n"
"	incl	%ebx\n"
"	movzbl	(%ebx), %ecx\n"
"	movsbl	%cl,%eax\n"
"	movl	_not_isdigzn(,%eax,4), %edi\n"
"	testl	%edi, %edi\n"
"	jne	L17\n"
"L104:\n"
"	testb	%cl, %cl\n"
"	je	L19\n"
"	cmpb	$10, %cl\n"
"	jne	L12\n"
"	incl	%ebx\n"
"	movzbl	(%ebx), %ecx\n"
"	cmpb	$10, %cl\n"
"	jne	L11\n"
"	jmp	L19\n"
"L12:\n"
"	movsbl	%cl,%eax\n"
"	incl	%ebx\n"
"	leal	-48(%eax), %edx\n"
"	movl	%edx, _ntests\n"
"	movzbl	(%ebx), %ecx\n"
"	movsbl	%cl,%eax\n"
"	movl	_isdig(,%eax,4), %esi\n"
"	testl	%esi, %esi\n"
"	je	L126\n"
"	movl	%eax, %esi\n"
"L26:\n"
"	leal	(%edx,%edx,4), %eax\n"
"	incl	%ebx\n"
"	leal	-48(%esi,%eax,2), %edx\n"
"	movl	%edx, _ntests\n"
"	movzbl	(%ebx), %ecx\n"
"	movsbl	%cl,%eax\n"
"	movl	%eax, %esi\n"
"	movl	_isdig(,%eax,4), %eax\n"
"	testl	%eax, %eax\n"
"	jne	L26\n"
"L106:\n"
"	movl	%edx, %eax\n"
"	decl	%edx\n"
"	movl	%edx, _ntests\n"
"	testl	%eax, %eax\n"
"	jle	L19\n"
"L99:\n"
"	movsbl	%cl,%eax\n"
"	movl	_not_isdigz(,%eax,4), %eax\n"
"	testl	%eax, %eax\n"
"	je	L34\n"
"L33:\n"
"	incl	%ebx\n"
"	movzbl	(%ebx), %ecx\n"
"	movsbl	%cl,%eax\n"
"	movl	_not_isdigz(,%eax,4), %eax\n"
"	testl	%eax, %eax\n"
"	jne	L33\n"
"L34:\n"
"	movsbl	%cl,%eax\n"
"	movl	_not_isdigzn(,%eax,4), %edi\n"
"	testl	%edi, %edi\n"
"	je	L110\n"
"L40:\n"
"	incl	%ebx\n"
"	movzbl	(%ebx), %ecx\n"
"	movsbl	%cl,%eax\n"
"	movl	_not_isdigzn(,%eax,4), %esi\n"
"	testl	%esi, %esi\n"
"	jne	L40\n"
"L110:\n"
"	testb	%cl, %cl\n"
"	je	L19\n"
"	cmpb	$10, %cl\n"
"	jne	L35\n"
"	incl	%ebx\n"
"	movzbl	(%ebx), %ecx\n"
"	cmpb	$10, %cl\n"
"	jne	L34\n"
"	jmp	L19\n"
"L35:\n"
"	movsbl	%cl,%eax\n"
"	leal	-48(%eax), %esi\n"
"	incl	%ebx\n"
"	movzbl	(%ebx), %ecx\n"
"	movsbl	%cl,%eax\n"
"	movl	_isdig(,%eax,4), %edx\n"
"	testl	%edx, %edx\n"
"	je	L112\n"
"	movl	%eax, %edx\n"
"L48:\n"
"	leal	(%esi,%esi,4), %eax\n"
"	leal	-48(%edx,%eax,2), %esi\n"
"	incl	%ebx\n"
"	movzbl	(%ebx), %ecx\n"
"	movsbl	%cl,%eax\n"
"	movl	%eax, %edx\n"
"	movl	_isdig(,%eax,4), %eax\n"
"	testl	%eax, %eax\n"
"	jne	L48\n"
"L112:\n"
"	movl	%esi, -16(%ebp)\n"
"	xorl	%edx, %edx\n"
"	cmpl	%esi, %edx\n"
"	jg	L128\n"
"L53:\n"
"	movl	%edx, _p(,%edx,4)\n"
"	incl	%edx\n"
"	cmpl	%esi, %edx\n"
"	jle	L53\n"
"L128:\n"
"	movsbl	%cl,%eax\n"
"	movl	_not_isdigzn(,%eax,4), %edi\n"
"	testl	%edi, %edi\n"
"	je	L115\n"
"L63:\n"
"	incl	%ebx\n"
"	movzbl	(%ebx), %ecx\n"
"	movsbl	%cl,%eax\n"
"	movl	_not_isdigzn(,%eax,4), %esi\n"
"	testl	%esi, %esi\n"
"	jne	L63\n"
"L115:\n"
"	testb	%cl, %cl\n"
"	je	L65\n"
"	cmpb	$10, %cl\n"
"	je	L130\n"
"	movsbl	%cl,%eax\n"
"	leal	-48(%eax), %esi\n"
"	incl	%ebx\n"
"	movzbl	(%ebx), %ecx\n"
"	movsbl	%cl,%eax\n"
"	movl	_isdig(,%eax,4), %edx\n"
"	testl	%edx, %edx\n"
"	je	L73\n"
"	movl	%eax, %edx\n"
"L72:\n"
"	leal	(%esi,%esi,4), %eax\n"
"	leal	-48(%edx,%eax,2), %esi\n"
"	incl	%ebx\n"
"	movzbl	(%ebx), %ecx\n"
"	movsbl	%cl,%eax\n"
"	movl	%eax, %edx\n"
"	movl	_isdig(,%eax,4), %eax\n"
"	testl	%eax, %eax\n"
"	jne	L72\n"
"L73:\n"
"	movsbl	%cl,%eax\n"
"	movl	_not_isdigzn(,%eax,4), %eax\n"
"	testl	%eax, %eax\n"
"	je	L118\n"
"L79:\n"
"	incl	%ebx\n"
"	movzbl	(%ebx), %ecx\n"
"	movsbl	%cl,%eax\n"
"	movl	_not_isdigzn(,%eax,4), %edi\n"
"	testl	%edi, %edi\n"
"	jne	L79\n"
"L118:\n"
"	testb	%cl, %cl\n"
"	je	L65\n"
"	cmpb	$10, %cl\n"
"	jne	L74\n"
"	incl	%ebx\n"
"	movzbl	(%ebx), %ecx\n"
"	cmpb	$10, %cl\n"
"	jne	L73\n"
"L129:\n"
"	incl	%ebx\n"
"L65:\n"
"	movl	-16(%ebp), %eax\n"
"	movl	%eax, 4(%esp)\n"
"	movl	$LC0, (%esp)\n"
"	call	printf\n"
"	movl	_ntests, %edx\n"
"	leal	-1(%edx), %eax\n"
"	movl	%eax, _ntests\n"
"	testl	%edx, %edx\n"
"	jle	L19\n"
"	movzbl	(%ebx), %ecx\n"
"	jmp	L99\n"
"L74:\n"
"	movsbl	%cl,%eax\n"
"	leal	-48(%eax), %edi\n"
"	incl	%ebx\n"
"	movzbl	(%ebx), %eax\n"
"	movb	%al, %cl\n"
"	movsbl	%al,%eax\n"
"	movl	_isdig(,%eax,4), %edx\n"
"	testl	%edx, %edx\n"
"	je	L120\n"
"	movl	%eax, %edx\n"
"L87:\n"
"	leal	(%edi,%edi,4), %eax\n"
"	leal	-48(%edx,%eax,2), %edi\n"
"	incl	%ebx\n"
"	movzbl	(%ebx), %eax\n"
"	movb	%al, %cl\n"
"	movsbl	%al,%eax\n"
"	movl	%eax, %edx\n"
"	movl	_isdig(,%eax,4), %eax\n"
"	testl	%eax, %eax\n"
"	jne	L87\n"
"L120:\n"
"	movl	%esi, %edx\n"
"	movl	_p(,%esi,4), %eax\n"
"	cmpl	%esi, %eax\n"
"	je	L122\n"
"L92:\n"
"	movl	%eax, %edx\n"
"	movl	_p(,%eax,4), %eax\n"
"	cmpl	%edx, %eax\n"
"	jne	L92\n"
"L122:\n"
"	movl	%edx, _p(,%esi,4)\n"
"	movl	%edx, %esi\n"
"	movl	%edi, %edx\n"
"	movl	_p(,%edi,4), %eax\n"
"	cmpl	%edi, %eax\n"
"	je	L124\n"
"L97:\n"
"	movl	%eax, %edx\n"
"	movl	_p(,%eax,4), %eax\n"
"	cmpl	%edx, %eax\n"
"	jne	L97\n"
"L124:\n"
"	movl	%edx, _p(,%edi,4)\n"
"	cmpl	%edx, %esi\n"
"	je	L128\n"
"	movl	%esi, _p(,%edx,4)\n"
"	decl	-16(%ebp)\n"
"	jmp	L128\n"
"	.p2align 4,,7\n"
"L130:\n"
"	incl	%ebx\n"
"	movzbl	(%ebx), %ecx\n"
"	cmpb	$10, %cl\n"
"	jne	L128\n"
"	jmp	L129\n"
"	.p2align 4,,7\n"
"L126:\n"
"	movl	_ntests, %edx\n"
"	jmp	L106\n"
"L125:\n"
"	movb	%dl, %cl\n"
"	jmp	L11\n"
"L19:\n"
"	movl	$0, (%esp)\n"
"	call	exit\n"
"	.comm	_isdig, 1024\n"
"	.comm	_not_isdigzn, 1024\n"
"	.comm	_not_isdigz, 1024\n"
"	.comm	_ntests, 16\n"
"	.comm	_p, 4194304\n"
"	.comm	_inbuf, 8388608\n"
);
}

int main()
{
	go();
	return 0;
}
