int main()
{
__asm__ __volatile__(
"	pushl	%ebp\n"
"	movl	%esp, %ebp\n"
"	pushl	%ebx\n"
"	subl	$20, %esp\n"
"	movl	$1048576, %eax\n"
"	movl	%eax, 8(%esp)\n"
"	movl	$_inbuf.0, %ebx\n"
"	movl	%ebx, 4(%esp)\n"
"	movl	$0, (%esp)\n"
"	call	read\n"
"	movb	$0, _inbuf.0(%eax)\n"
"	movl	$_outbuf.1, %ecx\n"
"	.p2align 4,,15\n"
"L10:\n"
"	movzbl	(%ebx), %eax\n"
"	testb	%al, %al\n"
"	je	L14\n"
"	cmpb	$124, %al\n"
"	je	L14\n"
"	.p2align 4,,15\n"
"L17:\n"
"	incl	%ebx\n"
"	movzbl	(%ebx), %eax\n"
"	testb	%al, %al\n"
"	je	L14\n"
"	cmpb	$124, %al\n"
"	jne	L17\n"
"L14:\n"
"	incl	%ebx\n"
"	cmpb	$124, %al\n"
"	jne	L11\n"
"	xorl	%edx, %edx\n"
"	movzbl	(%ebx), %eax\n"
"	cmpb	$124, %al\n"
"	je	L29\n"
"	.p2align 4,,15\n"
"L26:\n"
"	cmpb	$32, %al\n"
"	je	L30\n"
"	cmpb	$111, %al\n"
"	je	L31\n"
"L21:\n"
"	incl	%ebx\n"
"	movzbl	(%ebx), %eax\n"
"	cmpb	$124, %al\n"
"	jne	L26\n"
"L29:\n"
"	incl	%ebx\n"
"	movb	%dl, (%ecx)\n"
"	incl	%ecx\n"
"	jmp	L10\n"
"	.p2align 4,,7\n"
"L31:\n"
"	addl	%edx, %edx\n"
"	orl	$1, %edx\n"
"	jmp	L21\n"
"	.p2align 4,,7\n"
"L30:\n"
"	addl	%edx, %edx\n"
"	jmp	L21\n"
"L11:\n"
"	subl	$_outbuf.1, %ecx\n"
"	movl	%ecx, 8(%esp)\n"
"	movl	$_outbuf.1, %edx\n"
"	movl	%edx, 4(%esp)\n"
"	movl	$1, (%esp)\n"
"	call	write\n"
"	movl	$0, (%esp)\n"
"	call	exit\n"
".lcomm _inbuf.0,131072\n"
".lcomm _outbuf.1,65536\n"
);
}
