int main()
{
__asm__ __volatile__(
"	pushl	%ebp\n"
"	movl	%esp, %ebp\n"
"	pushl	%esi\n"
"	pushl	%ebx\n"
"	subl	$16, %esp\n"
"	call	_take\n"
"	call	_solve\n"
"	movl	_k, %edx\n"
"	movl	%edx, 8(%esp)\n"
"	movl	$LC0, %eax\n"
"	movl	%eax, 4(%esp)\n"
"	movl	$_outbuf, %ebx\n"
"	movl	%ebx, (%esp)\n"
"	call	sprintf\n"
"	cmpb	$0, _outbuf\n"
"	je	L110\n"
"	.p2align 4,,15\n"
"L97:\n"
"	incl	%ebx\n"
"	cmpb	$0, (%ebx)\n"
"	jne	L97\n"
"L110:\n"
"	xorl	%ecx, %ecx\n"
"	movl	_k, %esi\n"
"	cmpl	%esi, %ecx\n"
"	jge	L112\n"
"	.p2align 4,,15\n"
"L107:\n"
"	movl	_z(,%ecx,4), %eax\n"
"	movl	_xp(,%eax,4), %edx\n"
"	movzbl	(%edx), %eax\n"
"	testb	%al, %al\n"
"	je	L114\n"
"	.p2align 4,,15\n"
"L106:\n"
"	incl	%edx\n"
"	movb	%al, (%ebx)\n"
"	incl	%ebx\n"
"	movzbl	(%edx), %eax\n"
"	testb	%al, %al\n"
"	jne	L106\n"
"L114:\n"
"	movb	$10, (%ebx)\n"
"	incl	%ebx\n"
"	incl	%ecx\n"
"	cmpl	%esi, %ecx\n"
"	jl	L107\n"
"L112:\n"
"	subl	$_outbuf, %ebx\n"
"	movl	%ebx, 8(%esp)\n"
"	movl	$_outbuf, %ecx\n"
"	movl	%ecx, 4(%esp)\n"
"	movl	$1, (%esp)\n"
"	call	write\n"
"	movl	$0, (%esp)\n"
"	call	exit\n"
"	.p2align 4,,15\n"
"_take:\n"
"	pushl	%ebp\n"
"	movl	%esp, %ebp\n"
"	pushl	%esi\n"
"	pushl	%ebx\n"
"	subl	$16, %esp\n"
"	xorl	%edx, %edx\n"
"	.p2align 4,,15\n"
"L6:\n"
"	xorl	%eax, %eax\n"
"	movl	%eax, _d.0(,%edx,4)\n"
"	incl	%edx\n"
"	cmpl	$255, %edx\n"
"	jle	L6\n"
"	movl	$48, %edx\n"
"L11:\n"
"	movl	$1, %eax\n"
"	movl	%eax, _d.0(,%edx,4)\n"
"	incl	%edx\n"
"	cmpl	$57, %edx\n"
"	jle	L11\n"
"	xorl	%edx, %edx\n"
"	.p2align 4,,15\n"
"L16:\n"
"	movl	$1, %ecx\n"
"	movl	%ecx, _z.1(,%edx,4)\n"
"	incl	%edx\n"
"	cmpl	$255, %edx\n"
"	jle	L16\n"
"	movl	$48, %edx\n"
"L21:\n"
"	xorl	%ebx, %ebx\n"
"	movl	%ebx, _z.1(,%edx,4)\n"
"	incl	%edx\n"
"	cmpl	$57, %edx\n"
"	jle	L21\n"
"	xorl	%ebx, %ebx\n"
"	movl	%ebx, _z.1\n"
"	xorl	%esi, %esi\n"
"	movl	%esi, _z.1+180\n"
"	movl	$2048575, %edx\n"
"	movl	%edx, 8(%esp)\n"
"	movl	$_inbuf, %esi\n"
"	movl	%esi, 4(%esp)\n"
"	movl	$0, (%esp)\n"
"	call	read\n"
"	movb	$0, _inbuf(%eax)\n"
"	movb	$0, _inbuf+1(%eax)\n"
"	xorl	%edx, %edx\n"
"L129:\n"
"	movzbl	(%esi), %ecx\n"
"	movsbl	%cl,%eax\n"
"	movl	_z.1(,%eax,4), %ebx\n"
"	testl	%ebx, %ebx\n"
"	je	L124\n"
"	.p2align 4,,15\n"
"L28:\n"
"	incl	%esi\n"
"	movzbl	(%esi), %ecx\n"
"	movsbl	%cl,%eax\n"
"	movl	_z.1(,%eax,4), %ebx\n"
"	testl	%ebx, %ebx\n"
"	jne	L28\n"
"L124:\n"
"	movl	%esi, _xp(,%edx,4)\n"
"	cmpb	$45, %cl\n"
"	je	L131\n"
"	testb	%cl, %cl\n"
"	je	L23\n"
"	movsbl	%cl,%eax\n"
"	leal	-48(%eax), %ebx\n"
"	incl	%esi\n"
"	movsbl	(%esi),%eax\n"
"	movl	_d.0(,%eax,4), %ecx\n"
"	testl	%ecx, %ecx\n"
"	je	L128\n"
"	movl	%eax, %ecx\n"
"	.p2align 4,,15\n"
"L42:\n"
"	leal	(%ebx,%ebx,4), %eax\n"
"	leal	-48(%ecx,%eax,2), %ebx\n"
"	incl	%esi\n"
"	movsbl	(%esi),%eax\n"
"	movl	%eax, %ecx\n"
"	movl	_d.0(,%eax,4), %eax\n"
"	testl	%eax, %eax\n"
"	jne	L42\n"
"L128:\n"
"	movb	$0, (%esi)\n"
"	incl	%esi\n"
"L130:\n"
"	movl	%ebx, _x(,%edx,4)\n"
"	incl	%edx\n"
"	jmp	L129\n"
"L23:\n"
"	movl	%edx, _n\n"
"	addl	$16, %esp\n"
"	popl	%ebx\n"
"	popl	%esi\n"
"	popl	%ebp\n"
"	ret\n"
"L131:\n"
"	incl	%esi\n"
"	movsbl	(%esi),%ecx\n"
"	leal	-48(%ecx), %ebx\n"
"	incl	%esi\n"
"	movsbl	(%esi),%eax\n"
"	movl	_d.0(,%eax,4), %ecx\n"
"	testl	%ecx, %ecx\n"
"	je	L126\n"
"	movl	%eax, %ecx\n"
"L34:\n"
"	leal	(%ebx,%ebx,4), %eax\n"
"	leal	-48(%ecx,%eax,2), %ebx\n"
"	incl	%esi\n"
"	movsbl	(%esi),%eax\n"
"	movl	%eax, %ecx\n"
"	movl	_d.0(,%eax,4), %eax\n"
"	testl	%eax, %eax\n"
"	jne	L34\n"
"L126:\n"
"	movb	$0, (%esi)\n"
"	incl	%esi\n"
"	negl	%ebx\n"
"	jmp	L130\n"
"	.p2align 4,,15\n"
"_solve:\n"
"	pushl	%ebp\n"
"	movl	%esp, %ebp\n"
"	pushl	%edi\n"
"	pushl	%esi\n"
"	pushl	%ebx\n"
"	subl	$4, %esp\n"
"	movl	$1, %ecx\n"
"	movl	%ecx, _k\n"
"	movl	_x, %edx\n"
"	movl	%edx, _z+4\n"
"	movl	$1, %eax\n"
"	movl	%eax, _y\n"
"	movl	$1, %ebx\n"
"	movl	_n, %edx\n"
"	movl	%edx, -16(%ebp)\n"
"	cmpl	%edx, %ebx\n"
"	jge	L140\n"
"	movl	%ebx, %edi\n"
"	.p2align 4,,15\n"
"L58:\n"
"	movl	_x(,%ebx,4), %esi\n"
"	cmpl	_z(,%edi,4), %esi\n"
"	jle	L48\n"
"	incl	%edi\n"
"	movl	%edi, _k\n"
"	movl	%edi, _y(,%ebx,4)\n"
"	movl	%esi, _z(,%edi,4)\n"
"L46:\n"
"	incl	%ebx\n"
"	cmpl	-16(%ebp), %ebx\n"
"	jl	L58\n"
"L133:\n"
"	movl	-16(%ebp), %ebx\n"
"	decl	%ebx\n"
"	movl	_y(,%ebx,4), %eax\n"
"	cmpl	%edi, %eax\n"
"	je	L137\n"
"	.p2align 4,,15\n"
"L63:\n"
"	decl	%ebx\n"
"	movl	_y(,%ebx,4), %eax\n"
"	cmpl	%edi, %eax\n"
"	jne	L63\n"
"L137:\n"
"	leal	-1(%edi), %ecx\n"
"	movl	%ebx, _z(,%ecx,4)\n"
"	movl	_x(,%ebx,4), %edx\n"
"	testl	%ebx, %ebx\n"
"	js	L139\n"
"	.p2align 4,,15\n"
"L69:\n"
"	cmpl	%ecx, %eax\n"
"	je	L142\n"
"L66:\n"
"	decl	%ebx\n"
"	js	L139\n"
"	movl	_y(,%ebx,4), %eax\n"
"	jmp	L69\n"
"L139:\n"
"	popl	%esi\n"
"	popl	%ebx\n"
"	popl	%esi\n"
"	popl	%edi\n"
"	popl	%ebp\n"
"	ret\n"
"	.p2align 4,,7\n"
"L142:\n"
"	movl	_x(,%ebx,4), %eax\n"
"	cmpl	%edx, %eax\n"
"	jge	L66\n"
"	decl	%ecx\n"
"	movl	%ebx, _z(,%ecx,4)\n"
"	movl	%eax, %edx\n"
"	jmp	L66\n"
"	.p2align 4,,7\n"
"L48:\n"
"	movl	$1, %ecx\n"
"	movl	%edi, %edx\n"
"	leal	-1(%edi), %eax\n"
"	decl	%eax\n"
"	jle	L135\n"
"	.p2align 4,,15\n"
"L55:\n"
"	leal	(%edx,%ecx), %eax\n"
"	sarl	%eax\n"
"	cmpl	%esi, _z(,%eax,4)\n"
"	jge	L53\n"
"	leal	1(%eax), %ecx\n"
"L49:\n"
"	movl	%edx, %eax\n"
"	subl	%ecx, %eax\n"
"	decl	%eax\n"
"	jg	L55\n"
"L135:\n"
"	movl	_z(,%ecx,4), %eax\n"
"	cmpl	%esi, %eax\n"
"	jge	L56\n"
"	incl	%ecx\n"
"	movl	_z(,%ecx,4), %eax\n"
"L56:\n"
"	movl	%ecx, _y(,%ebx,4)\n"
"	cmpl	%eax, %esi\n"
"	jge	L46\n"
"	movl	%esi, _z(,%ecx,4)\n"
"	jmp	L46\n"
"	.p2align 4,,7\n"
"L53:\n"
"	movl	%eax, %edx\n"
"	jmp	L49\n"
"L140:\n"
"	movl	_k, %edi\n"
"	jmp	L133\n"

"LC0:\n"
"	.ascii \"%d\\12-\\12\\0\"\n"
".p2align 4,,15\n"
".lcomm _d.0,1024\n"
".lcomm _z.1,1024\n"
".lcomm	_x, 524288\n"
".lcomm	_y, 524288\n"
".lcomm	_z, 524288\n"
".lcomm	_n, 16\n"
".lcomm	_k, 16\n"
".lcomm	_inbuf, 2048576\n"
".lcomm	_outbuf, 2048576\n"
".lcomm	_xp, 524288\n"
);
}
