int main()
{
__asm__ __volatile__(
"	jmp	_main2\n"
"	.p2align 4,,15\n"
"_f:\n"
"	pushl	%ebp\n"
"	movl	%esp, %ebp\n"
"	pushl	%edi\n"
"	pushl	%esi\n"
"	pushl	%ebx\n"
"	subl	$8, %esp\n"
"	movl	_id, %eax\n"
"	movl	8(%ebp), %edx\n"
"	cmpl	%eax, _got(,%edx,4)\n"
"	je	L24\n"
"	movl	8(%ebp), %ecx\n"
"	movl	%eax, _got(,%ecx,4)\n"
"	xorl	%edi, %edi\n"
"	movl	_n, %ebx\n"
"	movl	%ebx, %edx\n"
"	cmpl	%ebx, %edi\n"
"	jge	L4\n"
"	testb	$1, %cl\n"
"	je	L4\n"
"	.p2align 4,,15\n"
"L8:\n"
"	incl	%edi\n"
"	cmpl	%edx, %edi\n"
"	jge	L4\n"
"	movl	8(%ebp), %eax\n"
"	movl	%edi, %ecx\n"
"	sarl	%cl, %eax\n"
"	testb	$1, %al\n"
"	jne	L8\n"
"	.p2align 4,,15\n"
"L4:\n"
"	cmpl	%edx, %edi\n"
"	je	L25\n"
"	movl	$0x7f800000, %eax\n"
"	movl	8(%ebp), %ecx\n"
"	movl	%eax, _tab(,%ecx,4)\n"
"	leal	1(%edi), %esi\n"
"	cmpl	%edx, %esi\n"
"	jge	L21\n"
"	movl	$1, %eax\n"
"	movl	%edi, %ecx\n"
"	sall	%cl, %eax\n"
"	movl	%eax, -16(%ebp)\n"
"	.p2align 4,,15\n"
"L18:\n"
"	movl	8(%ebp), %eax\n"
"	movl	%esi, %ecx\n"
"	sarl	%cl, %eax\n"
"	testb	$1, %al\n"
"	je	L26\n"
"L12:\n"
"	incl	%esi\n"
"	cmpl	%ebx, %esi\n"
"	jl	L18\n"
"L21:\n"
"	movl	8(%ebp), %ecx\n"
"	flds	_tab(,%ecx,4)\n"
"L1:\n"
"	addl	$8, %esp\n"
"	popl	%ebx\n"
"	popl	%esi\n"
"	popl	%edi\n"
"	popl	%ebp\n"
"	ret\n"
"	.p2align 4,,7\n"
"L26:\n"
"	movl	%edi, %ebx\n"
"	sall	$4, %ebx\n"
"	addl	%esi, %ebx\n"
"	movl	$1, %eax\n"
"	sall	%cl, %eax\n"
"	movl	8(%ebp), %ecx\n"
"	xorl	%ecx, %eax\n"
"	movl	-16(%ebp), %edx\n"
"	xorl	%edx, %eax\n"
"	movl	%eax, (%esp)\n"
"	call	_f\n"
"	fadds	_d(,%ebx,4)\n"
"	movl	8(%ebp), %eax\n"
"	flds	_tab(,%eax,4)\n"
"	fucomp	%st(1)\n"
"	fnstsw	%ax\n"
"	sahf\n"
"	jbe	L23\n"
"	movl	8(%ebp), %edx\n"
"	fstps	_tab(,%edx,4)\n"
"L22:\n"
"	movl	_n, %ebx\n"
"	jmp	L12\n"
"	.p2align 4,,7\n"
"L23:\n"
"	fstp	%st(0)\n"
"	jmp	L22\n"
"L25:\n"
"	fldz\n"
"	movl	8(%ebp), %eax\n"
"	fsts	_tab(,%eax,4)\n"
"	jmp	L1\n"
"L24:\n"
"	flds	_tab(,%edx,4)\n"
"	jmp	L1\n"
"LC3:\n"
"	.ascii \"%d\\0\"\n"
"LC6:\n"
"	.ascii \"Case %d: %.2f\\12\\0\"\n"
"LC4:\n"
"	.ascii \" %*s %d %d\\0\"\n"
"_main2:\n"
"	pushl	%ebp\n"
"	movl	%esp, %ebp\n"
"	pushl	%edi\n"
"	pushl	%esi\n"
"	pushl	%ebx\n"
"	subl	$28, %esp\n"
"	movl	$1, %edx\n"
"	movl	%edx, _id\n"
"L28:\n"
"	movl	$_n, %ebx\n"
"	movl	%ebx, 4(%esp)\n"
"	movl	$LC3, (%esp)\n"
"	call	scanf\n"
"	decl	%eax\n"
"	jne	L29\n"
"	movl	_n, %eax\n"
"	testl	%eax, %eax\n"
"	jle	L29\n"
"	addl	%eax, %eax\n"
"	movl	%eax, _n\n"
"	xorl	%edi, %edi\n"
"	cmpl	%eax, %edi\n"
"	jl	L37\n"
"	movl	_n, %ecx\n"
"L51:\n"
"	xorl	%edi, %edi\n"
"	cmpl	%ecx, %edi\n"
"	jge	L53\n"
"	.p2align 4,,15\n"
"L48:\n"
"	movl	%edi, %eax\n"
"	sall	$4, %eax\n"
"	addl	%edi, %eax\n"
"	movl	$0x0, %edx\n"
"	movl	%edx, _d(,%eax,4)\n"
"	leal	1(%edi), %ebx\n"
"	movl	%ebx, -24(%ebp)\n"
"	cmpl	%ecx, %ebx\n"
"	jge	L55\n"
"	movl	%ebx, %eax\n"
"	sall	$4, %eax\n"
"	addl	%edi, %eax\n"
"	leal	_d(,%eax,4), %esi\n"
"	.p2align 4,,15\n"
"L47:\n"
"	movl	%edi, %eax\n"
"	sall	$4, %eax\n"
"	addl	%ebx, %eax\n"
"	movl	%eax, -20(%ebp)\n"
"	movl	_x(,%edi,4), %edx\n"
"	movl	_x(,%ebx,4), %eax\n"
"	subl	%eax, %edx\n"
"	imull	%edx, %edx\n"
"	movl	_y(,%edi,4), %eax\n"
"	subl	_y(,%ebx,4), %eax\n"
"	imull	%eax, %eax\n"
"	addl	%eax, %edx\n"
"	pushl	%edx\n"
"	fildl	(%esp)\n"
"	addl	$4, %esp\n"
"	fld	%st(0)\n"
"	fsqrt\n"
"	fucom	%st(0)\n"
"	fnstsw	%ax\n"
"	sahf\n"
"	jp	L59\n"
"	jne	L59\n"
"	fstp	%st(1)\n"
"L46:\n"
"	fstps	-16(%ebp)\n"
"	movl	-16(%ebp), %eax\n"
"	movl	-20(%ebp), %edx\n"
"	movl	%eax, _d(,%edx,4)\n"
"	movl	%eax, (%esi)\n"
"	incl	%ebx\n"
"	addl	$64, %esi\n"
"	cmpl	%ecx, %ebx\n"
"	jl	L47\n"
"L55:\n"
"	movl	-24(%ebp), %edi\n"
"	cmpl	%ecx, %edi\n"
"	jl	L48\n"
"L53:\n"
"	movl	$0, (%esp)\n"
"	call	_f\n"
"	fstpl	8(%esp)\n"
"	movl	_id, %eax\n"
"	movl	%eax, 4(%esp)\n"
"	movl	$LC6, (%esp)\n"
"	call	printf\n"
"	incl	_id\n"
"	jmp	L28\n"
"	.p2align 4,,7\n"
"L59:\n"
"	fstp	%st(0)\n"
"	fstpl	(%esp)\n"
"	call	sqrt\n"
"	movl	_n, %ecx\n"
"	jmp	L46\n"
"	.p2align 4,,7\n"
"L37:\n"
"	leal	0(,%edi,4), %eax\n"
"	leal	_y(%eax), %edx\n"
"	movl	%edx, 8(%esp)\n"
"	addl	$_x, %eax\n"
"	movl	%eax, 4(%esp)\n"
"	movl	$LC4, (%esp)\n"
"	call	scanf\n"
"	incl	%edi\n"
"	movl	_n, %ecx\n"
"	cmpl	%ecx, %edi\n"
"	jl	L37\n"
"	jmp	L51\n"
"L29:\n"
"	xorl	%eax, %eax\n"
"	call	exit\n"
".lcomm _x,64\n"
".lcomm _y,64\n"
".lcomm _n,16\n"
".lcomm _id,16\n"
".lcomm _d,1024\n"
".lcomm _got,262144\n"
".lcomm _tab,262144\n"
);
}
