#!/usr/bin/python
import sys

n = int(open(sys.argv[1]).read())
for i in xrange(1, n+1):
    if i % 15 == 0:
        print 'Hop'
    elif i % 3 == 0:
        print 'Hoppity'
    elif i % 5 == 0:
        print 'Hophop'
