int main()
{
__asm__ __volatile__(
"	pushl	%ebp\n"
"	movl	%esp, %ebp\n"
"	pushl	%edi\n"
"	pushl	%esi\n"
"	pushl	%ebx\n"
"	subl	$92, %esp\n"
"	movl	$48, %ebx\n"
"L6:\n"
"	movl	$1, %edx\n"
"	movl	%edx, _isdig.3(,%ebx,4)\n"
"	incl	%ebx\n"
"	cmpl	$57, %ebx\n"
"	jle	L6\n"
"	movl	$48, %ebx\n"
"L11:\n"
"	movl	$1, %edx\n"
"	movl	%edx, _isdigm.4(,%ebx,4)\n"
"	incl	%ebx\n"
"	cmpl	$57, %ebx\n"
"	jle	L11\n"
"	movl	$1, %edi\n"
"	movl	%edi, _isdigm.4+180\n"
"	movl	$1048576, %esi\n"
"	movl	%esi, 8(%esp)\n"
"	movl	$_inbuf.0, -24(%ebp)\n"
"	movl	$_inbuf.0, %ebx\n"
"	movl	%ebx, 4(%esp)\n"
"	movl	$0, (%esp)\n"
"	call	read\n"
"	movl	$_outbuf.1, -28(%ebp)\n"
"	movzbl	_inbuf.0, %ecx\n"
"	movb	%cl, -45(%ebp)\n"
"	movl	_n.9, %eax\n"
"	movl	%eax, -64(%ebp)\n"
"L12:\n"
"	movsbl	-45(%ebp),%ecx\n"
"	movl	_isdigm.4(,%ecx,4), %edx\n"
"	testl	%edx, %edx\n"
"	jne	L102\n"
"L18:\n"
"	incl	-24(%ebp)\n"
"	movl	-24(%ebp), %edi\n"
"	movzbl	(%edi), %edx\n"
"	movb	%dl, -45(%ebp)\n"
"	movsbl	%dl,%esi\n"
"	movl	_isdigm.4(,%esi,4), %ebx\n"
"	testl	%ebx, %ebx\n"
"	je	L18\n"
"L102:\n"
"	cmpb	$45, -45(%ebp)\n"
"	je	L129\n"
"	movsbl	-45(%ebp),%edi\n"
"	leal	-48(%edi), %ebx\n"
"	incl	-24(%ebp)\n"
"	movl	-24(%ebp), %esi\n"
"	movzbl	(%esi), %edx\n"
"	movb	%dl, -45(%ebp)\n"
"	movsbl	%dl,%eax\n"
"	movl	_isdig.3(,%eax,4), %ecx\n"
"	testl	%ecx, %ecx\n"
"	je	L25\n"
"	movl	%eax, %edx\n"
"L30:\n"
"	leal	(%ebx,%ebx,4), %ecx\n"
"	leal	-48(%edx,%ecx,2), %ebx\n"
"	incl	-24(%ebp)\n"
"	movl	-24(%ebp), %edi\n"
"	movzbl	(%edi), %eax\n"
"	movb	%al, -45(%ebp)\n"
"	movsbl	%al,%esi\n"
"	movl	%esi, %edx\n"
"	movl	_isdig.3(,%esi,4), %ecx\n"
"	testl	%ecx, %ecx\n"
"	jne	L30\n"
"L25:\n"
"	testl	%ebx, %ebx\n"
"	jle	L128\n"
"	movl	%ebx, -40(%ebp)\n"
"	movl	%ebx, -64(%ebp)\n"
"	xorl	%ebx, %ebx\n"
"	xorl	%edx, %edx\n"
"	movl	%edx, _sum.6\n"
"	cmpl	-64(%ebp), %ebx\n"
"	jge	L107\n"
"L52:\n"
"	movsbl	-45(%ebp),%edi\n"
"	movl	_isdigm.4(,%edi,4), %esi\n"
"	testl	%esi, %esi\n"
"	jne	L109\n"
"	.p2align 4,,15\n"
"L39:\n"
"	incl	-24(%ebp)\n"
"	movl	-24(%ebp), %esi\n"
"	movzbl	(%esi), %ecx\n"
"	movb	%cl, -45(%ebp)\n"
"	movsbl	%cl,%edx\n"
"	movl	_isdigm.4(,%edx,4), %ecx\n"
"	testl	%ecx, %ecx\n"
"	je	L39\n"
"L109:\n"
"	cmpb	$45, -45(%ebp)\n"
"	je	L130\n"
"	movsbl	-45(%ebp),%ecx\n"
"	leal	-48(%ecx), %edi\n"
"	incl	-24(%ebp)\n"
"	movl	-24(%ebp), %eax\n"
"	movzbl	(%eax), %edx\n"
"	movb	%dl, -45(%ebp)\n"
"	movsbl	%dl,%eax\n"
"	movl	_isdig.3(,%eax,4), %esi\n"
"	testl	%esi, %esi\n"
"	je	L46\n"
"	movl	%eax, %edx\n"
"	.p2align 4,,15\n"
"L51:\n"
"	leal	(%edi,%edi,4), %ecx\n"
"	leal	-48(%edx,%ecx,2), %edi\n"
"	incl	-24(%ebp)\n"
"	movl	-24(%ebp), %esi\n"
"	movzbl	(%esi), %eax\n"
"	movb	%al, -45(%ebp)\n"
"	movsbl	%al,%ecx\n"
"	movl	%ecx, %edx\n"
"	movl	_isdig.3(,%ecx,4), %esi\n"
"	testl	%esi, %esi\n"
"	jne	L51\n"
"L46:\n"
"	movl	%edi, _a.5(,%ebx,4)\n"
"	movl	_sum.6(,%ebx,4), %edx\n"
"	addl	%edx, %edi\n"
"	movl	%edi, _sum.6+4(,%ebx,4)\n"
"	incl	%ebx\n"
"	cmpl	-40(%ebp), %ebx\n"
"	jl	L52\n"
"L107:\n"
"	xorl	%ebx, %ebx\n"
"	cmpl	-40(%ebp), %ebx\n"
"	jg	L116\n"
"L57:\n"
"	xorl	%eax, %eax\n"
"	movl	%eax, _rx.7(,%ebx,4)\n"
"	incl	%ebx\n"
"	cmpl	-40(%ebp), %ebx\n"
"	jle	L57\n"
"	xorl	%ebx, %ebx\n"
"	cmpl	-40(%ebp), %ebx\n"
"	jg	L116\n"
"L62:\n"
"	xorl	%edi, %edi\n"
"	movl	%edi, _ry.8(,%ebx,4)\n"
"	incl	%ebx\n"
"	cmpl	-40(%ebp), %ebx\n"
"	jle	L62\n"
"L116:\n"
"	movl	$1, -20(%ebp)\n"
"	movl	-40(%ebp), %ebx\n"
"	cmpl	%ebx, -20(%ebp)\n"
"	jg	L118\n"
"	movl	$128, -60(%ebp)\n"
"	movl	$128, -72(%ebp)\n"
"L84:\n"
"	xorl	%edi, %edi\n"
"	movl	-40(%ebp), %esi\n"
"	cmpl	%esi, -20(%ebp)\n"
"	jg	L120\n"
"	movl	-20(%ebp), %ebx\n"
"	movl	%ebx, -44(%ebp)\n"
"	movl	-72(%ebp), %eax\n"
"	movl	%eax, -56(%ebp)\n"
"	movl	-60(%ebp), %edx\n"
"	movl	%edx, -32(%ebp)\n"
"	movl	%eax, -52(%ebp)\n"
"	movl	%edx, -36(%ebp)\n"
"	movl	%ebx, %ecx\n"
"	sall	$9, %ecx\n"
"	addl	$_ry.8, %ecx\n"
"	movl	%ecx, -68(%ebp)\n"
"	.p2align 4,,15\n"
"L83:\n"
"	movl	-56(%ebp), %esi\n"
"	movl	_ry.8-508(,%esi,4), %ebx\n"
"	movl	_a.5(,%edi,4), %edx\n"
"	addl	%edx, %ebx\n"
"	movl	%ebx, _rx.7(,%esi,4)\n"
"	xorl	%ecx, %ecx\n"
"	movl	$1, %ebx\n"
"	cmpl	-20(%ebp), %ebx\n"
"	jg	L124\n"
"	movl	-32(%ebp), %eax\n"
"	addl	%edi, %eax\n"
"	movl	%eax, -76(%ebp)\n"
"	movl	-52(%ebp), %edx\n"
"	addl	$-128, %edx\n"
"	.p2align 4,,15\n"
"L76:\n"
"	leal	(%ebx,%edi), %eax\n"
"	movl	_a.5-4(,%eax,4), %esi\n"
"	addl	%esi, %ecx\n"
"	leal	(%eax,%edx), %eax\n"
"	movl	_ry.8(,%eax,4), %esi\n"
"	leal	(%esi,%ecx), %eax\n"
"	movl	-76(%ebp), %esi\n"
"	cmpl	_rx.7(,%esi,4), %eax\n"
"	jle	L73\n"
"	movl	%eax, _rx.7(,%esi,4)\n"
"L73:\n"
"	incl	%ebx\n"
"	addl	$-128, %edx\n"
"	cmpl	-20(%ebp), %ebx\n"
"	jle	L76\n"
"	xorl	%ecx, %ecx\n"
"	movl	$1, %ebx\n"
"	cmpl	-20(%ebp), %ebx\n"
"	jg	L124\n"
"	movl	-36(%ebp), %esi\n"
"	addl	%edi, %esi\n"
"	movl	-68(%ebp), %edx\n"
"	subl	$512, %edx\n"
"	.p2align 4,,15\n"
"L82:\n"
"	movl	-44(%ebp), %eax\n"
"	subl	%ebx, %eax\n"
"	addl	_a.5(,%eax,4), %ecx\n"
"	movl	%ecx, %eax\n"
"	addl	(%edx), %eax\n"
"	cmpl	_rx.7(,%esi,4), %eax\n"
"	jle	L79\n"
"	movl	%eax, _rx.7(,%esi,4)\n"
"L79:\n"
"	incl	%ebx\n"
"	subl	$512, %edx\n"
"	cmpl	-20(%ebp), %ebx\n"
"	jle	L82\n"
"L124:\n"
"	movl	-44(%ebp), %ebx\n"
"	movl	_sum.6(,%ebx,4), %esi\n"
"	movl	_sum.6(,%edi,4), %ecx\n"
"	subl	%ecx, %esi\n"
"	movl	-56(%ebp), %edx\n"
"	movl	_rx.7(,%edx,4), %eax\n"
"	subl	%eax, %esi\n"
"	movl	%esi, _ry.8(,%edx,4)\n"
"	incl	%edi\n"
"	addl	$4, -68(%ebp)\n"
"	incl	%edx\n"
"	movl	%edx, -56(%ebp)\n"
"	movl	-20(%ebp), %ebx\n"
"	leal	(%ebx,%edi), %esi\n"
"	movl	%esi, -44(%ebp)\n"
"	movl	-40(%ebp), %ecx\n"
"	cmpl	%ecx, %esi\n"
"	jle	L83\n"
"L120:\n"
"	incl	-20(%ebp)\n"
"	subl	$-128, -72(%ebp)\n"
"	subl	$-128, -60(%ebp)\n"
"	movl	-40(%ebp), %edi\n"
"	cmpl	%edi, -20(%ebp)\n"
"	jle	L84\n"
"L118:\n"
"	movl	-40(%ebp), %edx\n"
"	sall	$9, %edx\n"
"	movl	_rx.7(%edx), %ebx\n"
"	movl	_ry.8(%edx), %esi\n"
"	subl	%esi, %ebx\n"
"	testl	%ebx, %ebx\n"
"	jne	L85\n"
"	movl	-28(%ebp), %eax\n"
"	movb	$48, (%eax)\n"
"	incl	%eax\n"
"	movl	%eax, -28(%ebp)\n"
"L86:\n"
"	movl	-28(%ebp), %eax\n"
"	movb	$10, (%eax)\n"
"	incl	%eax\n"
"	movl	%eax, -28(%ebp)\n"
"	jmp	L12\n"
"L85:\n"
"	jl	L131\n"
"L87:\n"
"	movl	$_tmp.2, %ecx\n"
"	testl	%ebx, %ebx\n"
"	jle	L126\n"
"	movl	$1717986919, %esi\n"
"L92:\n"
"	movl	%ebx, %eax\n"
"	imull	%esi\n"
"	movl	%eax, -88(%ebp)\n"
"	movl	%edx, -84(%ebp)\n"
"	movl	-84(%ebp), %edi\n"
"	sarl	$2, %edi\n"
"	movl	%ebx, %edx\n"
"	sarl	$31, %edx\n"
"	subl	%edx, %edi\n"
"	leal	(%edi,%edi,4), %edx\n"
"	addl	%edx, %edx\n"
"	subl	%edx, %ebx\n"
"	movb	%bl, %dl\n"
"	addb	$48, %dl\n"
"	movb	%dl, (%ecx)\n"
"	incl	%ecx\n"
"	movl	%edi, %ebx\n"
"	testl	%edi, %edi\n"
"	jg	L92\n"
"L126:\n"
"	decl	%ecx\n"
"	cmpl	$_tmp.2-1, %ecx\n"
"	jbe	L86\n"
"L96:\n"
"	movzbl	(%ecx), %edx\n"
"	movl	-28(%ebp), %ebx\n"
"	movb	%dl, (%ebx)\n"
"	incl	%ebx\n"
"	movl	%ebx, -28(%ebp)\n"
"	decl	%ecx\n"
"	cmpl	$_tmp.2-1, %ecx\n"
"	ja	L96\n"
"	jmp	L86\n"
"L131:\n"
"	negl	%ebx\n"
"	movl	-28(%ebp), %ecx\n"
"	movb	$45, (%ecx)\n"
"	incl	%ecx\n"
"	movl	%ecx, -28(%ebp)\n"
"	jmp	L87\n"
"L130:\n"
"	incl	-24(%ebp)\n"
"	movl	-24(%ebp), %esi\n"
"	movsbl	(%esi),%edx\n"
"	leal	-48(%edx), %edi\n"
"	incl	%esi\n"
"	movl	%esi, -24(%ebp)\n"
"	movzbl	(%esi), %ecx\n"
"	movb	%cl, -45(%ebp)\n"
"	movsbl	%cl,%eax\n"
"	movl	_isdig.3(,%eax,4), %edx\n"
"	testl	%edx, %edx\n"
"	je	L111\n"
"	movl	%eax, %edx\n"
"L45:\n"
"	leal	(%edi,%edi,4), %ecx\n"
"	leal	-48(%edx,%ecx,2), %edi\n"
"	incl	-24(%ebp)\n"
"	movl	-24(%ebp), %esi\n"
"	movzbl	(%esi), %eax\n"
"	movb	%al, -45(%ebp)\n"
"	movsbl	%al,%ecx\n"
"	movl	%ecx, %edx\n"
"	movl	_isdig.3(,%ecx,4), %eax\n"
"	testl	%eax, %eax\n"
"	jne	L45\n"
"L111:\n"
"	negl	%edi\n"
"	jmp	L46\n"
"L129:\n"
"	incl	-24(%ebp)\n"
"	movl	-24(%ebp), %esi\n"
"	movsbl	(%esi),%edx\n"
"	leal	-48(%edx), %ebx\n"
"	incl	%esi\n"
"	movl	%esi, -24(%ebp)\n"
"	movzbl	(%esi), %ecx\n"
"	movb	%cl, -45(%ebp)\n"
"	movsbl	%cl,%eax\n"
"	movl	_isdig.3(,%eax,4), %ecx\n"
"	testl	%ecx, %ecx\n"
"	je	L104\n"
"	movl	%eax, %edx\n"
"L24:\n"
"	leal	(%ebx,%ebx,4), %edi\n"
"	leal	-48(%edx,%edi,2), %ebx\n"
"	incl	-24(%ebp)\n"
"	movl	-24(%ebp), %esi\n"
"	movzbl	(%esi), %ecx\n"
"	movb	%cl, -45(%ebp)\n"
"	movsbl	%cl,%edi\n"
"	movl	%edi, %edx\n"
"	movl	_isdig.3(,%edi,4), %eax\n"
"	testl	%eax, %eax\n"
"	jne	L24\n"
"L104:\n"
"	negl	%ebx\n"
"	jmp	L25\n"
"L128:\n"
"	movl	-64(%ebp), %edi\n"
"	movl	%edi, _n.9\n"
"	subl	$_outbuf.1, -28(%ebp)\n"
"	movl	-28(%ebp), %ecx\n"
"	movl	%ecx, 8(%esp)\n"
"	movl	$_outbuf.1, %esi\n"
"	movl	%esi, 4(%esp)\n"
"	movl	$1, (%esp)\n"
"	call	write\n"
"	movl	$0, (%esp)\n"
"	call	exit\n"
".lcomm _n.9,16\n"
".lcomm _a.5,1024\n"
".lcomm _sum.6,1024\n"
".lcomm _rx.7,65536\n"
".lcomm _ry.8,65536\n"
".lcomm _tmp.2,256\n"
".lcomm _isdig.3,1024\n"
".lcomm _isdigm.4,1024\n"
".lcomm _inbuf.0,1048576\n"
".lcomm _outbuf.1,1048576\n"
);
}
