int main()
{
__asm__ __volatile__(
"	pushl	%ebp\n"
"	movl	%esp, %ebp\n"
"	pushl	%edi\n"
"	pushl	%esi\n"
"	pushl	%ebx\n"
"	subl	$44, %esp\n"
"	movl	$48, -24(%ebp)\n"
"	.p2align 4,,15\n"
"L6:\n"
"	movl	-24(%ebp), %edx\n"
"	movl	$1, %eax\n"
"	movl	%eax, _isdig.3(,%edx,4)\n"
"	incl	%edx\n"
"	movl	%edx, -24(%ebp)\n"
"	cmpl	$57, %edx\n"
"	jle	L6\n"
"	movl	$1048576, %ebx\n"
"	movl	%ebx, 8(%esp)\n"
"	movl	$_inbuf.0, %edi\n"
"	movl	%edi, 4(%esp)\n"
"	movl	$0, (%esp)\n"
"	call	read\n"
"	movl	$_outbuf.1, %esi\n"
"	movsbl	_inbuf.0,%ecx\n"
"	movl	_isdig.3(,%ecx,4), %edx\n"
"	testl	%edx, %edx\n"
"	jne	L118\n"
"	.p2align 4,,15\n"
"L10:\n"
"	incl	%edi\n"
"	movzbl	(%edi), %edx\n"
"	movsbl	%dl,%ecx\n"
"	movl	_isdig.3(,%ecx,4), %ebx\n"
"	testl	%ebx, %ebx\n"
"	je	L10\n"
"L92:\n"
"	movsbl	%dl,%ecx\n"
"	subl	$48, %ecx\n"
"	movl	%ecx, -32(%ebp)\n"
"	incl	%edi\n"
"	movsbl	(%edi),%eax\n"
"	movl	_isdig.3(,%eax,4), %ebx\n"
"	testl	%ebx, %ebx\n"
"	je	L94\n"
"	movl	%eax, %edx\n"
"	.p2align 4,,15\n"
"L15:\n"
"	movl	-32(%ebp), %ebx\n"
"	leal	(%ebx,%ebx,4), %eax\n"
"	leal	-48(%edx,%eax,2), %ebx\n"
"	movl	%ebx, -32(%ebp)\n"
"	incl	%edi\n"
"	movsbl	(%edi),%ecx\n"
"	movl	%ecx, %edx\n"
"	movl	_isdig.3(,%ecx,4), %ebx\n"
"	testl	%ebx, %ebx\n"
"	jne	L15\n"
"L94:\n"
"	movl	$1, -28(%ebp)\n"
"	movl	-32(%ebp), %edx\n"
"	cmpl	%edx, -28(%ebp)\n"
"	jg	L96\n"
"	.p2align 4,,15\n"
"L88:\n"
"	movb	$67, (%esi)\n"
"	incl	%esi\n"
"	movb	$97, (%esi)\n"
"	incl	%esi\n"
"	movb	$115, (%esi)\n"
"	incl	%esi\n"
"	movb	$101, (%esi)\n"
"	incl	%esi\n"
"	movb	$32, (%esi)\n"
"	incl	%esi\n"
"	movb	$35, (%esi)\n"
"	incl	%esi\n"
"	movl	-28(%ebp), %ecx\n"
"	cmpl	$0, %ecx\n"
"	jne	L20\n"
"	movb	$48, (%esi)\n"
"	incl	%esi\n"
"L21:\n"
"	movb	$58, (%esi)\n"
"	incl	%esi\n"
"	movb	$32, (%esi)\n"
"	incl	%esi\n"
"	movzbl	(%edi), %edx\n"
"	movsbl	%dl,%ebx\n"
"	movl	_isdig.3(,%ebx,4), %ecx\n"
"	testl	%ecx, %ecx\n"
"	jne	L101\n"
"	.p2align 4,,15\n"
"L34:\n"
"	incl	%edi\n"
"	movzbl	(%edi), %edx\n"
"	movsbl	%dl,%ecx\n"
"	movl	_isdig.3(,%ecx,4), %ebx\n"
"	testl	%ebx, %ebx\n"
"	je	L34\n"
"L101:\n"
"	movsbl	%dl,%ecx\n"
"	subl	$48, %ecx\n"
"	movl	%ecx, -24(%ebp)\n"
"	incl	%edi\n"
"	movsbl	(%edi),%eax\n"
"	movl	_isdig.3(,%eax,4), %ebx\n"
"	testl	%ebx, %ebx\n"
"	je	L43\n"
"	movl	%eax, %edx\n"
"	.p2align 4,,15\n"
"L39:\n"
"	movl	-24(%ebp), %eax\n"
"	leal	(%eax,%eax,4), %ebx\n"
"	leal	-48(%edx,%ebx,2), %ecx\n"
"	movl	%ecx, -24(%ebp)\n"
"	incl	%edi\n"
"	movsbl	(%edi),%ebx\n"
"	movl	%ebx, %edx\n"
"	movl	_isdig.3(,%ebx,4), %eax\n"
"	testl	%eax, %eax\n"
"	jne	L39\n"
"	.p2align 4,,15\n"
"L43:\n"
"	incl	%edi\n"
"	movzbl	(%edi), %ecx\n"
"	movsbl	%cl,%eax\n"
"	movl	_isdig.3(,%eax,4), %edx\n"
"	testl	%edx, %edx\n"
"	je	L43\n"
"	leal	-48(%eax), %ebx\n"
"	incl	%edi\n"
"	movsbl	(%edi),%eax\n"
"	movl	_isdig.3(,%eax,4), %ecx\n"
"	testl	%ecx, %ecx\n"
"	je	L52\n"
"	movl	%eax, %edx\n"
"	.p2align 4,,15\n"
"L48:\n"
"	leal	(%ebx,%ebx,4), %ecx\n"
"	leal	-48(%edx,%ecx,2), %ebx\n"
"	incl	%edi\n"
"	movsbl	(%edi),%ecx\n"
"	movl	%ecx, %edx\n"
"	movl	_isdig.3(,%ecx,4), %ecx\n"
"	testl	%ecx, %ecx\n"
"	jne	L48\n"
"	.p2align 4,,15\n"
"L52:\n"
"	incl	%edi\n"
"	movzbl	(%edi), %ecx\n"
"	movsbl	%cl,%eax\n"
"	movl	_isdig.3(,%eax,4), %edx\n"
"	testl	%edx, %edx\n"
"	je	L52\n"
"	leal	-48(%eax), %ecx\n"
"	incl	%edi\n"
"	movsbl	(%edi),%eax\n"
"	movl	_isdig.3(,%eax,4), %edx\n"
"	testl	%edx, %edx\n"
"	je	L111\n"
"	movl	%eax, %edx\n"
"	.p2align 4,,15\n"
"L57:\n"
"	leal	(%ecx,%ecx,4), %eax\n"
"	leal	-48(%edx,%eax,2), %ecx\n"
"	incl	%edi\n"
"	movsbl	(%edi),%eax\n"
"	movl	%eax, %edx\n"
"	movl	_isdig.3(,%eax,4), %eax\n"
"	testl	%eax, %eax\n"
"	jne	L57\n"
"L111:\n"
"	cmpl	$100, -24(%ebp)\n"
"	jg	L60\n"
"	cmpl	$100, %ebx\n"
"	jg	L60\n"
"	cmpl	$100, %ecx\n"
"	jg	L60\n"
"	movl	-24(%ebp), %eax\n"
"	addl	%ebx, %eax\n"
"	addl	%ecx, %eax\n"
"	leal	-100(%eax), %edx\n"
"	testl	%edx, %edx\n"
"	jle	L120\n"
"	leal	-99(%eax), %edx\n"
"	sarl	%edx\n"
"L62:\n"
"	movl	-24(%ebp), %eax\n"
"	movl	%eax, -20(%ebp)\n"
"	cmpl	%eax, %ebx\n"
"	jge	L63\n"
"	movl	%ebx, -20(%ebp)\n"
"L63:\n"
"	cmpl	-20(%ebp), %ecx\n"
"	jge	L64\n"
"	movl	%ecx, -20(%ebp)\n"
"L64:\n"
"	cmpl	%edx, -20(%ebp)\n"
"	jl	L60\n"
"	movb	$66, (%esi)\n"
"	incl	%esi\n"
"	movb	$101, (%esi)\n"
"	incl	%esi\n"
"	movb	$116, (%esi)\n"
"	incl	%esi\n"
"	movb	$119, (%esi)\n"
"	incl	%esi\n"
"	movb	$101, (%esi)\n"
"	incl	%esi\n"
"	movb	$101, (%esi)\n"
"	incl	%esi\n"
"	movb	$110, (%esi)\n"
"	incl	%esi\n"
"	movb	$32, (%esi)\n"
"	incl	%esi\n"
"	movl	%edx, %ecx\n"
"	testl	%edx, %edx\n"
"	jne	L66\n"
"	movb	$48, (%esi)\n"
"	incl	%esi\n"
"L67:\n"
"	movb	$32, (%esi)\n"
"	incl	%esi\n"
"	movb	$97, (%esi)\n"
"	incl	%esi\n"
"	movb	$110, (%esi)\n"
"	incl	%esi\n"
"	movb	$100, (%esi)\n"
"	incl	%esi\n"
"	movb	$32, (%esi)\n"
"	incl	%esi\n"
"	movl	-20(%ebp), %ecx\n"
"	testl	%ecx, %ecx\n"
"	jne	L77\n"
"	movb	$48, (%esi)\n"
"	incl	%esi\n"
"L78:\n"
"	movb	$32, (%esi)\n"
"	incl	%esi\n"
"	movb	$116, (%esi)\n"
"	incl	%esi\n"
"	movb	$105, (%esi)\n"
"	incl	%esi\n"
"	movb	$109, (%esi)\n"
"	incl	%esi\n"
"	movb	$101, (%esi)\n"
"	incl	%esi\n"
"	movb	$115, (%esi)\n"
"	.p2align 4,,15\n"
"L119:\n"
"	incl	%esi\n"
"	movb	$46, (%esi)\n"
"	incl	%esi\n"
"	movb	$10, (%esi)\n"
"	incl	%esi\n"
"	incl	-28(%ebp)\n"
"	movl	-32(%ebp), %ebx\n"
"	cmpl	%ebx, -28(%ebp)\n"
"	jle	L88\n"
"	jmp	L96\n"
"L77:\n"
"	movl	$_tmp.2, %ebx\n"
"	jle	L116\n"
"L83:\n"
"	movl	$1717986919, %eax\n"
"	imull	%ecx\n"
"	sarl	$2, %edx\n"
"	movl	%ecx, %eax\n"
"	sarl	$31, %eax\n"
"	subl	%eax, %edx\n"
"	leal	(%edx,%edx,4), %eax\n"
"	addl	%eax, %eax\n"
"	subl	%eax, %ecx\n"
"	movb	%cl, %al\n"
"	addb	$48, %al\n"
"	movb	%al, (%ebx)\n"
"	incl	%ebx\n"
"	movl	%edx, %ecx\n"
"	testl	%edx, %edx\n"
"	jg	L83\n"
"L116:\n"
"	decl	%ebx\n"
"	cmpl	$_tmp.2-1, %ebx\n"
"	jbe	L78\n"
"L87:\n"
"	movzbl	(%ebx), %ecx\n"
"	movb	%cl, (%esi)\n"
"	incl	%esi\n"
"	decl	%ebx\n"
"	cmpl	$_tmp.2-1, %ebx\n"
"	ja	L87\n"
"	jmp	L78\n"
"L66:\n"
"	movl	$_tmp.2, %ebx\n"
"	jle	L113\n"
"L72:\n"
"	movl	$1717986919, %eax\n"
"	imull	%ecx\n"
"	sarl	$2, %edx\n"
"	movl	%ecx, %eax\n"
"	sarl	$31, %eax\n"
"	subl	%eax, %edx\n"
"	leal	(%edx,%edx,4), %eax\n"
"	addl	%eax, %eax\n"
"	subl	%eax, %ecx\n"
"	movb	%cl, %al\n"
"	addb	$48, %al\n"
"	movb	%al, (%ebx)\n"
"	incl	%ebx\n"
"	movl	%edx, %ecx\n"
"	testl	%edx, %edx\n"
"	jg	L72\n"
"L113:\n"
"	decl	%ebx\n"
"	cmpl	$_tmp.2-1, %ebx\n"
"	jbe	L67\n"
"L76:\n"
"	movzbl	(%ebx), %edx\n"
"	movb	%dl, (%esi)\n"
"	incl	%esi\n"
"	decl	%ebx\n"
"	cmpl	$_tmp.2-1, %ebx\n"
"	ja	L76\n"
"	jmp	L67\n"
"	.p2align 4,,7\n"
"L60:\n"
"	movb	$84, (%esi)\n"
"	incl	%esi\n"
"	movb	$104, (%esi)\n"
"	incl	%esi\n"
"	movb	$101, (%esi)\n"
"	incl	%esi\n"
"	movb	$32, (%esi)\n"
"	incl	%esi\n"
"	movb	$114, (%esi)\n"
"	incl	%esi\n"
"	movb	$101, (%esi)\n"
"	incl	%esi\n"
"	movb	$99, (%esi)\n"
"	incl	%esi\n"
"	movb	$111, (%esi)\n"
"	incl	%esi\n"
"	movb	$114, (%esi)\n"
"	incl	%esi\n"
"	movb	$100, (%esi)\n"
"	incl	%esi\n"
"	movb	$115, (%esi)\n"
"	incl	%esi\n"
"	movb	$32, (%esi)\n"
"	incl	%esi\n"
"	movb	$97, (%esi)\n"
"	incl	%esi\n"
"	movb	$114, (%esi)\n"
"	incl	%esi\n"
"	movb	$101, (%esi)\n"
"	incl	%esi\n"
"	movb	$32, (%esi)\n"
"	incl	%esi\n"
"	movb	$102, (%esi)\n"
"	incl	%esi\n"
"	movb	$97, (%esi)\n"
"	incl	%esi\n"
"	movb	$117, (%esi)\n"
"	incl	%esi\n"
"	movb	$108, (%esi)\n"
"	incl	%esi\n"
"	movb	$116, (%esi)\n"
"	incl	%esi\n"
"	movb	$121, (%esi)\n"
"	jmp	L119\n"
"L120:\n"
"	xorl	%edx, %edx\n"
"	jmp	L62\n"
"	.p2align 4,,7\n"
"L20:\n"
"	movl	$_tmp.2, %ebx\n"
"	jle	L98\n"
"	.p2align 4,,15\n"
"L26:\n"
"	movl	$1717986919, %eax\n"
"	imull	%ecx\n"
"	movl	%eax, -40(%ebp)\n"
"	movl	%edx, -36(%ebp)\n"
"	movl	-36(%ebp), %edx\n"
"	sarl	$2, %edx\n"
"	movl	%ecx, %eax\n"
"	sarl	$31, %eax\n"
"	subl	%eax, %edx\n"
"	leal	(%edx,%edx,4), %eax\n"
"	addl	%eax, %eax\n"
"	subl	%eax, %ecx\n"
"	movb	%cl, %al\n"
"	addb	$48, %al\n"
"	movb	%al, (%ebx)\n"
"	incl	%ebx\n"
"	movl	%edx, %ecx\n"
"	testl	%edx, %edx\n"
"	jg	L26\n"
"L98:\n"
"	decl	%ebx\n"
"	cmpl	$_tmp.2-1, %ebx\n"
"	jbe	L21\n"
"	.p2align 4,,15\n"
"L30:\n"
"	movzbl	(%ebx), %ecx\n"
"	movb	%cl, (%esi)\n"
"	incl	%esi\n"
"	decl	%ebx\n"
"	cmpl	$_tmp.2-1, %ebx\n"
"	ja	L30\n"
"	jmp	L21\n"
"L118:\n"
"	movzbl	_inbuf.0, %edx\n"
"	jmp	L92\n"
"L96:\n"
"	subl	$_outbuf.1, %esi\n"
"	movl	%esi, 8(%esp)\n"
"	movl	$_outbuf.1, %esi\n"
"	movl	%esi, 4(%esp)\n"
"	movl	$1, (%esp)\n"
"	call	write\n"
"	movl	$0, (%esp)\n"
"	call	exit\n"
".lcomm _tmp.2,256\n"
".lcomm _isdig.3,1024\n"
".lcomm _inbuf.0,1048576\n"
".lcomm _outbuf.1,1048576\n"
);
}
