int main()
{
__asm__ __volatile__(
"	jmp	_main2\n"
"	.p2align 4,,15\n"
"_sort:\n"
"	pushl	%ebp\n"
"	movl	%esp, %ebp\n"
"	pushl	%edi\n"
"	pushl	%esi\n"
"	pushl	%ebx\n"
"	subl	$8, %esp\n"
"	movl	8(%ebp), %edi\n"
"L2:\n"
"	cmpl	$31, 12(%ebp)\n"
"	jle	L36\n"
"	xorl	%esi, %esi\n"
"	movl	12(%ebp), %edx\n"
"	decl	%edx\n"
"	movl	12(%ebp), %eax\n"
"	incl	%eax\n"
"	sarl	%eax\n"
"	movl	(%edi,%eax,4), %ebx\n"
"	.p2align 4,,15\n"
"L15:\n"
"	movl	(%edi,%esi,4), %ecx\n"
"	cmpl	%ebx, %ecx\n"
"	jge	L33\n"
"	.p2align 4,,15\n"
"L21:\n"
"	incl	%esi\n"
"	movl	(%edi,%esi,4), %ecx\n"
"	cmpl	%ebx, %ecx\n"
"	jl	L21\n"
"L33:\n"
"	movl	(%edi,%edx,4), %eax\n"
"	cmpl	%ebx, %eax\n"
"	jle	L35\n"
"	.p2align 4,,15\n"
"L25:\n"
"	decl	%edx\n"
"	movl	(%edi,%edx,4), %eax\n"
"	cmpl	%ebx, %eax\n"
"	jg	L25\n"
"L35:\n"
"	cmpl	%edx, %esi\n"
"	jge	L16\n"
"	movl	%eax, (%edi,%esi,4)\n"
"	incl	%esi\n"
"	movl	%ecx, (%edi,%edx,4)\n"
"	decl	%edx\n"
"	jmp	L15\n"
"L16:\n"
"	movl	12(%ebp), %eax\n"
"	subl	%esi, %eax\n"
"	cmpl	$1, %eax\n"
"	jg	L37\n"
"L27:\n"
"	movl	%esi, 12(%ebp)\n"
"	jmp	L2\n"
"L37:\n"
"	movl	%eax, 4(%esp)\n"
"	leal	(%edi,%esi,4), %eax\n"
"	movl	%eax, (%esp)\n"
"	call	_sort\n"
"	jmp	L27\n"
"L36:\n"
"	movl	$1, %esi\n"
"	cmpl	12(%ebp), %esi\n"
"	jge	L1\n"
"L14:\n"
"	movl	(%edi,%esi,4), %ecx\n"
"	movl	%esi, %edx\n"
"	decl	%edx\n"
"	js	L9\n"
"	movl	(%edi,%edx,4), %eax\n"
"	cmpl	%ecx, %eax\n"
"	jle	L9\n"
"L13:\n"
"	movl	%eax, 4(%edi,%edx,4)\n"
"	decl	%edx\n"
"	js	L9\n"
"	movl	(%edi,%edx,4), %eax\n"
"	cmpl	%ecx, %eax\n"
"	jg	L13\n"
"L9:\n"
"	movl	%ecx, 4(%edi,%edx,4)\n"
"	incl	%esi\n"
"	cmpl	12(%ebp), %esi\n"
"	jl	L14\n"
"L1:\n"
"	addl	$8, %esp\n"
"	popl	%ebx\n"
"	popl	%esi\n"
"	popl	%edi\n"
"	popl	%ebp\n"
"	ret\n"
"	.p2align 4,,15\n"
"_xmake:\n"
"	pushl	%ebp\n"
"	movl	%esp, %ebp\n"
"	pushl	%edi\n"
"	pushl	%esi\n"
"	pushl	%ebx\n"
"	movl	$1, %esi\n"
"L49:\n"
"	movl	%esi, %eax\n"
"	sarl	$5, %eax\n"
"	movl	%esi, %ecx\n"
"	andl	$31, %ecx\n"
"	movl	_sieve.0(,%eax,4), %eax\n"
"	shrl	%cl, %eax\n"
"	leal	1(%esi), %edi\n"
"	testb	$1, %al\n"
"	je	L76\n"
"L41:\n"
"	movl	%edi, %esi\n"
"	cmpl	$1117, %edi\n"
"	jle	L49\n"
"	xorl	%esi, %esi\n"
"	movl	$1, %ebx\n"
"	movl	$3, %edi\n"
"	.p2align 4,,15\n"
"L60:\n"
"	movl	%ebx, %eax\n"
"	sarl	$5, %eax\n"
"	movl	%ebx, %ecx\n"
"	andl	$31, %ecx\n"
"	movl	_sieve.0(,%eax,4), %eax\n"
"	shrl	%cl, %eax\n"
"	testb	$1, %al\n"
"	je	L77\n"
"L52:\n"
"	incl	%ebx\n"
"	addl	$2, %edi\n"
"	cmpl	$1250003, %ebx\n"
"	jle	L60\n"
"	movl	$1250004, %ebx\n"
"	movl	$5000018, %edx\n"
"L66:\n"
"	movl	%ebx, %eax\n"
"	sarl	$5, %eax\n"
"	movl	%ebx, %ecx\n"
"	andl	$31, %ecx\n"
"	movl	_sieve.0(,%eax,4), %eax\n"
"	shrl	%cl, %eax\n"
"	testb	$1, %al\n"
"	jne	L63\n"
"	movl	%edx, _X(,%esi,4)\n"
"	incl	%esi\n"
"L63:\n"
"	incl	%ebx\n"
"	addl	$4, %edx\n"
"	cmpl	$2499999, %ebx\n"
"	jle	L66\n"
"	movl	%esi, _Xn\n"
"	xorl	%eax, %eax\n"
"	movl	%eax, _X(,%esi,4)\n"
"	popl	%ebx\n"
"	popl	%esi\n"
"	popl	%edi\n"
"	popl	%ebp\n"
"	ret\n"
"	.p2align 4,,7\n"
"L77:\n"
"	leal	(%edi,%edi), %edx\n"
"	cmpl	$10000000, %edx\n"
"	jg	L52\n"
"	.p2align 4,,15\n"
"L59:\n"
"	movl	%edx, _X(,%esi,4)\n"
"	incl	%esi\n"
"	addl	%edx, %edx\n"
"	cmpl	$10000000, %edx\n"
"	jle	L59\n"
"	jmp	L52\n"
"L76:\n"
"	leal	1(%esi,%esi), %edx\n"
"	imull	%edi, %esi\n"
"	leal	(%esi,%esi), %ebx\n"
"	cmpl	$2499999, %ebx\n"
"	jg	L41\n"
"L48:\n"
"	movl	%ebx, %eax\n"
"	sarl	$5, %eax\n"
"	movl	%ebx, %ecx\n"
"	andl	$31, %ecx\n"
"	movl	$1, %esi\n"
"	sall	%cl, %esi\n"
"	orl	%esi, _sieve.0(,%eax,4)\n"
"	addl	%edx, %ebx\n"
"	cmpl	$2499999, %ebx\n"
"	jle	L48\n"
"	jmp	L41\n"
"	.p2align 4,,15\n"
"_sigma:\n"
"	pushl	%ebp\n"
"	movl	%esp, %ebp\n"
"	movl	8(%ebp), %edx\n"
"	xorl	%eax, %eax\n"
"	testb	$1, %dl\n"
"	jne	L85\n"
"	.p2align 4,,15\n"
"L83:\n"
"	incl	%eax\n"
"	sarl	%edx\n"
"	testb	$1, %dl\n"
"	je	L83\n"
"L85:\n"
"	leal	1(%eax), %ecx\n"
"	movl	$1, %eax\n"
"	sall	%cl, %eax\n"
"	decl	%eax\n"
"	incl	%edx\n"
"	imull	%edx, %eax\n"
"	popl	%ebp\n"
"	ret\n"
"LC0:\n"
"	.ascii \"%d\\0\"\n"
"LC1:\n"
"	.ascii \"%d %lld\\12\\0\"\n"
"	.p2align 4,,15\n"
"_main2:\n"
"	pushl	%ebp\n"
"	movl	%esp, %ebp\n"
"	pushl	%edi\n"
"	pushl	%esi\n"
"	pushl	%ebx\n"
"	subl	$28, %esp\n"
"	call	_xmake\n"
"	movl	_Xn, %eax\n"
"	movl	%eax, 4(%esp)\n"
"	movl	$_X, (%esp)\n"
"	call	_sort\n"
"	movl	_X, %eax\n"
"	movl	%eax, (%esp)\n"
"	call	_sigma\n"
"	movl	_X, %edx\n"
"	addl	%edx, %edx\n"
"	subl	%edx, %eax\n"
"	movl	%eax, _S\n"
"	cltd\n"
"	movl	%edx, _S+4\n"
"	movl	$1, %esi\n"
"	cmpl	_Xn, %esi\n"
"	jge	L112\n"
"	movl	$_S, %edi\n"
"	.p2align 4,,15\n"
"L91:\n"
"	movl	_X(,%esi,4), %eax\n"
"	movl	%eax, (%esp)\n"
"	call	_sigma\n"
"	movl	%eax, %ecx\n"
"	movl	%eax, %ebx\n"
"	sarl	$31, %ebx\n"
"	addl	-8(%edi,%esi,8), %ecx\n"
"	adcl	-4(%edi,%esi,8), %ebx\n"
"	movl	_X(,%esi,4), %eax\n"
"	addl	%eax, %eax\n"
"	cltd\n"
"	subl	%eax, %ecx\n"
"	sbbl	%edx, %ebx\n"
"	movl	%ecx, _S(,%esi,8)\n"
"	movl	%ebx, _S+4(,%esi,8)\n"
"	incl	%esi\n"
"	cmpl	_Xn, %esi\n"
"	jl	L91\n"
"L112:\n"
"	leal	-16(%ebp), %edi\n"
"	.p2align 4,,15\n"
"L92:\n"
"	movl	%edi, 4(%esp)\n"
"	movl	$LC0, (%esp)\n"
"	call	scanf\n"
"	decl	%eax\n"
"	jne	L93\n"
"	movl	-16(%ebp), %ecx\n"
"	testl	%ecx, %ecx\n"
"	jle	L93\n"
"	xorl	%esi, %esi\n"
"	movl	_Xn, %ebx\n"
"	leal	-1(%ebx), %edx\n"
"	cmpl	%edx, %esi\n"
"	jge	L114\n"
"	.p2align 4,,15\n"
"L104:\n"
"	leal	1(%edx,%esi), %eax\n"
"	sarl	%eax\n"
"	cmpl	%ecx, _X(,%eax,4)\n"
"	jge	L100\n"
"	movl	%eax, %esi\n"
"L96:\n"
"	cmpl	%edx, %esi\n"
"	jl	L104\n"
"L114:\n"
"	leal	1(%esi), %eax\n"
"	cmpl	%ebx, %eax\n"
"	jge	L106\n"
"	movl	$_X, %edx\n"
"	cmpl	%ecx, 4(%edx,%esi,4)\n"
"	jge	L106\n"
"	.p2align 4,,15\n"
"L109:\n"
"	movl	%eax, %esi\n"
"	leal	1(%eax), %eax\n"
"	cmpl	%ebx, %eax\n"
"	jge	L106\n"
"	cmpl	%ecx, 4(%edx,%esi,4)\n"
"	jl	L109\n"
"	.p2align 4,,15\n"
"L106:\n"
"	movl	_S(,%esi,8), %eax\n"
"	movl	_S+4(,%esi,8), %edx\n"
"	movl	%eax, 8(%esp)\n"
"	movl	%edx, 12(%esp)\n"
"	movl	%ecx, 4(%esp)\n"
"	movl	$LC1, (%esp)\n"
"	call	printf\n"
"	jmp	L92\n"
"	.p2align 4,,7\n"
"L100:\n"
"	jle	L102\n"
"	leal	-1(%eax), %edx\n"
"	jmp	L96\n"
"	.p2align 4,,7\n"
"L102:\n"
"	movl	%eax, %esi\n"
"	movl	%eax, %edx\n"
"	jmp	L96\n"
"L93:\n"
"	xor	%eax, %eax\n"
"	call	exit\n"
".lcomm _Xn,16\n"
".lcomm _sieve.0,312800\n"
".lcomm _X,2948240\n"
".lcomm _S,5896480\n"
);
}
