int main()
{
__asm__ __volatile__(
"	pushl	%ebp\n"
"	movl	%esp, %ebp\n"
"	pushl	%edi\n"
"	pushl	%esi\n"
"	pushl	%ebx\n"
"	subl	$60, %esp\n"
"	movl	$0, -24(%ebp)\n"
"L11:\n"
"	xorl	%ecx, %ecx\n"
"	movl	-24(%ebp), %edx\n"
"	sall	$7, %edx\n"
"	.p2align 4,,15\n"
"L10:\n"
"	leal	(%ecx,%edx), %ebx\n"
"	movl	$1, %eax\n"
"	movl	%eax, _map(,%ebx,4)\n"
"	incl	%ecx\n"
"	cmpl	$127, %ecx\n"
"	jle	L10\n"
"	incl	-24(%ebp)\n"
"	cmpl	$127, -24(%ebp)\n"
"	jle	L11\n"
"	movl	$48, -24(%ebp)\n"
"L16:\n"
"	movl	-24(%ebp), %edx\n"
"	movl	$1, %ecx\n"
"	movl	%ecx, _isdig(,%edx,4)\n"
"	incl	%edx\n"
"	movl	%edx, -24(%ebp)\n"
"	cmpl	$57, %edx\n"
"	jle	L16\n"
"	movl	$1, %ecx\n"
"	movl	%ecx, _isnd+196\n"
"	movl	$1, %edx\n"
"	movl	%edx, _isnd+192\n"
"	movl	$1, %eax\n"
"	movl	%eax, _isnd+40\n"
"	movl	$1048576, %edi\n"
"	movl	%edi, 8(%esp)\n"
"	movl	$_inbuf, %edi\n"
"	movl	%edi, 4(%esp)\n"
"	movl	$0, (%esp)\n"
"	call	read\n"
"	movb	$10, _inbuf(%eax)\n"
"	movl	$_outbuf, -20(%ebp)\n"
"	movzbl	_inbuf, %esi\n"
"	movl	_isdig(,%esi,4), %ebx\n"
"	testl	%ebx, %ebx\n"
"	jne	L141\n"
"L20:\n"
"	incl	%edi\n"
"	movzbl	(%edi), %ebx\n"
"	movzbl	%bl, %edx\n"
"	movl	_isdig(,%edx,4), %esi\n"
"	testl	%esi, %esi\n"
"	je	L20\n"
"L111:\n"
"	movzbl	%bl, %edx\n"
"	subl	$48, %edx\n"
"	movl	%edx, -24(%ebp)\n"
"	incl	%edi\n"
"	movzbl	(%edi), %ebx\n"
"	movb	%bl, %dl\n"
"	movzbl	%bl, %esi\n"
"	movl	_isdig(,%esi,4), %ecx\n"
"	testl	%ecx, %ecx\n"
"	je	L113\n"
"L25:\n"
"	movl	-24(%ebp), %eax\n"
"	leal	(%eax,%eax,4), %esi\n"
"	movzbl	%dl, %ecx\n"
"	leal	-48(%ecx,%esi,2), %ebx\n"
"	movl	%ebx, -24(%ebp)\n"
"	incl	%edi\n"
"	movzbl	(%edi), %ebx\n"
"	movb	%bl, %dl\n"
"	movzbl	%bl, %esi\n"
"	movl	_isdig(,%esi,4), %ecx\n"
"	testl	%ecx, %ecx\n"
"	jne	L25\n"
"L113:\n"
"	movl	-24(%ebp), %edx\n"
"	decl	%edx\n"
"	movl	%edx, -40(%ebp)\n"
"	movl	%edx, _ntests\n"
"	incl	%edx\n"
"	je	L115\n"
"L103:\n"
"	movzbl	%bl, %esi\n"
"	movl	_isdig(,%esi,4), %ecx\n"
"	testl	%ecx, %ecx\n"
"	jne	L117\n"
"L32:\n"
"	incl	%edi\n"
"	movzbl	(%edi), %ebx\n"
"	movzbl	%bl, %ecx\n"
"	movl	_isdig(,%ecx,4), %edx\n"
"	testl	%edx, %edx\n"
"	je	L32\n"
"L117:\n"
"	movzbl	%bl, %edx\n"
"	subl	$48, %edx\n"
"	movl	%edx, -24(%ebp)\n"
"	incl	%edi\n"
"	movzbl	(%edi), %ebx\n"
"	movb	%bl, %dl\n"
"	movzbl	%bl, %ecx\n"
"	movl	_isdig(,%ecx,4), %esi\n"
"	testl	%esi, %esi\n"
"	je	L119\n"
"L37:\n"
"	movl	-24(%ebp), %ebx\n"
"	leal	(%ebx,%ebx,4), %eax\n"
"	movzbl	%dl, %esi\n"
"	leal	-48(%esi,%eax,2), %ebx\n"
"	movl	%ebx, -24(%ebp)\n"
"	incl	%edi\n"
"	movzbl	(%edi), %ebx\n"
"	movb	%bl, %dl\n"
"	movzbl	%bl, %ecx\n"
"	movl	_isdig(,%ecx,4), %esi\n"
"	testl	%esi, %esi\n"
"	jne	L37\n"
"L119:\n"
"	movl	-24(%ebp), %esi\n"
"	movl	%esi, _sy\n"
"	movzbl	%bl, %ecx\n"
"	movl	_isdig(,%ecx,4), %edx\n"
"	testl	%edx, %edx\n"
"	jne	L121\n"
"L41:\n"
"	incl	%edi\n"
"	movzbl	(%edi), %ebx\n"
"	movzbl	%bl, %ecx\n"
"	movl	_isdig(,%ecx,4), %edx\n"
"	testl	%edx, %edx\n"
"	je	L41\n"
"L121:\n"
"	movzbl	%bl, %edx\n"
"	subl	$48, %edx\n"
"	movl	%edx, -24(%ebp)\n"
"	incl	%edi\n"
"	movzbl	(%edi), %ebx\n"
"	movb	%bl, %dl\n"
"	movzbl	%bl, %ecx\n"
"	movl	_isdig(,%ecx,4), %esi\n"
"	testl	%esi, %esi\n"
"	je	L123\n"
"L46:\n"
"	movl	-24(%ebp), %ebx\n"
"	leal	(%ebx,%ebx,4), %eax\n"
"	movzbl	%dl, %esi\n"
"	leal	-48(%esi,%eax,2), %ebx\n"
"	movl	%ebx, -24(%ebp)\n"
"	incl	%edi\n"
"	movzbl	(%edi), %ebx\n"
"	movb	%bl, %dl\n"
"	movzbl	%bl, %ecx\n"
"	movl	_isdig(,%ecx,4), %esi\n"
"	testl	%esi, %esi\n"
"	jne	L46\n"
"L123:\n"
"	movl	-24(%ebp), %edx\n"
"	movl	%edx, _sx\n"
"	cmpb	$47, %bl\n"
"	ja	L125\n"
"L50:\n"
"	incl	%edi\n"
"	movzbl	(%edi), %ebx\n"
"	cmpb	$47, %bl\n"
"	jbe	L50\n"
"L125:\n"
"	movl	$0, -24(%ebp)\n"
"	movb	%bl, %al\n"
"	cmpb	$47, %bl\n"
"	jbe	L127\n"
"L55:\n"
"	incl	-24(%ebp)\n"
"	movzbl	%al, %ebx\n"
"	subl	$48, %ebx\n"
"	incl	%edi\n"
"	movl	-24(%ebp), %ecx\n"
"	movl	$_map, %esi\n"
"	movl	%ebx, 512(%esi,%ecx,4)\n"
"	movzbl	(%edi), %ebx\n"
"	movb	%bl, %al\n"
"	cmpb	$47, %bl\n"
"	ja	L55\n"
"L127:\n"
"	movl	-24(%ebp), %edx\n"
"	movl	%edx, _width\n"
"	movl	$1, %ecx\n"
"	.p2align 4,,15\n"
"L143:\n"
"	incl	%edi\n"
"	cmpb	$10, %bl\n"
"	je	L145\n"
"	movzbl	(%edi), %ebx\n"
"	jmp	L143\n"
"L145:\n"
"	movzbl	(%edi), %ebx\n"
"	movzbl	%bl, %edx\n"
"	movl	_isnd(,%edx,4), %esi\n"
"	testl	%esi, %esi\n"
"	jne	L129\n"
"	.p2align 4,,15\n"
"L65:\n"
"	incl	%edi\n"
"	movzbl	(%edi), %ebx\n"
"	movzbl	%bl, %esi\n"
"	movl	_isnd(,%esi,4), %edx\n"
"	testl	%edx, %edx\n"
"	je	L65\n"
"L129:\n"
"	movb	%bl, %al\n"
"	cmpb	$10, %bl\n"
"	je	L57\n"
"	incl	%ecx\n"
"	movl	$0, -24(%ebp)\n"
"	cmpb	$47, %bl\n"
"	jbe	L143\n"
"	movl	%ecx, %esi\n"
"	sall	$7, %esi\n"
"	.p2align 4,,15\n"
"L71:\n"
"	incl	-24(%ebp)\n"
"	movl	-24(%ebp), %ebx\n"
"	leal	(%ebx,%esi), %edx\n"
"	movzbl	%al, %ebx\n"
"	subl	$48, %ebx\n"
"	incl	%edi\n"
"	movl	%ebx, _map(,%edx,4)\n"
"	movzbl	(%edi), %eax\n"
"	movb	%al, %bl\n"
"	cmpb	$47, %al\n"
"	ja	L71\n"
"	jmp	L143\n"
"L57:\n"
"	movl	%ecx, _height\n"
"	movl	_sy, %esi\n"
"	sall	$7, %esi\n"
"	movl	_sx, %eax\n"
"	addl	%eax, %esi\n"
"	movl	_map(,%esi,4), %ecx\n"
"	testl	%ecx, %ecx\n"
"	je	L72\n"
"	movl	-20(%ebp), %eax\n"
"	movb	$48, (%eax)\n"
"	incl	%eax\n"
"L144:\n"
"	movb	$10, (%eax)\n"
"	incl	%eax\n"
"	movl	%eax, -20(%ebp)\n"
"	movl	-40(%ebp), %esi\n"
"	testl	%esi, %esi\n"
"	je	L26\n"
"	movl	-20(%ebp), %ecx\n"
"	movb	$10, (%ecx)\n"
"	incl	%ecx\n"
"	movl	%ecx, -20(%ebp)\n"
"	movl	$1, -24(%ebp)\n"
"	movl	_height, %eax\n"
"	movl	%eax, -36(%ebp)\n"
"	cmpl	%eax, -24(%ebp)\n"
"	jg	L26\n"
"	movl	_width, %esi\n"
"L102:\n"
"	movl	$1, %ecx\n"
"	cmpl	%esi, %ecx\n"
"	jg	L140\n"
"	movl	-24(%ebp), %edx\n"
"	sall	$7, %edx\n"
"	.p2align 4,,15\n"
"L101:\n"
"	leal	(%ecx,%edx), %eax\n"
"	movl	$1, _map(,%eax,4)\n"
"	incl	%ecx\n"
"	cmpl	%esi, %ecx\n"
"	jle	L101\n"
"L140:\n"
"	incl	-24(%ebp)\n"
"	movl	-36(%ebp), %edx\n"
"	cmpl	%edx, -24(%ebp)\n"
"	jle	L102\n"
"L26:\n"
"	decl	-40(%ebp)\n"
"	movl	-40(%ebp), %esi\n"
"	movl	%esi, _ntests\n"
"	incl	%esi\n"
"	jne	L103\n"
"	jmp	L115\n"
"L72:\n"
"	movl	$0, -28(%ebp)\n"
"	xorl	%esi, %esi\n"
"L82:\n"
"	movl	_sy(,%esi,4), %edx\n"
"	movl	%edx, -24(%ebp)\n"
"	movl	_sx(,%esi,4), %ecx\n"
"	sall	$7, %edx\n"
"	movl	%edx, -32(%ebp)\n"
"	addl	%ecx, %edx\n"
"	movl	$1, %eax\n"
"	movl	%eax, _map(,%edx,4)\n"
"	incl	-28(%ebp)\n"
"	movl	_map+512(,%edx,4), %eax\n"
"	testl	%eax, %eax\n"
"	jne	L78\n"
"	movl	-24(%ebp), %eax\n"
"	incl	%eax\n"
"	movl	%eax, _sy(,%esi,4)\n"
"	sall	$7, %eax\n"
"	addl	%ecx, %eax\n"
"	movl	$1, _map(,%eax,4)\n"
"	incl	%esi\n"
"L78:\n"
"	movl	_map-512(,%edx,4), %eax\n"
"	testl	%eax, %eax\n"
"	jne	L79\n"
"	movl	-24(%ebp), %eax\n"
"	decl	%eax\n"
"	movl	%eax, _sy(,%esi,4)\n"
"	movl	%ecx, _sx(,%esi,4)\n"
"	sall	$7, %eax\n"
"	addl	%ecx, %eax\n"
"	movl	$1, _map(,%eax,4)\n"
"	incl	%esi\n"
"L79:\n"
"	movl	_map+4(,%edx,4), %eax\n"
"	testl	%eax, %eax\n"
"	jne	L80\n"
"	movl	-24(%ebp), %eax\n"
"	movl	%eax, _sy(,%esi,4)\n"
"	leal	1(%ecx), %eax\n"
"	movl	%eax, _sx(,%esi,4)\n"
"	addl	-32(%ebp), %eax\n"
"	movl	$1, _map(,%eax,4)\n"
"	incl	%esi\n"
"L80:\n"
"	movl	_map-4(,%edx,4), %eax\n"
"	testl	%eax, %eax\n"
"	jne	L74\n"
"	movl	-24(%ebp), %eax\n"
"	movl	%eax, _sy(,%esi,4)\n"
"	leal	-1(%ecx), %eax\n"
"	movl	%eax, _sx(,%esi,4)\n"
"	movl	-32(%ebp), %edx\n"
"	addl	%edx, %eax\n"
"	movl	$1, %ecx\n"
"	movl	%ecx, _map(,%eax,4)\n"
"	incl	%esi\n"
"L74:\n"
"	movl	%esi, %ecx\n"
"	decl	%esi\n"
"	testl	%ecx, %ecx\n"
"	jg	L82\n"
"	movl	-28(%ebp), %ecx\n"
"	movl	$0, -24(%ebp)\n"
"	testl	%ecx, %ecx\n"
"	jle	L135\n"
"	movl	$1717986919, %esi\n"
"L87:\n"
"	movl	%ecx, %eax\n"
"	imull	%esi\n"
"	movl	%eax, -48(%ebp)\n"
"	movl	%edx, -44(%ebp)\n"
"	movl	-44(%ebp), %edx\n"
"	sarl	$2, %edx\n"
"	movl	%ecx, %eax\n"
"	sarl	$31, %eax\n"
"	subl	%eax, %edx\n"
"	leal	(%edx,%edx,4), %eax\n"
"	addl	%eax, %eax\n"
"	subl	%eax, %ecx\n"
"	movb	%cl, %al\n"
"	addb	$48, %al\n"
"	movl	-24(%ebp), %ecx\n"
"	movb	%al, _tmp(%ecx)\n"
"	incl	%ecx\n"
"	movl	%ecx, -24(%ebp)\n"
"	movl	%edx, %ecx\n"
"	testl	%edx, %edx\n"
"	jg	L87\n"
"L135:\n"
"	decl	-24(%ebp)\n"
"	cmpl	$-1, -24(%ebp)\n"
"	je	L137\n"
"L91:\n"
"	movl	-24(%ebp), %esi\n"
"	movzbl	_tmp(%esi), %ecx\n"
"	movl	-20(%ebp), %edx\n"
"	movb	%cl, (%edx)\n"
"	incl	%edx\n"
"	movl	%edx, -20(%ebp)\n"
"	decl	%esi\n"
"	movl	%esi, -24(%ebp)\n"
"	incl	%esi\n"
"	jne	L91\n"
"L137:\n"
"	movl	-20(%ebp), %eax\n"
"	jmp	L144\n"
"L141:\n"
"	movzbl	_inbuf, %ebx\n"
"	jmp	L111\n"
"L115:\n"
"	subl	$_outbuf, -20(%ebp)\n"
"	movl	-20(%ebp), %ebx\n"
"	movl	%ebx, 8(%esp)\n"
"	movl	$_outbuf, %edi\n"
"	movl	%edi, 4(%esp)\n"
"	movl	$1, (%esp)\n"
"	call	write\n"
"	movl	$0, (%esp)\n"
"	call	exit\n"
"	.p2align 4,,15\n"
".comm _ntests, 16\n"
".comm _width, 16\n"
".comm _height, 16\n"
".comm _map, 65536\n"
".comm _sy, 262144\n"
".comm _sx, 262144\n"
".comm _isdig, 1024\n"
".comm _isnd, 1024\n"
".comm _tmp, 256\n"
".comm _inbuf, 1048576\n"
".comm _outbuf, 1048576\n"
);
}
