int main()
{
__asm__ __volatile__(
"	pushl	%ebp\n"
"	movl	%esp, %ebp\n"
"	pushl	%edi\n"
"	pushl	%esi\n"
"	pushl	%ebx\n"
"	subl	$28, %esp\n"
"	movl	$0, (%esp)\n"
"	movl	$1073741824, %eax\n"
"	movl	%eax, 4(%esp)\n"
"	call	log\n"
"	fstpl	_l2\n"
"	movl	$31457280, %eax\n"
"	movl	%eax, 8(%esp)\n"
"	movl	$_inbuf, %ebx\n"
"	movl	%ebx, 4(%esp)\n"
"	movl	$0, (%esp)\n"
"	call	read\n"
"	movl	$_isdig, %edi\n"
"	movl	$1024, %eax\n"
"	xorl	%edx, %edx\n"
"	testl	$4, %edi\n"
"	je	L19\n"
"	xorl	%ecx, %ecx\n"
"	movl	%ecx, _isdig\n"
"	movl	$_isdig+4, %edi\n"
"	movl	$1020, %eax\n"
"L19:\n"
"	cld\n"
"	movl	%eax, %ecx\n"
"	shrl	$2, %ecx\n"
"	movl	%edx, %eax\n"
"	rep\n"
"	stosl\n"
"	movl	$_isdigx, %edi\n"
"	movl	$1024, %eax\n"
"	testl	$4, %edi\n"
"	je	L20\n"
"	xorl	%esi, %esi\n"
"	movl	%esi, _isdigx\n"
"	movl	$_isdigx+4, %edi\n"
"	movl	$1020, %eax\n"
"L20:\n"
"	cld\n"
"	movl	%eax, %ecx\n"
"	shrl	$2, %ecx\n"
"	movl	%edx, %eax\n"
"	rep\n"
"	stosl\n"
"	movl	$48, %esi\n"
"L25:\n"
"	movl	$1, %edx\n"
"	movl	%edx, _isdig(,%esi,4)\n"
"	incl	%esi\n"
"	cmpl	$57, %esi\n"
"	jle	L25\n"
"	movl	$48, %esi\n"
"L30:\n"
"	movl	$1, %edi\n"
"	movl	%edi, _isdigx(,%esi,4)\n"
"	incl	%esi\n"
"	cmpl	$57, %esi\n"
"	jle	L30\n"
"	movl	$1, %edi\n"
"	movl	%edi, _isdigx+184\n"
"	movl	$1, %edx\n"
"	movl	%edx, _isdigx+180\n"
"	movsbl	_inbuf,%esi\n"
"	movl	_isdig(,%esi,4), %ecx\n"
"	testl	%ecx, %ecx\n"
"	jne	L97\n"
"L34:\n"
"	incl	%ebx\n"
"	movzbl	(%ebx), %edx\n"
"	movsbl	%dl,%esi\n"
"	movl	_isdig(,%esi,4), %ecx\n"
"	testl	%ecx, %ecx\n"
"	je	L34\n"
"L81:\n"
"	movsbl	%dl,%ecx\n"
"	leal	-48(%ecx), %edi\n"
"	incl	%ebx\n"
"	movzbl	(%ebx), %edx\n"
"	movsbl	%dl,%eax\n"
"	movl	_isdig(,%eax,4), %esi\n"
"	testl	%esi, %esi\n"
"	je	L83\n"
"	movl	%eax, %ecx\n"
"L39:\n"
"	leal	(%edi,%edi,4), %edx\n"
"	leal	-48(%ecx,%edx,2), %edi\n"
"	incl	%ebx\n"
"	movzbl	(%ebx), %edx\n"
"	movsbl	%dl,%esi\n"
"	movl	%esi, %ecx\n"
"	movl	_isdig(,%esi,4), %esi\n"
"	testl	%esi, %esi\n"
"	jne	L39\n"
"L83:\n"
"	movl	$1, -20(%ebp)\n"
"	cmpl	%edi, -20(%ebp)\n"
"	jg	L85\n"
"L75:\n"
"	movsbl	%dl,%esi\n"
"	movl	_isdig(,%esi,4), %ecx\n"
"	testl	%ecx, %ecx\n"
"	jne	L87\n"
"	.p2align 4,,15\n"
"L47:\n"
"	incl	%ebx\n"
"	movzbl	(%ebx), %edx\n"
"	movsbl	%dl,%esi\n"
"	movl	_isdig(,%esi,4), %ecx\n"
"	testl	%ecx, %ecx\n"
"	je	L47\n"
"L87:\n"
"	movsbl	%dl,%ecx\n"
"	leal	-48(%ecx), %esi\n"
"	incl	%ebx\n"
"	movzbl	(%ebx), %edx\n"
"	movsbl	%dl,%eax\n"
"	movl	_isdig(,%eax,4), %ecx\n"
"	testl	%ecx, %ecx\n"
"	je	L89\n"
"	movl	%eax, %ecx\n"
"	.p2align 4,,15\n"
"L52:\n"
"	leal	(%esi,%esi,4), %edx\n"
"	leal	-48(%ecx,%edx,2), %esi\n"
"	incl	%ebx\n"
"	movzbl	(%ebx), %edx\n"
"	movsbl	%dl,%eax\n"
"	movl	%eax, %ecx\n"
"	movl	_isdig(,%eax,4), %eax\n"
"	testl	%eax, %eax\n"
"	jne	L52\n"
"L89:\n"
"	movl	%esi, %ecx\n"
"	movl	%esi, _n\n"
"	xorl	%esi, %esi\n"
"	cmpl	%ecx, %esi\n"
"	jge	L91\n"
"	fldz\n"
"	fld1\n"
"	flds	LC7\n"
"	.p2align 4,,15\n"
"L74:\n"
"	movsbl	%dl,%eax\n"
"	movl	_isdigx(,%eax,4), %eax\n"
"	testl	%eax, %eax\n"
"	jne	L93\n"
"	.p2align 4,,15\n"
"L60:\n"
"	incl	%ebx\n"
"	movzbl	(%ebx), %edx\n"
"	movsbl	%dl,%eax\n"
"	movl	_isdigx(,%eax,4), %eax\n"
"	testl	%eax, %eax\n"
"	je	L60\n"
"L93:\n"
"	fld	%st(1)\n"
"	cmpb	$45, %dl\n"
"	je	L102\n"
"L62:\n"
"	fld	%st(3)\n"
"	movsbl	%dl,%eax\n"
"	cmpl	$0, _isdig(,%eax,4)\n"
"	je	L95\n"
"	fld	%st(2)\n"
"	.p2align 4,,15\n"
"L67:\n"
"	fmul	%st, %st(1)\n"
"	subl	$48, %eax\n"
"	pushl	%eax\n"
"	fildl	(%esp)\n"
"	addl	$4, %esp\n"
"	faddp	%st, %st(2)\n"
"	fxch	%st(1)\n"
"	fstps	-16(%ebp)\n"
"	flds	-16(%ebp)\n"
"	incl	%ebx\n"
"	movzbl	(%ebx), %edx\n"
"	movsbl	%dl,%eax\n"
"	cmpl	$0, _isdig(,%eax,4)\n"
"	je	L103\n"
"	fxch	%st(1)\n"
"	jmp	L67\n"
"	.p2align 4,,7\n"
"L103:\n"
"	fstp	%st(1)\n"
"L95:\n"
"	cmpb	$46, %dl\n"
"	je	L104\n"
"L68:\n"
"	fmulp	%st, %st(1)\n"
"	fstps	_a(,%esi,4)\n"
"	incl	%esi\n"
"	cmpl	%ecx, %esi\n"
"	jl	L74\n"
"	fstp	%st(0)\n"
"	fstp	%st(0)\n"
"	fstp	%st(0)\n"
"L91:\n"
"	call	_solve\n"
"	fstpl	8(%esp)\n"
"	movl	-20(%ebp), %esi\n"
"	movl	%esi, 4(%esp)\n"
"	movl	$LC9, (%esp)\n"
"	call	printf\n"
"	incl	-20(%ebp)\n"
"	cmpl	%edi, -20(%ebp)\n"
"	jg	L85\n"
"	movzbl	(%ebx), %edx\n"
"	jmp	L75\n"
"L104:\n"
"	movl	$0x3dcccccd, %edx\n"
"	movl	%edx, -24(%ebp)\n"
"	flds	-24(%ebp)\n"
"	incl	%ebx\n"
"	movzbl	(%ebx), %eax\n"
"	movb	%al, %dl\n"
"	movsbl	%al,%eax\n"
"	cmpl	$0, _isdig(,%eax,4)\n"
"	je	L100\n"
"	fld	%st(3)\n"
"	.p2align 4,,15\n"
"L73:\n"
"	subl	$48, %eax\n"
"	pushl	%eax\n"
"	fildl	(%esp)\n"
"	addl	$4, %esp\n"
"	fmul	%st(2), %st\n"
"	faddp	%st, %st(3)\n"
"	incl	%ebx\n"
"	fld	%st(0)\n"
"	fdivrp	%st, %st(2)\n"
"	fxch	%st(1)\n"
"	fstps	-16(%ebp)\n"
"	flds	-16(%ebp)\n"
"	movzbl	(%ebx), %eax\n"
"	movb	%al, %dl\n"
"	movsbl	%al,%eax\n"
"	cmpl	$0, _isdig(,%eax,4)\n"
"	je	L105\n"
"	fxch	%st(1)\n"
"	jmp	L73\n"
"L105:\n"
"	fstp	%st(0)\n"
"L100:\n"
"	fstp	%st(0)\n"
"	jmp	L68\n"
"L102:\n"
"	fstp	%st(0)\n"
"	incl	%ebx\n"
"	movl	$0xbf800000, %edx\n"
"	movl	%edx, -24(%ebp)\n"
"	flds	-24(%ebp)\n"
"	movzbl	(%ebx), %edx\n"
"	jmp	L62\n"
"L97:\n"
"	movzbl	_inbuf, %edx\n"
"	jmp	L81\n"
"L85:\n"
"	movl	$0, (%esp)\n"
"	call	exit\n"
"_solve:\n"
"	pushl	%ebp\n"
"	movl	%esp, %ebp\n"
"	pushl	%edi\n"
"	pushl	%esi\n"
"	pushl	%ebx\n"
"	subl	$60, %esp\n"
"	movl	_n, %eax\n"
"	leal	-1(%eax), %esi\n"
"	movl	%esi, %edi\n"
"	sarl	%edi\n"
"	testl	$1, %esi\n"
"	je	L2\n"
"	pushl	%eax\n"
"	fildl	(%esp)\n"
"	addl	$4, %esp\n"
"	fstpl	(%esp)\n"
"	call	lgamma\n"
"	fstpl	-32(%ebp)\n"
"	leal	1(%edi), %ebx\n"
"	pushl	%ebx\n"
"	fildl	(%esp)\n"
"	addl	$4, %esp\n"
"	fstpl	(%esp)\n"
"	call	lgamma\n"
"	fsubrl	-32(%ebp)\n"
"	fstpl	-32(%ebp)\n"
"	movl	%esi, %edx\n"
"	subl	%edi, %edx\n"
"	incl	%edx\n"
"	pushl	%edx\n"
"	fildl	(%esp)\n"
"	addl	$4, %esp\n"
"	fstpl	(%esp)\n"
"	call	lgamma\n"
"	fsubrl	-32(%ebp)\n"
"	fstpl	-32(%ebp)\n"
"	pushl	%esi\n"
"	fildl	(%esp)\n"
"	addl	$4, %esp\n"
"	fmull	_l2\n"
"	fsubrl	-32(%ebp)\n"
"	fstpl	(%esp)\n"
"	call	exp\n"
"	fldz\n"
"	movl	%edi, %edx\n"
"	movl	%ebx, %ecx\n"
"	testl	%edi, %edi\n"
"	js	L121\n"
"	fld1\n"
"	fldl	LC2\n"
"	.p2align 4,,15\n"
"L9:\n"
"	flds	_a(,%ecx,4)\n"
"	fadds	_a(,%edx,4)\n"
"	fmul	%st(4), %st\n"
"	faddp	%st, %st(3)\n"
"	pushl	%edx\n"
"	fildl	(%esp)\n"
"	movl	%esi, %ebx\n"
"	subl	%edx, %ebx\n"
"	movl	%ebx, (%esp)\n"
"	fildl	(%esp)\n"
"	addl	$4, %esp\n"
"	fadd	%st(3), %st\n"
"	fdivrp	%st, %st(1)\n"
"	fmulp	%st, %st(4)\n"
"	fucom	%st(3)\n"
"	fnstsw	%ax\n"
"	sahf\n"
"	ja	L119\n"
"	incl	%ecx\n"
"	decl	%edx\n"
"	jns	L9\n"
"L119:\n"
"	fstp	%st(0)\n"
"L120:\n"
"	fstp	%st(0)\n"
"L121:\n"
"	fstp	%st(1)\n"
"	addl	$60, %esp\n"
"	popl	%ebx\n"
"	popl	%esi\n"
"	popl	%edi\n"
"	popl	%ebp\n"
"	ret\n"
"	.p2align 4,,7\n"
"L2:\n"
"	pushl	%eax\n"
"	fildl	(%esp)\n"
"	addl	$4, %esp\n"
"	fstpl	(%esp)\n"
"	call	lgamma\n"
"	leal	1(%edi), %ebx\n"
"	pushl	%ebx\n"
"	fildl	(%esp)\n"
"	addl	$4, %esp\n"
"	fstpl	(%esp)\n"
"	fstpl	-56(%ebp)\n"
"	call	lgamma\n"
"	fadd	%st(0), %st\n"
"	fldl	-56(%ebp)\n"
"	fsubp	%st, %st(1)\n"
"	pushl	%esi\n"
"	fildl	(%esp)\n"
"	addl	$4, %esp\n"
"	fmull	_l2\n"
"	fsubrp	%st, %st(1)\n"
"	fstpl	(%esp)\n"
"	call	exp\n"
"	fld	%st(0)\n"
"	fmuls	_a(,%edi,4)\n"
"	pushl	%edi\n"
"	fildl	(%esp)\n"
"	movl	%esi, %edx\n"
"	subl	%edi, %edx\n"
"	movl	%edx, (%esp)\n"
"	fildl	(%esp)\n"
"	addl	$4, %esp\n"
"	fld1\n"
"	fadd	%st, %st(1)\n"
"	fxch	%st(2)\n"
"	fdivp	%st, %st(1)\n"
"	fmulp	%st, %st(3)\n"
"	movl	%ebx, %ecx\n"
"	movl	%edi, %edx\n"
"	decl	%edx\n"
"	js	L120\n"
"	fldl	LC2\n"
"	.p2align 4,,15\n"
"L17:\n"
"	flds	_a(,%ecx,4)\n"
"	fadds	_a(,%edx,4)\n"
"	fmul	%st(4), %st\n"
"	faddp	%st, %st(3)\n"
"	pushl	%edx\n"
"	fildl	(%esp)\n"
"	movl	%esi, %edi\n"
"	subl	%edx, %edi\n"
"	movl	%edi, (%esp)\n"
"	fildl	(%esp)\n"
"	addl	$4, %esp\n"
"	fadd	%st(3), %st\n"
"	fdivrp	%st, %st(1)\n"
"	fmulp	%st, %st(4)\n"
"	fucom	%st(3)\n"
"	fnstsw	%ax\n"
"	sahf\n"
"	ja	L119\n"
"	incl	%ecx\n"
"	decl	%edx\n"
"	jns	L17\n"
"	jmp	L119\n"
"LC9:\n"
"	.ascii \"Case #%d: %.3f\\12\\0\"\n"
"	.align 4\n"
"LC7:\n"
"	.long	1092616192\n"
"	.align 8\n"
"LC2:\n"
"	.long	-1698910392\n"
"	.long	1048238066\n"
"	.align 8\n"
".lcomm _n,16\n"
".lcomm _l2,16\n"
".lcomm _isdigx,1024\n"
".lcomm _isdig,1024\n"
".lcomm _a,262144\n"
".lcomm _inbuf,31457280\n"
);
}
